### ISSUE TITLE
Requesting a new app: GIMP

### ISSUE THREAD

**Issue by M-Rick** [wimpysworld/deb-get#1001]
## Requesting a new app ✨

 - [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Gimp
 - Download URL: https://ppa.launchpadcontent.net/ubuntuhandbook1/gimp/ubuntu/pool/main/g/gimp/gimp_2.10.36-0build1~ubuntu2310_amd64.deb
https://ppa.launchpadcontent.net/ubuntuhandbook1/gimp/ubuntu/pool/main/g/gimp/gimp_2.10.36-0build1~ubuntu2310_arm64.deb
 - Website URL: https://www.gimp.org/
 - App Summary: GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows used for image manipulation (retouching) and image editing, free-form drawing, transcoding between different image file formats, and more specialized tasks. It is extensible by means of plugins, and scriptable. It is not designed to be used for drawing, though some artists and creators have used it in this way.

```
sudo add-apt-repository -y ppa:ubuntuhandbook1/gimp && sudo apt update
sudo apt install -y gimp gimp-help-fr
```

**Comment by philclifford** [comment]
see https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md

* Software **has to be published authoritatively by the upstream vendor, project or maintainer**. Packages published by unassociated community contributors will not be accepted.
