### ISSUE TITLE
Bump version in debian changelog

### ISSUE THREAD

**Issue by hsbasu** [wimpysworld/deb-get#1003]
@flexiondotorg Can you please bump the version in `debian/changelog` file to facilitate building on Launchpad?

**Comment by hsbasu** [comment]
@flexiondotorg A gentle reminder.

**Comment by hsbasu** [comment]
@philclifford Any idea on this request?

**Comment by flexiondotorg** [comment]
I suggest you fork the Debian packaging for building in LP. The automation that publishes new releases to the GitHub page automatically bumps the version.
