### ISSUE TITLE
Cannot install deb-get on Ubuntu 24.04 (I'm using WSL though that should not make any difference)

### ISSUE THREAD

**Issue by TiLopes** [wimpysworld/deb-get#1029]
### Expected behavior

The installation should succeed without any errors.

### Actual behavior

The installation fails stating that it is not Debian/Ubuntu derived.
`ERROR! Ubuntu Noble is not supported because it is not derived from a supported Debian or Ubuntu release.`
I tried both through the script and manually installing the `.deb`

### Steps to reproduce

Follow installion in README.md

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
PRETTY_NAME="Ubuntu Noble Numbat (development branch)"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

#### /etc/lsb-release

```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu Noble Numbat (development branch)"
```

**Comment by HwapX** [comment]
Same here with my system upgraded to Ubuntu 24.04 Noble Numbat beta.

When support for this version will be added?

**Comment by Fuseteam** [comment]
24.04 isn't out yet, it is in its beta phase as we speak, so deb-get cannot support it yet

**Comment by dacorsa** [comment]
Hi @Fuseteam ,
was released yesterday,  we'll waiting deb-get will supports it, ;)

**Comment by saullubkin** [comment]
I have the same problem.  I hope that deb-get will support Ubuntu 24.04 soon.

**Comment by Fuseteam** [comment]
it's only a few days guys come on, give them time

**Comment by dacorsa** [comment]
Thanks for all, now works well !!!
Thanks to all the team deb-get !!!
best regards

**Comment by cst-rmrz** [comment]
`deb-get` still will not install on desktop Ubuntu 24.04

`Setting up deb-get (0.4.0-1) ...
  [!] ERROR! Ubuntu Noble is not supported because it is not derived from a supported Debi
an or Ubuntu release.`

**Comment by dacorsa** [comment]
@cst-rmrz 
you have to install in this way:

cd /app
git clone https://github.com/wimpysworld/deb-get.git
cd /app/deb-get/
git reset --hard
git pull
cd /app/deb-get/docs/
ls -la /usr/bin/deb-get*
make install
ls -la /usr/bin/deb-get*

**Comment by cst-rmrz** [comment]
> @cst-rmrz
you have to install in this way:
>
> cd /app
git clone https://github.com/wimpysworld/deb-get.git
cd /app/deb-get/
git reset --hard
git pull
cd /app/deb-get/docs/
ls -la /usr/bin/deb-get*
make install
ls -la /usr/bin/deb-get*

Works perfectly!
Thanks so much.

**Comment by Fuseteam** [comment]
@TiLopes can you also confirm?

**Comment by TiLopes** [comment]
It works now.

**Comment by Fuseteam** [comment]
feel free to close issue, in that case i would say @TiLopes :smile:

**Comment by saullubkin** [comment]
I'm running Ubuntu 24.04.

Here's what I just got trying to use deb-get in a terminal:

 sudo deb-get install zoom dropbox
[sudo] password for saul:
  [!] ERROR! Ubuntu Noble is not supported because it is not derived from a supported Debian or Ubuntu release.

So I know that the issue is not solved yet.

  --  Saul

________________________________________
From: Tiago Lopes ***@***.***>
Sent: Friday, May 10, 2024 11:58 AM
To: wimpysworld/deb-get
Cc: Lubkin, Saul; Comment
Subject: [EXT] Re: [wimpysworld/deb-get] Cannot install deb-get on Ubuntu 24.04 (I'm using WSL though that should not make any difference) (Issue #1029)

Closed #1029<https://urldefense.com/v3/__https://github.com/wimpysworld/deb-get/issues/1029__;!!CGUSO5OYRnA7CQ!Y8UEZS8kj-ckMm3HZ-xuTQ0fSvyIQ6vwKAw_n3uQStO_2_SbLKif7E1-_qiK9jowdh0HbcdnQI-zWFdLUrl71IdJu1SvaO4$> as completed.

**Comment by Fuseteam** [comment]
try this @saullubkin https://github.com/wimpysworld/deb-get/issues/1029#issuecomment-2099002203

**Comment by philclifford** [comment]
> sudo deb-get

**Never** use `sudo deb-get`!

**Comment by moorepants** [comment]
I did a fresh install, as per the readme instructions, and I still get the error:

```
  [!] ERROR! Ubuntu Noble is not supported because it is not derived from a supported Debian or Ubuntu release.
```

I'm guessing a new release needs to be made before this functions on Noble. Is that possible? I use this to install Zoom and Zoom has recently dropped support for very recent old versions and I'm not able to update Zoom with deb-get anymore and cannot use it.

**Comment by philclifford** [comment]
See comments above: you just need to get the latest deb-get until a new release arrives. Clone or download the repo and go into the docs directory and `sudo make install` . Or just download the latest `deb-get` script and use that one.

**Comment by saullubkin** [comment]
I downloaded the shell script from wimpysworld, and called in deb-get-sh.
The following command works well for me:

sudo /bin/bash ~/deb-get.sh install zoom dropbox

(But at the moment, to the best of my knowledge, there is not yet an executable deb-get that works on 24.04.)

  --  Saul

________________________________________
From: Phil Clifford ***@***.***>
Sent: Friday, May 17, 2024 2:41 PM
To: wimpysworld/deb-get
Cc: Lubkin, Saul; Mention
Subject: [EXT] Re: [wimpysworld/deb-get] Cannot install deb-get on Ubuntu 24.04 (I'm using WSL though that should not make any difference) (Issue #1029)

See comments above: you just need to get the latest deb-get until a new release arrives. Clone or download the repo and go into the docs directory and sudo make install . Or just download the latest deb-get script and use that one.
