### ISSUE TITLE
ERROR! Missing required information of github package emby-server

### ISSUE THREAD

**Issue by yermulnik** [wimpysworld/deb-get#1049]
### Expected behavior

`deb-get` runs w/o errors

### Actual behavior

`deb-get` runs with errors

### Steps to reproduce

`env DEBGET_TOKEN=ghp_XXX deb-get update`

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
> cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### /etc/lsb-release

```bash
> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

#### deb-get version

```bash
> deb-get version
0.4.0
```

### deb-get update

```bash
> env DEBGET_TOKEN=ghp_XXX deb-get update
  [+] Updating /etc/deb-get/01-main
-=#=-#   #     #
  [+] Updating /etc/deb-get/91-fixes
-=#=-#   #     #
  [+] Updating cache of supported apps in the background
  [+] Updating /var/cache/deb-get/deb-get.json
Hit:10 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
[…]
  [!] ERROR! Missing required information of github package emby-server:
URL=
VERSION_PUBLISHED=
[…]
Fetched 4.778 kB in 41s (116 kB/s)
Reading package lists...
```

**Comment by yermulnik** [comment]
@philclifford Are end-users supposed to use HEAD or the latest version which is what I'm on (`0.4.0`)? The "works for me" resolution is odd 😲

**Comment by yermulnik** [comment]
> Possibly transient issue with github while release assets were building (this is not uncommon)

How do I get out of the situation?

**Comment by philclifford** [comment]
> > Possibly transient issue with github while release assets were building (this is not uncommon)
> 
> How do I get out of the situation?

re-run the update. If the assets are there now you will succeed.  You'll need to remove the cached json or set the cache timeout low to force re-downloading the info. Possibly `deb-get install emby-server` will download the new info anyway regardless of the cache time iirc.

It's not a "works here" solution but a "works when it is ready" solution.  The note above will make a general issue to try and fix the actual problem.

**Comment by yermulnik** [comment]
> re-run the update. If the assets are there now you will succeed.

Still the same error.

> You'll need to remove the cached json or set the cache timeout low to force re-downloading the info.

Appreciate your assistance. Would you please also share how to accomplish each of the options?
I'm an end-user, rather than a `deb-get` dev 🤷🏻 

> Possibly `deb-get install emby-server` will download the new info anyway regardless of the cache time iirc.

I do not need `emby-server`. It just breaks `deb-get` for me.

> The note above will make a general issue to try and fix the actual problem.

Please share a bit more detailed instructions for end-user.

**Comment by yermulnik** [comment]
Aha, so the "cached json" is `/var/cache/deb-get/emby-server.json`. Now it runs w/o error.

**Comment by philclifford** [comment]
Glad it's working for you.  We do need better documentation for end users around troubleshooting and FAQ-type questions. 
Your input is very valuable in this effort. Thanks

**Comment by philclifford** [comment]
Some relevant information is in the output of `deb-get` (which is included in the `man` [page](https://github.com/wimpysworld/deb-get/blob/main/docs/deb-get.1.md#commands) and the [README.md](https://github.com/wimpysworld/deb-get/blob/main/README.md#usage) so I'll drop a snip here as a stash for possibly making a troubleshooting tip or two.

```
$ deb-get
  [!] ERROR! You must specify an action.

Usage

deb-get {update [--repos-only] [--quiet] | upgrade | show <pkg list> | install <pkg list>
        | reinstall <pkg list> | remove [--remove-repo] <pkg list>
        | purge [--remove-repo] <pkg list>
        | search [--include-unsupported] <regex> | cache | clean
        | list [--include-unsupported] [--raw|--installed|--not-installed]
        | prettylist [<repo>] | csvlist [<repo>] | fix-installed [--old-apps]
        | help | version}
[...]
clean
    clean clears out the local repository (/var/cache/deb-get) of retrieved
    package files.
[...]
cache
    list the contents of the deb-get cache (/var/cache/deb-get).
```

`deb-get clean` is often useful in problem situations before trying an update. It is a blunt instrument though, so if there's a particular problem package then `sudo rm /var/cache/deb-get/<package>.{json,html}` is more targetted

We do need to document the DEBGET_CACHE_RTN environment variable, which allows overriding the default 1 hour cache retention by setting a lower or higher value in minutes : `export DEBGET_CACHE_RTN=1` . When troubleshooting a single package setting a high value can speed things up if you remove the one cached file before each update attempt.

**Comment by yermulnik** [comment]
> for end users around troubleshooting and FAQ-type questions.

That would be indeed great. Maybe also spit out a short one-step direction on what may help, like `Try deleting "/var/cache/deb-get/<package>.{json,html}" file` along the error message.

**Comment by yermulnik** [comment]
@philclifford Apologies for resurrecting this old issue, though I'm hitting somewhat alike but a different on `deb-get update`:
```
  [!] ERROR! Missing required information of direct package glab:
URL=
VERSION_PUBLISHED=
```
I tried the same fix as previously, though I'm stuck with missing cache file:
```shell
> deb-get show glab
  [!] ERROR! Missing required information of direct package glab:
URL=
VERSION_PUBLISHED=

> ll /var/cache/deb-get/*glab*
ls: cannot access '/var/cache/deb-get/*glab*': No such file or directory
```
Seeking your advice on how to fix this this time. Thanks in advance.

**Comment by philclifford** [comment]
Odd.  I think I know the reason though:  I think glab needs a new function for getting its info from gitlab which went into `deb-get` alongside the PR that addded `glab` using it.  If you update your `deb-get` to the one from head (or any after the commit that merged `glab` in) it should work for you as it does for me. 

Note to self and @wimpysworld/deb-get-devs : if a package is to be added that requires new functionality in `deb-get` to work we need to hold off adding the package definition until after the relevant code is merged and released.


``` text 
deb-get show glab
Glab
  Package:	glab
  Repository:	90-contribs
  Updater:	deb-get
  Installed:	No
  Published:	1.40.0
  Architecture:	amd64
  Download:	https://gitlab.com/gitlab-org/cli/-/releases/v1.40.0/downloads/glab_1.40.0_Linux_x86_64.deb
  Website:	https://gitlab.com/gitlab-org/cli
  Summary:	A GitLab CLI tool bringing GitLab to your command line
```

**Comment by philclifford** [comment]
The missing code is in https://github.com/wimpysworld/deb-get/commit/ae36cad1836a6d3d7afaebf0ec2ff1b4240172e8

See https://github.com/wimpysworld/deb-get/commit/ae36cad1836a6d3d7afaebf0ec2ff1b4240172e8.patch

**Comment by yermulnik** [comment]
@philclifford Thank you for details.
```shell
> curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | bash -s install deb-get
  [+] Updating /var/cache/deb-get/deb-get.json
  [*] WARNING! Updating /var/cache/deb-get/deb-get.json failed.
  [+] deb-get_0.4.0-1_all.deb is up to date.

> deb-get show glab
  [!] ERROR! Missing required information of direct package glab:
URL=
VERSION_PUBLISHED=
```
So I went forcible =)
```shell
> curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | tee /bin/deb-get
```
And now it all fine.
Thanks for the insights and hints.

**Comment by philclifford** [comment]
Always glad to help, or at least try.  Glad it's working for you again.

**Comment by yermulnik** [comment]
Hmm, it seems like I again am hitting issue with `glab` despite having `deb-get` from HEAD =(
Probably related to https://github.com/wimpysworld/deb-get/issues/1069 🤔 
`deb-get show glab` works okay, though I'm getting the below error when running my nightly `env DEBGET_TOKEN=ghp_[…]] timeout 15m deb-get update --quiet` cron job:
```
  [!] ERROR! Missing required information of direct package glab:
URL=
VERSION_PUBLISHED=
```

**Comment by yermulnik** [comment]
It's getting worse 😢 No changes, the `deb-get update` task is running daily from `/etc/crontab`.
```shell
  [!] ERROR! Missing required information of website package bitwig-studio:
URL=
VERSION_PUBLISHED=
  [!] ERROR! Missing required information of website package bluejeans-v2:
URL=
VERSION_PUBLISHED=
  [!] ERROR! Missing required information of direct package glab:
URL=
VERSION_PUBLISHED=
```

Is there maybe an option to "blacklist" specific packages from the "index" list?
None of the above listed are installed. It's just they are in the `deb-get` index.

@philclifford Seeking your assistance 🙏🏻
