### ISSUE TITLE
compile on ubuntu

### ISSUE THREAD

**Issue by dacorsa** [wimpysworld/deb-get#1054]
Hi all,
how can i compile deb-get on ubuntu from latest code of github?
Thanks, best regards.

**Comment by philclifford** [comment]
There is no compile - it is _just_ a `bash` script.  There is a Makefile in docs/ which will help put things in place.

**Comment by dacorsa** [comment]
Good morning @philclifford 
Thanks for your reply, i did:
cd /app/deb-get/docs/
make install
and that's all, best regards, you're a gentleman.
