### ISSUE TITLE
App request: Manuskript

### ISSUE THREAD

**Issue by techmagus** [wimpysworld/deb-get#1056]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [Y] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Manuskript
 - Download URL: https://github.com/olivierkes/manuskript
 - Website URL: https://www.theologeek.ch/manuskript/
 - App Summary: A open-source tool for writers.  Manuskript is a perfect tool for those writer who like to organize and plan everything before writing.

---

P.S.

I'm not sure if this will qualify, but similar to Hugo where it's still in v0.xx, Manuskript is very much usable for daily (and professional) use.

**Comment by philclifford** [comment]
Looks interesting.  The "early development" caveats might disqualify, but I'll give it a spin.

**Comment by dchurch315** [comment]
> Looks interesting. The "early development" caveats might disqualify, but I'll give it a spin.

I've actually been using Manuskript for the last six years - the main developer is just very cautious about incrementing the version number in general.
