### ISSUE TITLE
bug: 🐛 Adding glab to 01-main causes errors until the required function gets into users'  deb-get

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#1069]
## Reporting a bug 🐛

Until a new release is made the required function and other amendments to allow them to get the package info from gitlab are not present in end-users' `deb-get` but their next and subsequent `deb-get update` will generate "missing info" errors because there is no file retrieved.

It all works fine if the user has a version of `deb-get` at or after the commit that introduced the new behaviour. 

[!TIP] Users affected by this can overcome the problem by fetching the `deb-get` from the HEAD of the main branch.

Maybe we should have a "breaking changes" dev branch that such changes can be merged into and which can be merged into main as part of a release.

**Comment by thestub** [comment]
We need to add better error handling, as currently the stability of the tool is in the hands of the maintainers of other application.

**Comment by philclifford** [comment]
> currently the stability of the tool is in the hands of the maintainers of other application.

That is inevitable I'm afraid.  This problem however was self-inflicted and entirely my fault for not being awake enough to remember that before we commit a new package definition to the repository our users will fetch on their next update which depends on functionality in `deb-get` that they will not yet have if using the current release we must make a new release with such functionality included.  The package definition can be added after the release is out.
