### ISSUE TITLE
[`strem.io`] Missing required information of website package

### ISSUE THREAD

**Issue by yermulnik** [wimpysworld/deb-get#1070]
## Reporting a bug 🐛

As of look of it `strem.io` has changed download links for Linux
Refs:
* https://github.com/wimpysworld/deb-get/blob/main/01-main/packages/stremio
* https://www.stremio.com/downloads

### Expected behavior

`deb-get update` runs w/o errors.

### Actual behavior

```shell
> deb-get update --quiet
[…]
   [!] ERROR! Missing required information of website package stremio:
URL=
VERSION_PUBLISHED=

> deb-get show stremio
  [!] ERROR! Missing required information of website package stremio:
URL=
VERSION_PUBLISHED=
```

### Steps to reproduce

```shell
> deb-get update --quiet
> deb-get show stremio
```

### System information

```shell
> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

#### deb-get version

```bash
> deb-get version
0.4.0
```

(grabbed `deb-get` from HEAD yesterday in scope of https://github.com/wimpysworld/deb-get/issues/1049)

**Comment by philclifford** [comment]
They have.
Here is a temporary workaround:

``` shell
sed 's/dl-linux-four-deb/https:\/\/dl.strem.io\/shell-linux\/.*\/stremio/;s/ | cut -d \"\\\"\" -f 3)/)/' /etc/deb-get/01-main.d/stremio > /etc/deb-get/99-local.d/stremio
```

the proof of the pudding: 

```
deb-get show stremio
  [+] Including local package stremio
  [!] Please consider contributing back new entries, an issue (or raise a PR) directly at https://github.com/wimpysworld/deb-get/pulls
Stremio
  Package:	stremio
  Repository:	99-local
  Updater:	deb-get
  Installed:	No
  Published:	4.4.168-1
  Architecture:	amd64
  Download:	https://dl.strem.io/shell-linux/v4.4.168/stremio_4.4.168-1_amd64.deb"
  Website:	https://www.stremio.com/
  Summary:	Watch videos, movies, TV series and TV channels instantly.
```

A fix will come as soon as a PR to update 01-main/stremio can is available and merged

**Comment by yermulnik** [comment]
Just to caveats:
* Destination dir (`/etc/deb-get/99-local.d`) needs to be created
* The resulting `URL` has extra double quote at the end (I commented in the #1071)

**Comment by philclifford** [comment]
also added to my "91-fixes" external repo
