### ISSUE TITLE
Add Cliptopia

### ISSUE THREAD

**Issue by sbstn87** [wimpysworld/deb-get#1075]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Cliptopia
 - Download URL: https://github.com/omegaui/cliptopia/releases
 - Website URL: https://github.com/omegaui/cliptopia
 - App Summary:  Cliptopia is a beautiful state-of-the-art clipboard management software for linux desktops that turns your simple clipboard into a full-fledged power house.

**Comment by philclifford** [comment]
Currently beta and not yet released as stable. Please re-open when it reaches a stable release.
