### ISSUE TITLE
Please enable Noble (Ubuntu 24.04) support

### ISSUE THREAD

**Issue by lproven** [wimpysworld/deb-get#1077]
It is time. It is a known distro in the list. It's been out since last month.

I can't install deb-get on my Noble boxes, and the [new release of Asmi Linux](https://blog.teejeetech.com/2024/04/27/asmi-24-04-final/) (formerly known as Zinc) which came with it as standard and is how I first encountered the program doesn't and can't include the deb-get utility.

**Comment by philclifford** [comment]
Already supported by #1057.  Just use the main branch as there are also important fixes there too.

**Comment by teejee2008** [comment]
Please release a new version. Anyone trying to install the current release, or install using the installation command mentioned in the README will get an error on Noble.

**Comment by lproven** [comment]
> Just use the main branch as there are also important fixes there too

This requires, at a minimum, installing Git, connecting to Github, giving credentials, and cloning the repo. That is a considerable amount of work, bandwidth (some users are on metered or slow connections), and is thus not an acceptable answer.

It is quicker and easier to add repos manually, or hand-download `.deb` files for apps that add their own repos (e.g. Google Chrome). 

Remember the purpose of `deb-get` is convenience and time-saving.

Please bear in mind that there are _already distros releasing versions_ which would normally include Deb-Get which can't do so because you've failed to update your tool to handle a version of Ubuntu _that it already knows about_ and which was released a month ago.

**Comment by KlfJoat** [comment]
@philclifford

This is not invalid. People running the most popular Linux distribution cannot install your software as per its own documentation. That's a quite valid issue.

This is also not completed for the same reasons.
