### ISSUE TITLE
Please add Freetube 

### ISSUE THREAD

**Issue by shom13** [wimpysworld/deb-get#108]
Freetube is a private youtube client.
Its deb-file is always available at https://freetubeapp.io/#download.
Thank you

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any daily/nightly, beta or pre-release software. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
