### ISSUE TITLE
deb-get unable to find du-dust and fastfetch

### ISSUE THREAD

**Issue by SyedWafiHasan** [wimpysworld/deb-get#1109]
## Reporting a bug 🐛
deb-get is unable to find du-dust and fastfetch

```bash
root@victus:~# deb-get version
0.4.0

root@victus:~# deb-get install fastfetch
  [!] ERROR! fastfetch is not a supported application.
deb-get
root@victus:~# deb-get install du-dust
  [!] ERROR! du-dust is not a supported application.
deb-get

```

### Expected behavior

The applications are installed via deb-get

### Actual behavior

deb-get throws the error "<name> is not a supported application"

### Steps to reproduce

1. Check deb-get updates via ```deb-get update```
2. Try to install fastfetch or du-dust via ```deb-get install fastfetch``` or ```deb-get install du-dust```

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
root@victus:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### deb-get version

```bash
root@victus:~# deb-get version
0.4.0
```

### deb-get update

```bash
root@victus:~# deb-get update
  [+] Updating /etc/deb-get/01-main
  [+] Updating /etc/deb-get/91-fixes
   -=O=-  #      #        #        #                                                                                                                        
  [+] Updating cache of supported apps in the background
  [*] WARNING! Cached file /var/cache/deb-get/deb-get.json is empty or missing.
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm-backports InRelease
Hit:3 https://packages.microsoft.com/repos/code stable InRelease
Hit:4 http://mirror.djvg.sg/debian bookworm InRelease
Hit:5 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:6 http://mirror.djvg.sg/debian bookworm-updates InRelease
Hit:7 http://mirror.sg.gs/debian bookworm InRelease
Hit:8 http://mirror.sg.gs/debian bookworm-updates InRelease
Hit:9 http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any InRelease
Hit:10 http://download.virtualbox.org/virtualbox/debian bookworm InRelease
Hit:11 http://ftp.ch.debian.org/debian bookworm InRelease
Hit:12 http://ftp.ch.debian.org/debian bookworm-updates InRelease
Hit:13 http://ftp.au.debian.org/debian bookworm InRelease
Hit:14 http://ftp.au.debian.org/debian bookworm-updates InRelease
Reading package lists...
  [+] Updating /var/cache/deb-get/deb-get.json

```

**Comment by philclifford** [comment]
I cannot replicate this on Debian 12: fresh install of current release per Readme (not even the latest head with all the fixes, although that reinstalled them fine as well) on a fresh VM and all is as expected.

Wait - I think I  see your problem!

```
root@victus:~# deb-get install fastfetch
```

DO NOT EVER run deb-get as root or with sudo!

You need to set up a github PAT in a normal user's environment and run deb-get as a normal user.  It will seek elevated privileges when needed. Running with sudo or as root has been known to break things badly plus root/sudo will not generally have the needed ENV for github. You might want to copy /etc/deb-get/installed and /etc/deb-get/aptrepos somewhere if they are OK and clean out the cache (`deb-get clean` but also check there are no background jobs and remove any remaining files in `/var/cache/deb-get/`)

I'm closing this issue but feel free to continue discussing here if you continue having problems and I'll try and help.

**Comment by SyedWafiHasan** [comment]
Hi @philclifford 
Thank you for educating me on this. I was under the impression that like any other package manager, this too should be run as root. 

Following your instructions, I deleted the cache as well as ran ```deb-get clean``` followed by an update and upgrade to bring it to version 0.4.1-1

However, I still am unable to install fastfetch. Below is the output : 

```bash
swh@victus:~$ deb-get install fastfetch
  [!] ERROR! fastfetch is not a supported application.
deb-get
```
