### ISSUE TITLE
update stops whenever it encounters an error with some packages

### ISSUE THREAD

**Issue by techmagus** [wimpysworld/deb-get#1110]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

If there's an error, `update` should continue regardless.

### Actual behavior

If `update` encounters an error, it terminates.

### Steps to reproduce

1. Clean installation
2. `sudo deb-get update`

Once it encounter the following packages, it stops updating the cache.
* atuin
* glam

## Workaround

1. edit `01-main.repo`
2. Comment out `atuin` and `glam`
3. `sudo chmod -w 01-main.repo` (so `update` will read the current version before it overwrites it)
4. `sudo deb-get update`
5. At this point, the terminal will stop (the progress bar) however, the `/var/cache/deb-get/` folder is getting filled (there's the `.lock` file while it's working in the background).
6. After the entire operation is completed, the `01-main.repo` file is overwritten by `update` despite the lack of write permission and while maintaining the current permission of the file. Thus, we have to repeat from Step 1 on the next `deb-get update`. 

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

#### /etc/lsb-release

Disabled in Pop!_OS.

#### deb-get version

0.4.0

### deb-get update

```bash
  [+] Updating /etc/deb-get/01-main
########################################################################################################################################################################################################################## 100.0%
  [+] Updating cache of supported apps in the background
```

**Comment by philclifford** [comment]
This is already fixed in main for some time - so will be in the next release.
