### ISSUE TITLE
Elementary is not supported

### ISSUE THREAD

**Issue by Sush-ruta** [wimpysworld/deb-get#1120]
## Reporting a bug 🐛

I used `deb-get` in my Ubuntu distro, but since shifting to [Elementary OS](https://elementary.io/), after installing `deb-get`, I get the following message:
```
  [*] WARNING! Elementary is not supported.
```

### Expected behavior

Since Elementary is based on Ubuntu, `deb-get` should run just fine.

### Actual behavior

`  [*] WARNING! Elementary is not supported.`

#### /etc/os-release

```bash
cat /etc/os-release
PRETTY_NAME="elementary OS 7.1 Horus"
NAME="elementary OS"
CPE_NAME="cpe:/o:elementary:elementary_os:7.1"
VERSION_ID="7.1"
VERSION="7.1 Horus"
VERSION_CODENAME=horus
ID=elementary
ID_LIKE="ubuntu debian"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://docs.elementary.io/contributor-guide/feedback/reporting-issues"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
UBUNTU_CODENAME=jammy
UBUNTU_PRETTY_NAME="Ubuntu 22.04.3 LTS"
UBUNTU_NAME="Ubuntu"
UBUNTU_VERSION_ID="22.04"
UBUNTU_VERSION="22.04.3 LTS (Jammy Jellyfish)"
UBUNTU_VERSION_CODENAME=jammy

```

#### /etc/lsb-release

```bash
cat /etc/lsb-release
DISTRIB_ID=elementary
DISTRIB_RELEASE=7.1
DISTRIB_CODENAME=horus
DISTRIB_DESCRIPTION="elementary OS 7.1 Horus"
```

#### deb-get version

```bash
deb-get version
  [*] WARNING! Elementary is not supported.
0.4.1
```

P.S.: Sorry if I have made any errors in reporting the issue here. And thank you for the work you do in developing `deb-get` even if I can't use it atm. :))

**Comment by philclifford** [comment]
Thanks for providing the necessary information.  Hopefully this one-line [patch](https://github.com/wimpysworld/deb-get/pull/1134.patch) is all that is needed to support elementary OS.  It would be helpful @Sush-ruta if you could test and confirm or report back either way.

**Comment by Sush-ruta** [comment]
@philclifford Thank you for the patch. It works now. :+1:
