### ISSUE TITLE
Request: neovim

### ISSUE THREAD

**Issue by sanyer** [wimpysworld/deb-get#1122]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: neovim
 - Download URL: https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu
 - Website URL: https://neovim.io/
 - App Summary: Hyperextensible Vim-based text editor

**Comment by philclifford** [comment]
The `neovim` PPA is not maintained by the neovim team so does not meet the acceptance criteria.

**Comment by sanyer** [comment]
> The `neovim` PPA is not maintained by the neovim team so does not meet the acceptance criteria.

yeah, seems like you're right, that's a shame
