### ISSUE TITLE
get_filename_from_url: command not found & micro installed every time from deb-get

### ISSUE THREAD

**Issue by dacorsa** [wimpysworld/deb-get#1125]
# deb-get issue template

Thank you for taking the time to report an issue to the `deb-get` project 🙂

 - Please complete one the appropriate sections below.
 - Delete all the sections that do not apply, including this one.
 - Any issues that do not use this template will be closed.
 - If you're not sure what to do, or have a general question about `deb-get`, then ask in [Wimpy's World Discord](https://wimpysworld.io/discord).

## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date: yes updated, 0.4.1 latest code from github

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

Describe the expected behavior here. 
No errors and no reinstall micro every times

### Actual behavior
'
`/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] antimicrox-3.4.0-ubuntu-20.04-x86_64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] appimagelauncher_2.2.0-gha111.d9d4c73%2Bbionic_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] Blockbench_4.10.4.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] bottom-musl_0.9.6_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] crossover_24.0.2-1.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] deb-get_0.4.1-1_all.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] Ferdium-linux-6.7.5-amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] franz_5.10.0_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] gh_2.52.0_linux_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] google-chat-electron_2.20.0_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] lsd_1.1.2_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] lutris_0.5.17_all.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
dpkg: attenzione: sintassi della versione "nightly" errata: il numero di versione non inizia con una cifra
--2024-07-08 10:03:54--  https://github.com/zyedidia/micro/releases/download/nightly/micro-2.0.14-dev.181-amd64.deb
Risoluzione di github.com (github.com)... 140.82.121.3
Connessione a github.com (github.com)|140.82.121.3|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 302 Found
Posizione: https://objects.githubusercontent.com/github-production-release-asset-2e65be/53632140/40775a3c-2f8f-45bf-840c-362942a1c09d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240708%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240708T080223Z&X-Amz-Expires=300&X-Amz-Signature=91cc2261c4d9b4940b9b958f2d27087d1a816acb7fb33a6a8f81599ee2de550f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=53632140&response-content-disposition=attachment%3B%20filename%3Dmicro-2.0.14-dev.181-amd64.deb&response-content-type=application%2Foctet-stream [segue]
--2024-07-08 10:03:54--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/53632140/40775a3c-2f8f-45bf-840c-362942a1c09d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240708%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240708T080223Z&X-Amz-Expires=300&X-Amz-Signature=91cc2261c4d9b4940b9b958f2d27087d1a816acb7fb33a6a8f81599ee2de550f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=53632140&response-content-disposition=attachment%3B%20filename%3Dmicro-2.0.14-dev.181-amd64.deb&response-content-type=application%2Foctet-stream
Risoluzione di objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connessione a objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 4823062 (4,6M) [application/octet-stream]
Salvataggio in: «/var/cache/deb-get/micro-2.0.14-dev.181-amd64.deb»

/var/cache/deb-get/micro-2.0.14-dev.181-amd64 100%[=================================================================================================>]   4,60M  23,9MB/s    in 0,2s    

2024-07-08 10:03:55 (23,9 MB/s) - «/var/cache/deb-get/micro-2.0.14-dev.181-amd64.deb» salvato [4823062/4823062]

/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] ocenaudio_debian9_64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] p3x-onenote_2024.10.110_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] pandoc-3.2.1-1-amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] pdfsam_5.2.3-1_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] rclone-v1.67.0-linux-amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] Simplenote-linux-2.21.0-amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] system-monitoring-center_2.26.0_all.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] teams-for-linux_1.7.5_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] tixati_3.25-1_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] youtube-music_3.3.12_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] zenith_0.14.1-1_amd64.deb is up to date.
/usr/bin/deb-get: line 320: get_filename_from_url: command not found
  [+] zoom_amd64.deb is up to date.
`'
### Steps to reproduce

execute deb-get upgrade

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

#### /etc/lsb-release

```bash
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
```

#### deb-get version

```bash
deb-get version
0.4.1
```

### deb-get update

```bash
deb-get update
yes updated
```

**Comment by philclifford** [comment]
The `get_filename_from_url` bug was fixed by #1124 so if you run the latest release or the head of main you should not experience this after a `deb-get update`

There is another problem with `micro` though.  I'll close this one and open a separate one for that part.

**Comment by dacorsa** [comment]
ok thanks :)

**Comment by philclifford** [comment]
Thank you for the report!
