### ISSUE TITLE
bug: micro nightly releases causing continual attempts to update

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#1126]
micro is now releasing updates tagged nightly so if installed we attempt to compare that string with the installed version and upset dpkg and download the version we already have every upgrade.

Originally reported by @dacorsa in #1125

**Comment by philclifford** [comment]
@dacorsa You'll have the nightly dev installed now.  If you wish to get back to latest actual release you'll need to `deb-get reinstall micro` once either the fix is merged and you get it in a update or you copy the fix into an override in `/etc/deb-get/99-local.d/` If you choose to keep the nightly dev version you have you'll instead need to tweak the current definition as an override and get the VERSION_PUBLISHED with something like 

```
VERSION_PUBLISHED="$(echo $URL | cut -d/ -f9 |cut -d- -f2-3 )
```
and then watch out for the next actual release.

**Comment by dacorsa** [comment]
Hi @philclifford thanks,

but i don't have this path:
17:40:16 root@NanoKDE /etc/deb-get # cd /etc/deb-get/99-local.d/
-bash: cd: /etc/deb-get/99-local.d/: File o directory non esistente
17:41:00 root@NanoKDE /etc/deb-get # 

i can create? and inside i have to create a file? micro.txt?

thanks

**Comment by philclifford** [comment]
Yes - except the filename should be just the same exact name as the app (no .txt). For an override something like `cd /etc/deb-get; cp 01-main.d/$APP 99-local.d/`  See the [README](https://github.com/wimpysworld/deb-get/blob/main/README.md#custom-user-includes) for a. You might want to chown the `/etc/deb-get/99-local.d/` to yourself for convenience. `deb-get show micro` will show you where it gets the definition from.

**Comment by dacorsa** [comment]
i have done but starts all the app from deb-get ...very strange

**Comment by dacorsa** [comment]
20:30:08 root@NanoKDE /etc/deb-get # deb-get show micro
  [+] Including local package micro
  [!] Please consider contributing back new entries, an issue (or raise a PR) directly at https://github.com/wimpysworld/deb-get/pulls
  [!] ERROR! Missing required information of package micro:
DEFVER=
PRETTY_NAME=
SUMMARY=
WEBSITE=

**Comment by dacorsa** [comment]
20:30:38 root@NanoKDE /etc/deb-get/99-local.d # ll
drwxr-xr-x 2 root root 4096 lug  8 20:29 ./
drwxr-xr-x 3 root root 4096 lug  8 20:30 ../
totale 12
-rw-r--r-- 1 root root   68 lug  8 20:29 micro
20:30:39 root@NanoKDE /etc/deb-get/99-local.d #

**Comment by dacorsa** [comment]
20:30:39 root@NanoKDE /etc/deb-get/99-local.d # cat micro 
VERSION_PUBLISHED="$(echo $URL | cut -d/ -f9 |cut -d- -f2-3 )
20:30:58 root@NanoKDE /etc/deb-get/99-local.d #

**Comment by philclifford** [comment]
You need a '"'  at the end of the VERSION_PUBLISHED line (sorry, I missed it!) The `/etc/deb-get/99-local.d/micro` you need for the dev version would be
```
DEFVER=1
get_github_releases "zyedidia/micro" 
if [ "${ACTION}" != "prettylist" ]; then
    URL=$(grep "browser_download_url.*${HOST_ARCH}\.deb\"" "${CACHE_FILE}" | grep -v nightly |head -n1 | cut -d'"' -f4)
    #VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f8 | tr -d v)"
    VERSION_PUBLISHED="$(echo $URL | cut -d/ -f9 |cut -d- -f2-3 )"
fi
PRETTY_NAME="micro"
WEBSITE="https://micro-editor.github.io/"
SUMMARY="A modern and intuitive terminal-based text editor."
```

Note that besides the tweaked VERSION the "latest" tag has been removed so you get all the releases from the API.

Once the next release is released you'd probably need to remove the file from `/etc/deb-get/99-local.d` , do a `deb-get update` and if the released version appears "lower" than the nightly you'd need to `deb-get reinstall micro`

**Comment by dacorsa** [comment]
ok thanks works perfectly:

21:29:37 root@NanoKDE /etc/deb-get/99-local.d # sudo apt dist-upgrade && sudo flatpak update && sudo snap refresh && sudo deb-get upgrade
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
Calcolo dell'aggiornamento... Fatto
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
Looking for updates…

Nothing to do.
Tutte le snap aggiornate.
Lettura elenco dei pacchetti...
Generazione albero delle dipendenze...
Lettura informazioni sullo stato...
Calcolo dell'aggiornamento...
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
  [+] antimicrox-3.4.0-ubuntu-20.04-x86_64.deb is up to date.
  [+] appimagelauncher_2.2.0-gha111.d9d4c73%2Bbionic_amd64.deb is up to date.
  [+] Blockbench_4.10.4.deb is up to date.
  [+] bottom-musl_0.9.6_amd64.deb is up to date.
  [+] crossover_24.0.2-1.deb is up to date.
  [+] deb-get_0.4.1-1_all.deb is up to date.
  [+] Ferdium-linux-6.7.5-amd64.deb is up to date.
  [+] franz_5.10.0_amd64.deb is up to date.
  [+] gh_2.52.0_linux_amd64.deb is up to date.
  [+] google-chat-electron_2.20.0_amd64.deb is up to date.
  [+] lsd_1.1.2_amd64.deb is up to date.
  [+] lutris_0.5.17_all.deb is up to date.
  [+] micro-2.0.13-amd64.deb is up to date.
  [+] ocenaudio_debian9_64.deb is up to date.
  [+] p3x-onenote_2024.10.110_amd64.deb is up to date.
  [+] pandoc-3.2.1-1-amd64.deb is up to date.
  [+] pdfsam_5.2.3-1_amd64.deb is up to date.
  [+] rclone-v1.67.0-linux-amd64.deb is up to date.
  [+] Simplenote-linux-2.21.0-amd64.deb is up to date.
  [+] system-monitoring-center_2.26.0_all.deb is up to date.
  [+] teams-for-linux_1.7.5_amd64.deb is up to date.
  [+] tixati_3.25-1_amd64.deb is up to date.
  [+] youtube-music_3.3.12_amd64.deb is up to date.
  [+] zenith_0.14.1-1_amd64.deb is up to date.
  [+] zoom_amd64.deb is up to date.
21:35:43 root@NanoKDE /etc/deb-get/99-local.d #
