### ISSUE TITLE
Add Google-Chat-Linux

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#115]
an unofficial Google Chat Client
They have a deb available from their website.
https://github.com/squalou/google-chat-linux/releases/download/5.15.17-1/google-chat-linux_5.15.17-1_amd64.deb

**Comment by flexiondotorg** [comment]
Duplicate of #114. Only one Google Chat client is required in `deb-get` and Google-Chat-Eletron appears to be better maintained.
