### ISSUE TITLE
Prevent installation of `sources.list.d` files

### ISSUE THREAD

**Issue by felipecrs** [wimpysworld/deb-get#116]
For example, `sudo deb-get install code` will also create the `/etc/apt/sources.list.d/vscode.list`. This means that `code` would be upgradable through `apt` instead of only `deb-get`.

Isn't that a problem? If not, I think this deserves a note in the README.

**Comment by Forage** [comment]
I'd say it's a nice feature because it reduces the need to manually run deb-get again to get updates.
Having a parameter to prevent this behaviour could be useful in some cases though.

**Comment by flexiondotorg** [comment]
This is by design. When available `deb-get` add the official apt repositories so that packages update with regular system upgrades.
