### ISSUE TITLE
deb-get install publii fails with not-found error (seems to be using now-nonexistent url)

### ISSUE THREAD

**Issue by davidmhodges-net** [wimpysworld/deb-get#1181]
### Expected behavior

Install publii so future updates can be handled through deb-get.

### Actual behavior

Fails due to incorrect url https://cdn.getpublii.com/Publii-0.46.1.deb. (Entering same address in browser also yields 404 Not Found error.)

Terminal output:

$ deb-get install publii 
--2024-10-05 16:20:59--  https://cdn.getpublii.com/Publii-0.46.1.deb
Resolving cdn.getpublii.com (cdn.getpublii.com)... 66.42.48.254
Connecting to cdn.getpublii.com (cdn.getpublii.com)|66.42.48.254|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-05 16:21:02 ERROR 404: Not Found.

### Steps to reproduce

Type deb-get install publii in the Terminal.
--2024-10-05 16:20:59--  https://cdn.getpublii.com/Publii-0.46.1.deb
Resolving cdn.getpublii.com (cdn.getpublii.com)... 66.42.48.254
Connecting to cdn.getpublii.com (cdn.getpublii.com)|66.42.48.254|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-05 16:21:02 ERROR 404: Not Found.
[!] ERROR! Failed to download https://cdn.getpublii.com/Publii-0.46.1.deb. Deleting /var/cache/deb-get/Publii-0.46.1.deb...

#### /etc/os-release

PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

#### /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"

#### deb-get version

0.4.3
### deb-get update

  [+] Updating /etc/deb-get/01-main
   -=O=-       #    #     #      #                                                        
51991
52017
59314
59339
62446
62477
66365
66557
  [*] WARNING! Lock file found, but job is not running. Deleting /var/cache/deb-get/updating_supported.lock, cache update continues.
  [+] Updating cache of supported apps in the background
Hit:1 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease
Hit:2 https://brave-browser-apt-release.s3.brave.com stable InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 https://repo.waydro.id jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-stable/ubuntu jammy InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://download.sublimetext.com apt/stable/ InRelease
Hit:10 https://deb.torproject.org/torproject.org jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/openshot.developers/libopenshot-daily/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/tomtomtom/k9copy/ubuntu jammy InRelease
mv: cannot stat '/var/cache/deb-get/supported.list.tmp': No such file or directory
Hit:13 https://ppa.launchpadcontent.net/ubuntuhandbook1/apps/ubuntu jammy InRelease
Hit:14 https://ppa.launchpadcontent.net/ubuntuhandbook1/avidemux/ubuntu jammy InRelease
Reading package lists...
$ mv: cannot stat '/var/cache/deb-get/supported.list.tmp': No such file or directory
[pauses at this point without prompt; hitting return brings back prompt]

#### Note on preceding
I note that deb-get includes hits above for every deb app I've added to my software sources, not just ones installed with deb-get. (Publii was first attempted deb-get install. I already have it installed from .deb but thought it would be nice to not have to upgrade with manual reinstalls every time.)

#### additional note: access token

Possibly relevant: for the access token, I used a classic token with public_repo scope since deb-get is a public repository.

**Comment by davidmhodges-net** [comment]
👍

**Comment by umasse** [comment]
It seems this issue is "back" in some way. The main link has changed, the CDN link now works, but the end result is that Publii updates are currently failing for me.
