### ISSUE TITLE
Request: cbk-next

### ISSUE THREAD

**Issue by sbstn87** [wimpysworld/deb-get#1184]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name:  cbk-next
 - Download URL: https://launchpad.net/~tatokis/+archive/ubuntu/ckb-next/+packages
 - Website URL: https://github.com/ckb-next/ckb-next
 - App Summary: ckb-next is an open-source driver for Corsair keyboards and mice. It aims to bring the features of Corsair's proprietary CUE software to Linux operating systems. Major features:

    Control multiple devices independently
    United States and European keyboard layouts
    Customizable key bindings
    Per-key lighting and animation
    Reactive lighting
    Multiple profiles/modes with hardware save function
    Adjustable mouse DPI with ability to change DPI on button press

**Comment by philclifford** [comment]
The latest release is included in Ubuntu Universe: https://launchpad.net/ubuntu/+source/ckb-next/0.6.0+dfsg-0.2build2
