### ISSUE TITLE
[idea] use only a local apt repository

### ISSUE THREAD

**Issue by pirate486743186** [wimpysworld/deb-get#1188]
there's the package `local-apt-repository` . You put debs in `/srv/local-apt-repository` and that acts like a local deb repo.

I'm proposing that deb-get only manages files in it's own local repo and leaves the user to manage apt.

**Comment by philclifford** [comment]
That is not aligned with the intentions of `deb-get`.  
Others have proposed an enhancement to enable `deb-get update/upgrade` to be restricted to `deb-get`-managed repos and PPAs or continue, as now, to have `deb-get` act across all enabled apt repos and PPAs in the one pass.
