### ISSUE TITLE
Requesting a new app: Viber

### ISSUE THREAD

**Issue by chrodos** [wimpysworld/deb-get#1194]
If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [ ] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: viber
 - Download URL: https://www.viber.com/en/download/
 - Website URL: https://www.viber.com/en/
 - App Summary: Viber, is a cross-platform voice over IP (VoIP) and instant messaging (IM) software application, provided as freeware.

**Comment by philclifford** [comment]
previously declined in #57 
Still nothing on their website provides a version clue
Please do check open and closed issues when requesting a new app
