### ISSUE TITLE
[Package Request] GNU IceCat

### ISSUE THREAD

**Issue by contrarybaton60** [wimpysworld/deb-get#1200]
- [✔ ] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: GNU IceCat
 - Download URL: https://icecatbrowser.org/download.html
 - Website URL: https://www.gnu.org/software/gnuzilla/, https://icecatbrowser.org/index.html
 - App Summary: the GNU version of the Firefox web browser

**Comment by philclifford** [comment]
Thanks but I feel this source does not conform to the [acceptability criteria](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md#what-is-acceptable) as it is unofficial and not endorsed from upstream.

A working definition is easy enough to add to your local override or an external repo **at your own risk**.  Here's one I tested earlier but decided not to add to my own 3rd-party external repo.

https://github.com/philclifford/deb-get/blob/3858d8eaa96e915e95865d40e1bc363b53171889/82-3rdparty/packages/icecat
