### ISSUE TITLE
Please RELEASE support for Ubuntu Oracular 24.10

### ISSUE THREAD

**Issue by KlfJoat** [wimpysworld/deb-get#1212]
## Reporting a bug 🐛

Issue #1185 says that PR #1189 adds support for Oracular 24.10. But I still get an error that it is not supported.

It appears that #1189 was committed on 10-15 and actually approved only 2 days later. Nice speed.

But the [latest release DEB was built on 09-30](https://github.com/wimpysworld/deb-get/releases).

IMO #1185 is not actually complete until it's available to users (unless you have it connected to a Milestone).

So when will we have support for Ubuntu 24.10? I can't update DEBs for any software managed by deb-get.

### Expected behavior

deb-get supports the latest released version of Ubuntu, as it has done for the last year or two.

### Actual behavior

A month after release (10-10 to 11-20), deb-get does not yet support the latest released version of Ubuntu, Oracular (24.10).

### Steps to reproduce

1. Have deb-get installed for the last year or two.
2. Upgrade host to the latest Ubuntu release during that time.
3. Upgrade host to Ubuntu Oracular 24.10.
4. Run any deb-get command.

```bash
$ deb-get --help
  [!] ERROR! Ubuntu Oracular is not supported because it is not derived from a supported Debian or Ubuntu release.
1 $
```

### System information

Run the following a paste the output below:

#### /etc/os-release

```plain
PRETTY_NAME="Ubuntu 24.10"
NAME="Ubuntu"
VERSION_ID="24.10"
VERSION="24.10 (Oracular Oriole)"
VERSION_CODENAME=oracular
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=oracular
LOGO=ubuntu-logo
```

#### /etc/lsb-release

```plain
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.10
DISTRIB_CODENAME=oracular
DISTRIB_DESCRIPTION="Ubuntu 24.10"
```

#### deb-get version

```plain
$ deb-get version
  [!] ERROR! Ubuntu Oracular is not supported because it is not derived from a supported Debian or Ubuntu release.
1 $
```

### deb-get update

```plain
$ deb-get update
  [!] ERROR! Ubuntu Oracular is not supported because it is not derived from a supported Debian or Ubuntu release.
1 $
```

**Comment by tapyu** [comment]
> IMO https://github.com/wimpysworld/deb-get/issues/1185 is not actually complete until it's available to users

Agreed. While a newer release of `deb-get` is not available, 24.10 Ubuntu users cannot use it :(

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/deb-get/releases/tag/0.4.4

**Comment by KlfJoat** [comment]
> Fixed via https://github.com/wimpysworld/deb-get/releases/tag/0.4.4

I'm afraid it has not been fixed.

```shell
$ deb-get update
  [!] ERROR! Ubuntu Oracular is not supported because it is not derived from a supported Debian or Ubuntu release.
1 $ deb-get upgrade
  [!] ERROR! Ubuntu Oracular is not supported because it is not derived from a supported Debian or Ubuntu release.
1 $ deb-get --help
  [!] ERROR! Ubuntu Oracular is not supported because it is not derived from a supported Debian or Ubuntu release.
1 $
```

You may have finally released the update in a .deb hosted on GitHub. But my local deb-get does not update.
