### ISSUE TITLE
CI test for new/changed github-sourced packages fail 

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#1227]
Mandatory CI tests on PRs for github-sourced apps seem to no longer be getting authenticated via token so all fail :-(  

affects #1197 #1218 #1220 #1222 

I think this was working for some time and recently started failing without the test yml having changed. Various attempts to change how/when the token is passed/presented (using 'export in the script', using 'env' to set the environment) have not worked. 

Presumably github have changed something so the supplied CI token cannot be exported/used in a call out to an http GET header.

_Originally posted by @philclifford in https://github.com/wimpysworld/deb-get/issues/1222#issuecomment-2524691102_

**Comment by philclifford** [comment]
I think we may need to add a repository secret for an API token for our CI tests to use to make authenticated API calls.

**Comment by silentJET85** [comment]
I'm not 100% sure if it's the same issue, but I've been seeing similar errors when I do a `deb-get update` or try to install one of the github releases. I found that there's a write permission issue when it tries to save the cache file. 
It looks like it may have started with commit 76a3018.

**Comment by philclifford** [comment]
I think you've nailed it! Cherry-picking your fix seems to fix the CI failures.
Thanks!
