### ISSUE TITLE
Add Anki

### ISSUE THREAD

**Issue by siriak** [wimpysworld/deb-get#124]
Anki is a free and open-source flashcard program using spaced repetition, available at https://apps.ankiweb.net/ and https://github.com/ankitects/anki

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is published as a `.deb`. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
