### ISSUE TITLE
Add Hyperspace

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#129]
unofficial mastodon client
They have a deb available from their website.
https://github.com/hyperspacedev/hyperspace/releases/download/v1.1.4/hyperspace_1.1.4_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
