### ISSUE TITLE
Separate Beta Channel like Flathub-Beta Branch

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#131]
Hi
I know there is new rule that this deb-get only allowed stable branch apps today. But, I think it will be better if there is a separate beta channel like Flathub-Beta. Is it possible?

**Comment by flexiondotorg** [comment]
Install beta or pre-release software is out of scope for `deb-get`. This potentially introduces issues with namespace releases using different configuration paths or sharing paths that make rolling back difficult for users who encounter issues with pre-release software.
