### ISSUE TITLE
Add OnlyOffice

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#133]
an open source Office suite
Homepage: https://www.onlyoffice.com/download-desktop.aspx
They have a deb available from their website.
https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v7.0.2/onlyoffice-desktopeditors_amd64.deb

**Comment by flexiondotorg** [comment]
Already added via https://github.com/wimpysworld/deb-get/commit/6a5a2bfda37ef91779e263a72d271598ac149774
