### ISSUE TITLE
Add Copyq

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#152]
famous FOSS clipboard manager
Homepage: https://hluk.github.io/CopyQ/
They have a deb available from their website.
https://github.com/hluk/CopyQ/releases/download/v6.1.0/copyq_6.1.0_Debian_11-1_amd64.deb

**Comment by flexiondotorg** [comment]
Has a PPA for Ubuntu:

- https://launchpad.net/~hluk/+archive/ubuntu/copyq
