### ISSUE TITLE
Add Flameshot

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#154]
Powerful Screenshot App
https://github.com/flameshot-org/flameshot
They have a deb available from their website.
https://github.com/flameshot-org/flameshot/releases/tag/v0.10.2

**Comment by Fuseteam** [comment]
a nice trick: on github you can always get to the latest tag  by replace: `/tag/vx.y` with `/latest`
for example the latest release of flameshot is at https://github.com/flameshot-org/flameshot/releases/latest

**Comment by kingeejit** [comment]
Taking a look
