### ISSUE TITLE
Add WebTorrent Desktop

### ISSUE THREAD

**Issue by Paddy-NI** [wimpysworld/deb-get#159]
Stream any user provided torrent file or magnet link sequentially (Audio, Video)

https://github.com/webtorrent/webtorrent-desktop

Deb Available here

https://github.com/webtorrent/webtorrent-desktop/releases

**Comment by philclifford** [comment]
There seem to be upstream issues of viability and direction that preclude including this at this time.

https://github.com/webtorrent/webtorrent/issues/2609
https://github.com/webtorrent/webtorrent/issues/2498
https://github.com/webtorrent/webtorrent-desktop/issues/2309
