### ISSUE TITLE
deb-get upgrade persistently updates sengi

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#166]
Hi
I tried to update the apps with sudo deb-get upgrade. But, after I reboot. it still trying to download the one of the software same version again. Is it a bug?

![image](https://user-images.githubusercontent.com/29157187/168414375-d9602703-79df-4b91-ac01-36cd5602607f.png)

**Comment by philclifford** [comment]
There's a manual workaround in #803
