### ISSUE TITLE
Add Picocrypt

### ISSUE THREAD

**Issue by HACKERALERT** [wimpysworld/deb-get#167]
Hi, I'm the dev of a popular encryption tool called Picocrypt.
https://github.com/HACKERALERT/Picocrypt
Debs are available in the Releases:
https://github.com/HACKERALERT/Picocrypt/releases

**Comment by zadkiel0** [comment]
![image](https://user-images.githubusercontent.com/94993487/219932775-edac7585-bfd6-4dfc-a93b-8ac64e84443a.png)

i found these vulnerablitties when i scanned the file with virus total , what does this mean it even has trojan in it
