### ISSUE TITLE
user includes capability?

### ISSUE THREAD

**Issue by dreamcat4** [wimpysworld/deb-get#169]
Hi,
It simply occurred to me that user includes feature would be really convenient here. So that all individual users each don't have to keep re-merging upstream / master into their own git forks (and keep re merging always until their own individual request eventually gets accepted / merged). This would be a lot less painful. Lower friction...

For example if at the end of (at the very bottom of the script). Then look for and find any files found to exist in `/etc/deb-get.d/*`, then include them (in alphabetical loading order `10-file-A`, `20-file-B`, `30-file-C`, etc. And just... `. $file` to include it.

And since as a subfolder under `/etc/`, it is only writable by `root` user. The security should be good. Its same level of elevated permissions users need already in order to run `deb-get` in the first place. In order to even write a new file to there.

Many thanks for considering this request.

**Comment by flexiondotorg** [comment]
CLosed via #247
