### ISSUE TITLE
please carefully sync apps list with applications.json from ubuntu-mate-welcome-legacy

### ISSUE THREAD

**Issue by N0rbert** [wimpysworld/deb-get#18]
We already have a big list of deb-packages in Ubuntu MATE Welcome Software Boutique. 
I would recommend to carefully sync apps from https://github.com/ubuntu-mate/ubuntu-mate-welcome-legacy/blob/master/data/js/applications.json with deb-get applications database. You can even create a parser for this file.

My drafts are below:

```bash
#!/bin/sh

echo "URLs"

wget --quiet https://raw.githubusercontent.com/ubuntu-mate/ubuntu-mate-welcome-legacy/master/data/js/applications.json -O - | grep "deb\ .*" --only-matching | sed "s/\"//" | sed "s/\[arch=amd64\] //" | sed "s/\[arch=amd64,armhf\] //" | sed "s/\[arch=amd64,arm64,armhf\] //" | awk '{print $2}' | sort -u | sed "s/https:\/\///" | sed "s/http:\/\///" | awk -F / '{print $1}' | sort -u

echo "----"

echo "PPAs"
wget --quiet https://raw.githubusercontent.com/ubuntu-mate/ubuntu-mate-welcome-legacy/master/data/js/applications.json -O - | grep "ppa:" | sort -u | sed 's/,//g' | sed 's/\"//g' | awk '{print $2}' | sort -u
```

**Comment by flexiondotorg** [comment]
Please raise an issue for each app that needs adding to `deb-get` so those issues can be closed discretely as each missing app is added.

`deb-get` is inspred by Software Boutique and most apps it supports are already included in `deb-get` :+1:
