### ISSUE TITLE
ARM and Mobian support

### ISSUE THREAD

**Issue by giovannicaligaris** [wimpysworld/deb-get#189]
Is it possible to add arm support for Debian/Mobian? That way it can be used on pinephone and other mobile linux devices.

**Comment by flexiondotorg** [comment]
Please paste the output of:

```bash
cat /etc/os-release
cat /etc/lsb-release
```

**Comment by giovannicaligaris** [comment]
$ cat /etc/os-release
PRETTY_NAME="Droidian bookworm"
NAME="Droidian"
ID=droidian
ID_LIKE="debian"
HOME_URL="https://droidian.org/"
BUG_REPORT_URL="https://github.com/droidian/meta/issues"

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Droidian
Description:	Droidian bookworm
Release:	testing
Codename:	bookworm

**Comment by flexiondotorg** [comment]
This is based on sid (bookworm) so not something I can reliably support. Sorry.
