### ISSUE TITLE
Is KeeShare reducing security?

### ISSUE THREAD

**Issue by Simplenuity** [wimpysworld/deb-get#193]
I would like to clarify whether/what I'm missing something here?

If my KeePassXC database is secured with a second factor and I decide to use KeeShare, am I not reducing my security for the data included in the KeeShare file due to not being able to use a second factor for the file?

Thanks!

**Comment by flexiondotorg** [comment]
Please direct this question to the appropriate project 🙂

**Comment by Simplenuity** [comment]
Sincerely sorry! No idea how I ended up here.
