### ISSUE TITLE
please add ubuntuzilla repository

### ISSUE THREAD

**Issue by N0rbert** [wimpysworld/deb-get#20]
See https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/ .

Repository adding is possible with:
```bash
echo "deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main" | sudo tee -a /etc/apt/sources.list.d/ubuntuzilla.list > /dev/null
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C
sudo apt-get update
```

This will allow one to install *firefox-mozilla-build* , *firefox-esr-mozilla-build*, *thunderbird-mozilla-build* , *seamonkey-mozilla-build* packages.

**Comment by flexiondotorg** [comment]
`apt-key` is deprecated so an alternative means of retrieving the key is required.

**Comment by flexiondotorg** [comment]
What I am about to write, I do need to clearly document in the README. But, I am not going to add software sources that are not authoritatively from the vendor or project. Unbuntuzilla is an interesting community project, but not the upstream vendor/project.

So, am I going to politely decline this request.
