### ISSUE TITLE
Some packages have an empty Download URL

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#213]
Hi
When I typed sudo deb-get upgrade I got the message [!] ERROR! Download URL is empty. Skipping. Is it a bug?

![image](https://user-images.githubusercontent.com/29157187/170807173-722aa4e3-2026-412e-b81d-bc438e3b4cbe.png)

**Comment by flexiondotorg** [comment]
@dtantono I've just pushed a change to the logging to git master. Can you run `deb-get upgrade` using git master and it will identify which packages are affected so I can investigate :+1:

**Comment by dtantono** [comment]
Hi
is this what you mean?
![image](https://user-images.githubusercontent.com/29157187/170823499-fcd0b9cd-0283-44ec-9388-90615139986d.png)

**Comment by flexiondotorg** [comment]
No :slightly_smiling_face: 

Please clone this git repo and run `./deb-get update` from the git clone, not the installed version.

**Comment by dtantono** [comment]
Hi
Yes, I found something 
![image](https://user-images.githubusercontent.com/29157187/170827991-857ae980-cffd-4517-9b7d-3c39ea79db44.png)

**Comment by flexiondotorg** [comment]
So, can this issue be closed? Looks like git master is working correctly.

**Comment by dtantono** [comment]
it looks like there are some apps that have version conflicts. that means if the conflicting apps are updating itself to the newest version. this problem will be gone automatically. Is that so?

**Comment by flexiondotorg** [comment]
Please provide post the full output (text not screenshot) of the apps which have a version mismatch.

**Comment by dtantono** [comment]
here it is 

 [*] WARNING! draw.io (16.1.2) has an update pending for: 18.1.3
  [+] Updating /var/cache/deb-get/franz.json
  [+] Updating /var/cache/deb-get/github-desktop.json
  [+] Updating /var/cache/deb-get/google-chat-electron.json
  [*] WARNING! google-chat-electron (2.15.1) has an update pending for: 2.16.1
  [+] Updating /var/cache/deb-get/igdm.json
  [+] Updating /var/cache/deb-get/ksnip.json
  [*] WARNING! ksnip (1.9.1-0build0~ubuntu20.04) has an update pending for: 1.10.0
  [+] Updating /var/cache/deb-get/p3x-onenote.json
  [+] Updating /var/cache/deb-get/rustdesk.json
  [*] WARNING! shutter-encoder (15.7) has an update pending for: 16.0
  [+] Updating /var/cache/deb-get/system-monitoring-center.json
  [*] WARNING! system-monitoring-center (0.3.2~beta1) has an update pending for: 1.17.0

**Comment by flexiondotorg** [comment]
Everything looks correct. I'll change the WARNING to INFO, since it is not a warning, just a notification that updates are available.
