### ISSUE TITLE
Add Master PDF Editor 4 (Free to Use edition)

### ISSUE THREAD

**Issue by bayazidbh** [wimpysworld/deb-get#221]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Master PDF Editor 4 ([masterpdfeditor-free](https://aur.archlinux.org/packages/masterpdfeditor-free) in AUR)
 - Download URL: http://code-industry.net/public/master-pdf-editor-4.3.89_qt5.amd64.deb
 - Website URL: https://code-industry.net/free-pdf-editor/
 - App Summary: A complete solution for creation and editing PDF files - Free version without watermark
 
 [Master PDF Editor 4](https://www.linuxuprising.com/2019/04/download-master-pdf-editor-4-for-linux.html) has less editing restrictions than Master PDF Editor 5 in #89, it is a valid alternative for users who wish to use its editing capability (editing or adding text, inserting images, etc.) instead of purchasing Master PDF Editor 5 or while keeping it a separate install on Flatpak.

**Comment by aindriu80** [comment]
Can you add Master PDF Editor version 5?

It's here:-

https://code-industry.net/free-pdf-editor/

https://code-industry.net/public/master-pdf-editor-5.8.63-qt5_included.x86_64.deb 

Version 5 is ok for non-commercial use, version 4 is old.

> The unregistered version can be used only in personal, noncommercial purposes to view documents, fill PDF forms, comment and print documents. In order to use the application for commercial purposes, and with its full functionality you are required to purchase a license.

**Comment by bayazidbh** [comment]
@aindriu80 Master PDF Editor 5 is covered in #89. I'm specifically mentioning Master PDF Editor 4, although it's old, has less restrictions than Master PDF Editor 5. Primarily with editing text, pictures, and the like- which in Master PDF Editor 5 would create a watermark in the free version.

I understand that it's old, but even AUR kept it and the download is still available to this day, so I think it's at least worth considering as an alternative to Master PDF Editor 5.

**Comment by Fuseteam** [comment]
not to be the sourpuss but it master pdf editor 4 actively maintained? i don't see it on the official website

**Comment by bayazidbh** [comment]
> not to be the sourpuss but is master pdf editor 4 actively maintained? i don't see it on the official website

It is an old version, so no. I guess you can compare it to the last version of Photoshop before it got rolled to Creative Cloud.

**Comment by Fuseteam** [comment]
Well technically that makes it out of scope according https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md

**Comment by philclifford** [comment]
I *strongly* urge you not to do this for your own security
===

But there's nothing to stop you putting it into 99-local (or your own external repo) if you choose.  Using the version 5 as a basis you just need to hard-code the URL and tweak the version (or hard-code that).  I can see nowhere to get the version (or find any updates, which is moot of course!) but the file you mentioned can currently be retrieved.  So it will probably never make it into the project, but you could put the following into `/etc/deb-get/99-local.d/master-pdf-editor-4` and have it available to you (it installed fine on kinetic alongside v5).

```
DEFVER=1
CODENAMES_SUPPORTED="bionic bullseye buster focal jammy kinetic"
#get_website "https://code-industry.net/get-master-pdf-editor-for-ubuntu/?download"
if [ "${ACTION}" != "prettylist" ]; then
        URL="http://code-industry.net/public/master-pdf-editor-4.3.89_qt5.amd64.deb"
        VERSION_PUBLISHED="$(echo "${URL}" | sed 's/^.*editor-//;s/-qt5.amd64.*$//')"
fi
PRETTY_NAME="Master PDF Editor v4"
WEBSITE="https://code-industry.net/free-pdf-editor/"
SUMMARY="Ancient unsupported version! Do not use. "

```

**Comment by philclifford** [comment]
As noted :point_up:  insecure, unmaintained and out-of-scope
