### ISSUE TITLE
Add OpenSnitch

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#222]
I have checked that this app does not already have a pending request and has not previously been declined.
App Name: OpenSnitch
Download URL: https://github.com/evilsocket/opensnitch/releases/download/v1.5.1/opensnitch_1.5.1-1_amd64.deb
Website URL: https://github.com/evilsocket/opensnitch
App Summary: OpenSnitch is a GNU/Linux application firewall.

**Comment by flexiondotorg** [comment]
OpenSnitch is not compatible with 22.04 unless manual workarounds are applied.

- https://github.com/evilsocket/opensnitch/issues/647#issuecomment-1090545284
