### ISSUE TITLE
Add Fsearch

### ISSUE THREAD

**Issue by bayazidbh** [wimpysworld/deb-get#224]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Fsearch
 - Download URL: https://launchpad.net/~christian-boxdoerfer/+archive/ubuntu/fsearch-stable
 - Website URL: https://github.com/cboxdoerfer/fsearch
 - App Summary: FSearch is a fast file search utility, inspired by Everything Search Engine.

**Comment by flexiondotorg** [comment]
Fixed via #271
