### ISSUE TITLE
Add VSCode 

### ISSUE THREAD

**Issue by aindriu80** [wimpysworld/deb-get#226]
## Requesting to add VSCode ✨

 - [ X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name:  VSCode
 - Download URL: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
 - Website URL: https://code.visualstudio.com
 - App Summary: An IDE 

## Requesting a new feature 🧑‍💻

Can you add VSCode to the list? It's currently behind by a version and I had to do it manually with the following

`wget 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' -O /tmp/code_latest_amd64.deb
sudo dpkg -i /tmp/code_latest_amd64.deb
`

**Comment by flexiondotorg** [comment]
Code and Codium are both already supported.

**Comment by aindriu80** [comment]
Well it is not working very well because I had to download VSCode 1.67 yesterday, I was stuck on 1.66 for ages and I kept getting pop ups in VSCode saying a new version is ready, VSCode wasn't listed in your files yesterday:S
