### ISSUE TITLE
Add Ubuntu Mainline Kernel Installer

### ISSUE THREAD

**Issue by RayJW** [wimpysworld/deb-get#228]
## Requesting a new app ✨

 - [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: mainline
 - Download URL: 
     - There is a PPA: https://code.launchpad.net/~cappelikan/+archive/ubuntu/ppa
     - And a deb package on the repo: https://github.com/bkw777/mainline/releases/latest
 - Website URL: https://github.com/bkw777/mainline
 - App Summary: A tool for installing the latest Linux kernels on Ubuntu-based distributions.

**Comment by flexiondotorg** [comment]
I've updated the guidelines for packages we'll include in `deb-get` to exclude anything that changes the hardware enablement (HWE) stack. You can find the guidelines here:

 - https://github.com/wimpysworld/deb-get#what-is-acceptable


Sorry, but we will not be including the mainline kernel installer.

**Comment by RayJW** [comment]
I get why this decision was made, and I think it makes sense. 
So thank you for your response and for the clarification in the rules.
