### ISSUE TITLE
Add Eversticky

### ISSUE THREAD

**Issue by dnet890** [wimpysworld/deb-get#230]
I have checked that this app does not already have a pending request and has not previously been declined.
App Name: Eversticky
Download URL: https://github.com/itsmejoeeey/eversticky/releases/download/v0.96.0/eversticky_0.96.0-1_amd64.deb
Website URL: https://github.com/itsmejoeeey/eversticky
App Summary: open source Evernote client

**Comment by Xmetalfanx** [comment]
Template message from me at this point ... issue addressed https://github.com/Xmetalfanx/deb-get/commit/16b68c8c8ad950c3b2b02d918e75eb151f8743f3 on my fork but I'd like to test it if i could, in case i messed something up ... I don't mind doing a PR if the team seems this and the code seems right.

**Comment by natanjunges** [comment]
To test it, go in the terminal to the folder where you cloned the repository and run:
```bash
./deb-get install eversticky
```
