### ISSUE TITLE
Add Vuescan

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#236]
I have checked that this app does not already have a pending request and has not previously been declined.
App Name: Vuescan
Download URL: https://www.hamrick.com/files/vuex6497.deb
Website URL: https://github.com/itsmejoeeey/eversticky
App Summary: Linux scanner utility

**Comment by LoicBrassart** [comment]
I may be wrong, but I think that's done already (just saw it in the listing)
