### ISSUE TITLE
Add gamescope

### ISSUE THREAD

**Issue by bayazidbh** [wimpysworld/deb-get#238]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: gamescope
 - Download URL: https://launchpad.net/~ar-lex/+archive/ubuntu/gamescope
 - Website URL: https://github.com/Plagman/gamescope/
 - App Summary: A low latency micro-compositor for games

**Comment by flexiondotorg** [comment]
gamescope does not publish a .deb package.
