### ISSUE TITLE
Add CoreCtrl

### ISSUE THREAD

**Issue by bayazidbh** [wimpysworld/deb-get#239]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: CoreCtrl
 - Download URL: https://launchpad.net/~ernstp/+archive/ubuntu/mesarc
 - Website URL: https://gitlab.com/corectrl/corectrl
 - App Summary: a Free and Open Source GNU/Linux application that allows you to control with ease your computer hardware using application profiles.

**Comment by natanjunges** [comment]
I'm working on it.

**Comment by flexiondotorg** [comment]
Closed via #265
