### ISSUE TITLE
Add Notable

### ISSUE THREAD

**Issue by natanjunges** [wimpysworld/deb-get#248]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Notable
 - Download URL: https://download.notable.app/?target=deb
 - Website URL: https://notable.app
 - App Summary: The Markdown-based note-taking app that doesn't suck.

**Comment by flexiondotorg** [comment]
This gets the published version:

```bash
unroll_url "https://download.notable.app/?target=deb" | sed -n -e 's/^.*\(\(notable\).*\)/\1/p' | cut -d'_' -f2
```

**Comment by natanjunges** [comment]
OK, I'm working on it.
