### ISSUE TITLE
[Feature request] port to other languages

### ISSUE THREAD

**Issue by hsbasu** [wimpysworld/deb-get#25]
Hi Martin,
I was searching for a method to add useful packages that are not available in Ubuntu/Debian repository like `Tixati` or `MS Edge`. Most of the time, to try out new apps/versions, I have to either manually download the deb package or add the apt repo manually. It is also a hassle to upgrade to new versions for apps like Tixati. So `deb-get` of yours would definitely provide an AUR-like experience to avid Ubuntu or Debian users like me.
Is there any plan to rewrite it in C or Python to make it more feature rich?
BTW, I am also requesting to add `Tixati` - A torrent client to `deb-get`.

**Comment by flexiondotorg** [comment]
No plans to rewrite it or make the feature set complex.
