### ISSUE TITLE
Add BitWig Studio

### ISSUE THREAD

**Issue by natanjunges** [wimpysworld/deb-get#253]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: BitWig Studio
 - Download URL: https://www.bitwig.com/dl/?id=481&os=installer_linux
 - Website URL: https://www.bitwig.com
 - App Summary: Modern music production and performance.

**Comment by natanjunges** [comment]
I'm working on it.

**Comment by Zahrun** [comment]
Seems this is a fixed version and is not updating though

**Comment by natanjunges** [comment]
This is true, thanks for the heads up. I'll work on a fix.
