### ISSUE TITLE
please support Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by N0rbert** [wimpysworld/deb-get#26]
Running on Ubuntu 18.04 LTS gives a unexpected (for me) error

>     $ curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
>     [!] ERROR! Ubuntu Bionic is not supported because it is not derived from a supported Ubuntu release.

I do not see any particular reason to abandon [current supported Ubuntu 18.04 LTS](https://wiki.ubuntu.com/Releases) release. Please support it in deb-get.

**Comment by flexiondotorg** [comment]
Sorry, this is out of scope for the project.

**Comment by Fuseteam** [comment]
could you elaborate why it is out of scope @flexiondotorg?

**Comment by enigma9o7** [comment]
I'm also on 18.04LTS which canonical supports for almost another year, and could really benefit from deb-get until then - there's a few apps in ubuntu repos which are getting old, etc.  Please add support!  There's no good reason not too, all the deb files themselves work even on 16.04....

Or just wait an other year and it wont matter anymore.

**Comment by N0rbert** [comment]
Dear @Fuseteam and @enigma9o7 you are welcome to use my fork https://github.com/N0rbert/deb-get , it supports 18.04 LTS.
Dear @flexiondotorg , if you have good willing - you can merge my additions to main branch to satisfy user demands.

**Comment by Fuseteam** [comment]
@N0rbert i don't need it, it's fairly simple to make the change in you old pr and force deb-get to work.
i'm more interested in the implications of doing that, if we're over looking something
