### ISSUE TITLE
Add Standard-Notes

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#301]
I have checked that this app does not already have a pending request and has not previously been declined.
App Name: Standardnotes
Download URL: https://github.com/standardnotes/app/releases/download/%40standardnotes%2Fdesktop%403.23.61/standard-notes-3.23.61-linux-amd64.deb
Website URL: https://standardnotes.com/longevity
App Summary: a reliable note-taking app

**Comment by kingeejit** [comment]
Taking a look
