### ISSUE TITLE
Add Keepsolid VPN

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#302]
I have checked that this app does not already have a pending request and has not previously been declined.
App Name: Keepsolid VPN
Download URL: https://www.vpnunlimited.com/api/keepsolid/vpn-download?platform=debian-7
Website URL: https://www.vpnunlimited.com/downloads/linux
App Summary: a cheap VPN.

**Comment by flexiondotorg** [comment]
There is no mechanism to automatically determine the published version from the vendor.
