### ISSUE TITLE
Add Ferdium

### ISSUE THREAD

**Issue by bayazidbh** [wimpysworld/deb-get#315]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Ferdium
 - Download URL: https://github.com/ferdium/ferdium-app/releases/latest
 - Website URL: https://ferdium.org/
 - App Summary: All your services in one place, built by the community (Hard-fork of [Franz](https://github.com/meetfranz/franz), adding awesome features and removing unwanted ones.)

**Comment by flexiondotorg** [comment]
Every release is a nightly/pre-release. We have guidelines for packages we'll include in `deb-get` here:

 - https://github.com/wimpysworld/deb-get#what-is-acceptable

We will only add stable releases. Sorry, closing this until Ferdium has a stable release.

**Comment by bayazidbh** [comment]
Ah, fair. Though it has a [stable release](https://github.com/ferdium/ferdium-app/releases/tag/v5.9.2), I just noticed that only the 6.0 versions has .deb releases. I'll keep an eye on it as it does [seem close to stable release](https://github.com/ferdium/ferdium-app/issues/9). Thanks for the consideration though!

**Comment by bayazidbh** [comment]
requesting re-opening @flexiondotorg as ferdium finally has a stable release: https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0

**Comment by bayazidbh** [comment]
Should I create a new issue @flexiondotorg @natanjunges ?

**Comment by natanjunges** [comment]
If you cannot reopen this one, you might as well.
