### ISSUE TITLE
Purge does not limit itself to package specified

### ISSUE THREAD

**Issue by Forage** [wimpysworld/deb-get#318]
## Reporting a bug 🐛
Earlier today I received a kernel update. As a result packages like `linux-headers-5.15.0-39`, `linux-image-5.15.0-39-generic`, etc. of the earlier version were no longer needed but I did not remove them yet.
When I tried to purge an app with `deb-get` those got removed as well. While I understand why this is happening, it is unexpected behaviour nonetheless when `deb-get` is the installer I'm passing through.

### Expected behavior

When running `deb-get purge appname` I expect only that app, and possible its no longer needed dependencies, to be removed.

### Actual behavior

All packages marked for auto-removal get removed, including those not related to the app asked to be removed.

#### /etc/os-release

```bash
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### /etc/lsb-release

```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```

#### deb-get version

```bash
0.3.0
```

**Comment by natanjunges** [comment]
It seems that it is a limitation of `apt-get` and not `deb-get` itself, so I do not think there is an easy workaround.

**Comment by flexiondotorg** [comment]
As @natanjunges points out, this is `apt-get` behaviour and not something `deb-get` can *"fix"*. Sorry.
