### ISSUE TITLE
KDE Neon does not worked on 0.3.1

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#327]
Expected behavior
The package should function normally as it did before version 0.3.1

Actual behavior
The package refuses to function due to unsupported distro.

Steps to reproduce
Running any of deb-get's commands would function as intended but after updating to 0.3.1-1 from 0.3.0-1, it returns
[!] ERROR! KDE Neon Focal is not supported because it is not derived from a supported Debian or Ubuntu release.

System information
/etc/os-release

  GNU nano 4.8                                                                                                  
NAME="KDE neon"
VERSION="5.25"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - 5.25"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

/etc/lsb-release
ISTRIB_ID=neon
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="KDE neon User - Plasma 5.25"

deb-get version
  [!] ERROR! KDE Neon  Focal is not supported because it is not derived from a supported Debian or Ubuntu release.

deb-get update
  [!] ERROR! KDE Neon Focal is not supported because it is not derived from a supported Debian or Ubuntu release.

**Comment by natanjunges** [comment]
Please follow the template for reporting bugs. We cannot help without the relevant information.

**Comment by dtantono** [comment]
@natanjunges updated

**Comment by natanjunges** [comment]
OK, looks similar to #328. A solution is being worked in #343.
