### ISSUE TITLE
0.3.1 drops support for Zorin OS

### ISSUE THREAD

**Issue by doms9** [wimpysworld/deb-get#328]
### Expected behavior

The package should function normally as it did before version 0.3.1

### Actual behavior

The package refuses to function due to unsupported distro.

### Steps to reproduce

Running any of deb-get's commands would function as intended but after updating to 0.3.1-1 from 0.3.0-1, it returns<br> `[!] ERROR! Zorin OS Focal is not supported because it is not derived from a supported Debian or Ubuntu release.`

#### /etc/os-release

```bash
NAME="Zorin OS"
VERSION="16.1"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16.1"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://help.zorin.com/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

#### /etc/lsb-release

```bash
DISTRIB_ID=Zorin
DISTRIB_RELEASE=16
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Zorin OS 16.1"
```

#### deb-get version

```bash
  [!] ERROR! Zorin OS Focal is not supported because it is not derived from a supported Debian or Ubuntu release.
```

### deb-get update

```bash
  [!] ERROR! Zorin OS Focal is not supported because it is not derived from a supported Debian or Ubuntu release.
```

**Comment by MortenPiil** [comment]
Linux Mint 20.3 is also affected, works with 0.3.0
