### ISSUE TITLE
Add muCommander

### ISSUE THREAD

**Issue by peutch** [wimpysworld/deb-get#336]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: muCommander
 - Download URL:  https://www.mucommander.com/#download
 - Website URL: https://www.mucommander.com/
 - App Summary: muCommander is an open source, dual-pane file manager available on all major operating systems

This is another Midnight Commander.

**Comment by Xmetalfanx** [comment]
I added a commit for this in my fork https://github.com/Xmetalfanx/deb-get/commit/f7e026e0cc4ccbbbe2d89357639bae28f5626bc4 and am unsure I want to do a PR for it as I'd like to test it (but am  unsure how) just in case I goofed up somewhere ... .so I am sure it's ready when I do the PR 

If this looks good (even if I can't test it locally) for a PR,  I have no issue submitting the PR

**Comment by natanjunges** [comment]
To test it, go in the terminal to the folder where you cloned the repository and run:
```bash
./deb-get install mucommander
```

**Comment by Xmetalfanx** [comment]
tested this and it works locally  ... again thanks for the info
