### ISSUE TITLE
Add Iphigénie

### ISSUE THREAD

**Issue by peutch** [wimpysworld/deb-get#338]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: iPhiGéNie J
 - Download URL: http://iphigénie.com/help_J/fr.lproj/iPhiGeNie_J.html
 - Website URL: https://www.iphigen.ie/
 - App Summary: Iphigénie, the mapping app, the best tool for hiking and outdoor activities.

For the frenchies! ;-)

**Comment by flexiondotorg** [comment]
There is no means to determine the current published version, required so `deb-get` can handle updates.
