### ISSUE TITLE
Add jOrgan

### ISSUE THREAD

**Issue by peutch** [wimpysworld/deb-get#339]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: jOrgan
 - Download URL: https://sourceforge.net/projects/jorgan/files/jorgan-package/
 - Website URL: https://jorgan.info
 - App Summary: jOrgan is a Java-based MIDI-Processor, in other terms a Java MIDI-IDE. Its open architecture allows for complex transmitting and dynamical modifying of MIDI-Messages on their way between MIDI-Encoders and MIDI-Decoders, by means of its own MIDI Programming Language MPL. A device being used to run jOrgan must also have a suitable version of Java installed.

**Comment by flexiondotorg** [comment]
This current version of jOrgan does not have a stable release. Please see https://github.com/wimpysworld/deb-get#what-is-acceptable
