### ISSUE TITLE
Updating `ksnip` using `deb-get` leads to the removal of `kde-spectacle`

### ISSUE THREAD

**Issue by Ahmed-E-86** [wimpysworld/deb-get#341]
## Reporting a bug 🐛

Updating `ksnip` using `deb-get` leads to the removal of `kde-spectacle`, which it is not the same behavior when installing `ksnip` using `apt`.

## System info
**Linux distro:** Kubuntu 22.04 + Kubuntu Backports PPA
**deb-get version:** 0.3.1

**Comment by natanjunges** [comment]
Please provide all the information requested in the template for reporting bugs.
