### ISSUE TITLE
Syntax error breaks latest head

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#344]
## Reporting a bug 🐛

current release is OK but the "one-lilne install" gets the latest from main, which is broken ...
A PR awaits ...

```
$ ./deb-get install deb-get
./deb-get: line 2457: syntax error near unexpected token `rm'
./deb-get: line 2457: `        ${ELEVATE} rm -v "${CACHE_DIR}"/*.json;;'
```

### Expected behavior
runs

### Actual behavior
does not run

### Steps to reproduce

Copy-pasta the one-line-install from the readme ...,

**Comment by justinhartman** [comment]
+1 for me too trying to install from command line:

```console
$ curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
bash: line 2457: syntax error near unexpected token `rm'
bash: line 2457: `        ${ELEVATE} rm -v "${CACHE_DIR}"/*.json;;'
```
