### ISSUE TITLE
Pop_OS! isn't supported anymore (0.3.1=

### ISSUE THREAD

**Issue by oguzkarayemis** [wimpysworld/deb-get#348]
# deb-get issue template

Thank you for taking the time to report an issue to the `deb-get` project 🙂

 - Please complete one the appropriate sections below.
 - Delete all the sections that do not apply, including this one.
 - Any issues that do not use this template will be closed.
 - If you're not sure what to do, or have a general question about `deb-get`, then ask in [Wimpy's World Discord](https://wimpysworld.io/discord).

## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [ ] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name:
 - Download URL:
 - Website URL:
 - App Summary:

## Requesting a new feature 🧑‍💻

If you are proposing a new feature for `deb-get` please describe the proposed
feature with as much detail as possible here:

## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

Updating and upgrading without any issue.

### Actual behavior

```
sudo deb-get update && sudo deb-get upgrade
  [!] ERROR! Pop!_OS Jammy is not supported because it is not derived from a supported Debian or Ubuntu release.
```

### Steps to reproduce

open a terminal and run deb-get.

### System information

Run the following a paste the output below:

#### /etc/os-release
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
#### /etc/lsb-release

```
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
```

#### deb-get version

```
[!] ERROR! Pop!_OS Jammy is not supported because it is not derived from a supported Debian or Ubuntu release.
```

### deb-get update

```
[!] ERROR! Pop!_OS Jammy is not supported because it is not derived from a supported Debian or Ubuntu release.
```

**Comment by natanjunges** [comment]
Looks similar to #328. A solution is being worked in #343.

**Comment by oguzkarayemis** [comment]
Yes, it is. Thanks for your work :).

**Comment by aindriu80** [comment]
What is the solution? I didn't get it to work - I'm running a fresh install Pop 22.04 and don't have deb-get installed yet.  I've tried downloading the deb package and also using the curl installation method but I am still getting the error

`
[!] ERROR! Pop!_OS Jammy is not supported because it is not derived from a supported Debian or Ubuntu release.
`

**Comment by natanjunges** [comment]
A solution is already being worked on. Please wait until it is approved, merged and released.

**Comment by oguzkarayemis** [comment]
The issue has come back with new update: 0.3.3-1.
