### ISSUE TITLE
the .deb file is not Debian compatible (zst compressed)

### ISSUE THREAD

**Issue by peutch** [wimpysworld/deb-get#350]
Hi,

On my Debian Sid system, here is what happens:
```
# dpkg -i deb-get_0.3.1-1_all.deb 
dpkg-deb: error: archive 'deb-get_0.3.1-1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive deb-get_0.3.1-1_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 deb-get_0.3.1-1_all.deb
```

Debian is not supporting (yet? see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664) the ZST compressed archive format contrary to Ubuntu and so the archive format has to be converted before.

**Comment by natanjunges** [comment]
Please use the provided template for reporting bugs.
