### ISSUE TITLE
Linux Mint 20.3 (Una) is no longer supprted by the latest version.

### ISSUE THREAD

**Issue by kimme** [wimpysworld/deb-get#352]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

Linux Mint 20.3 (Una) is not supported anymore with the newest version. It worked fine up until the latest version....

 
❯ sudo deb-get update
[sudo] password for kimme:         
  [!] ERROR! Linux Mint Una is not supported because it is not derived from a supported Debian or Ubuntu release.

~ took 4s 
❯ sudo deb-get reinstall deb-get
  [!] ERROR! Linux Mint Una is not supported because it is not derived from a supported Debian or Ubuntu release.

~ 
❯ sudo apt-get reinstall deb-get
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reinstallation of deb-get is not possible, it cannot be downloaded.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

~

**Comment by kimme** [comment]
I have to uninstall the latest version, and re-install version 0.3.0

**Comment by natanjunges** [comment]
Please provide all information requested in the template.
