### ISSUE TITLE
Link the installation documentation to latest release, not to main

### ISSUE THREAD

**Issue by DiogoConstantino** [wimpysworld/deb-get#355]
Installation documentation should point to an asset on the latest release, and not to the main branch, as main may be broken, as is currently (see https://github.com/wimpysworld/deb-get/issues/344).

**Comment by natanjunges** [comment]
A solution is being proposed in #354.

**Comment by flexiondotorg** [comment]
This doesn't fix anything. 0.3.1 is broken, `main` is now fixed.

Making this change to link to a release keeps things in a broken state for longer.
