### ISSUE TITLE
Linux Mint has no option in apt-add-repository

### ISSUE THREAD

**Issue by natanjunges** [wimpysworld/deb-get#370]
### Expected behavior

PPAs should be added to Linux Mint using `apt-add-repository -y --no-update "${PPA}"`.

### Actual behavior

As the `apt-add-repository` command in Linux Mint is actually a rewrite in Python of the original tool from Debian, it does not support the `--no-update` option.

### Steps to reproduce

Try to install any package from a PPA in Linux Mint:
```shell
sudo deb-get install <pkg>
```

### Possible solution
It seems that the effect of the `--no-update` option is the default in the Linux Mint implementation, so this option could be removed when Linux Mint is detected.

**Comment by philclifford** [comment]
This may not be _only_ Mint but might be amenable to a generic solution rather than lots of per-distro fencing.
I'm thinking that it may be that either distros will be using the ubuntu or the debian tooling, so something like 
`dpkg -S $(command -v apt-add-repository)|cut -d: -f1`
so that  
```
software-properties-common -> ubuntu;
software-properties-python -> debian;
ubuntu -> "-y --no-update";
debian -> " -y";
```
hopefully without having to consider version histories ....

**Comment by M4rQu1Nh0S** [comment]
I noticied a similar problem with firefox-esr.

after analyze and done some changes at deb-get i solved the problem.

deb-get firefox-esr section as example:
```
function deb_firefox-esr() {
    if [ "${UPSTREAM_ID}" == "ubuntu" ]; then
        PPA="ppa:mozillateam/ppa"
        PRETTY_NAME="Firefox ESR"
        WEBSITE="https://www.mozilla.org/firefox/enterprise/"
        SUMMARY=" Firefox Extended Support Release."
    fi
}
```

Try remove lines with **if** and **fi**
The code now:
```
function deb_firefox-esr() {
        PPA="ppa:mozillateam/ppa"
        PRETTY_NAME="Firefox ESR"
        WEBSITE="https://www.mozilla.org/firefox/enterprise/"
        SUMMARY=" Firefox Extended Support Release."
}
```
And try to install your package again. 
I was done these steps some time ago at Ubuntu 22.04, although my issue was different from yours removing those lines i was able to install the package normally again. try it.

**Comment by natanjunges** [comment]
I think you commented to the wrong issue.

**Comment by M4rQu1Nh0S** [comment]
That's right, sorry.
