### ISSUE TITLE
Add notesnook

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#383]
I have checked that this app does not already have a pending request and has not previously been declined.
App Name: Notesnook
Download URL: https://notesnook.com/releases/linux/notesnook_amd64.deb
Website URL: https://notesnook.com/
App Summary: encrypted note taking app

**Comment by flexiondotorg** [comment]
There is no way to determine the current released version of Notesnook, which is required so `deb-get` can provide updates.

**Comment by dtantono** [comment]
based on the roadmap, they are going open source soon. maybe we will see that they will provide released version of this app
