### ISSUE TITLE
Release 0.3.3 no longer works on some distros

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#384]
It seems the problem has been re-introduced and whilst it works fine on

 *  Ubuntu Mate (presumably all ubuntu flavours)
 * Debian 11 (presumably all debians too)

It fails on Linux Mint with the error 

```
 [!] ERROR! Linux Mint Una is not supported because it is not derived from a supported Debian or Ubuntu release.
```
The change that closed #366 also appears to have broken/removed the change/fix that led to #365 
presumably re-introduces 
#327 KDE Neon 
#328 Zorin
#348 Pop as well as 
#352 Mint
(referred to try and catch some re-opens/issues)
I'll try and test on those to confirm or otherwise.

### Expected behavior

deb-get runs
### Actual behavior

deb-get errors (see above)

### Steps to reproduce

Describe the exact steps required to reproduce the issue.

#### /etc/os-release

```
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal

```

#### /etc/lsb-release

```bash
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.3
DISTRIB_CODENAME=una
DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"
```

#### deb-get version

n/a it is 0.3.3 but the version is bumped in testing
also it errors

### deb-get update

```
 [!] ERROR! Linux Mint Una is not supported because it is not derived from a supported Debian or Ubuntu release.
```

**Comment by philclifford** [comment]
Now fixed and [tested](https://github.com/philclifford/deb-get/actions/runs/2725405649) in main, including most of the [noted derivatives]( https://github.com/philclifford/deb-get/actions/runs/2725631286)

**Comment by natanjunges** [comment]
Your solution looks good, very similar to what I suggested in https://github.com/wimpysworld/deb-get/pull/366#issuecomment-1190333061. Please submit a pull request so we can fix this as soon as possible.

**Comment by guso** [comment]
Hi @philclifford, I'm on KDE Neon and I've tried to install it with the curl command on the README and it trows the reported error, but then I cloned the repo and replaced the binary for the cloned one and worked fine, reported version as 0.3.3, the curl command was showing 0.3.3-1, I could do some testing if needed

**Comment by natanjunges** [comment]
Did you get this error when trying to run the `deb-get` self-install command or when trying to install another package using the self-installed `deb-get`?

**Comment by philclifford** [comment]
hi @guso 

I just removed it from my test server to check (the automated testing tests the cloned version in effect but doesn't currently clean the environment and then try the README self-install) and had no problem reported
```
phil@qvm-neon:~$ sudo apt  remove deb-get
[sudo] password for phil: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following packages will be REMOVED:
  deb-get
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 118 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 190211 files and directories currently installed.)
Removing deb-get (0.3.3-1) ...
phil@qvm-neon:~$ sudo apt install curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.68.0-1ubuntu2.12).
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
phil@qvm-neon:~$ curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
  [+] Updating /var/cache/deb-get/deb-get.json
/var/cache/deb-get/deb-get_0.3.3-1_all.deb               100%[================================================================================================================================>]  24.10K  --.-KB/s    in 0.007s  
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
Selecting previously unselected package deb-get.
(Reading database ... 190207 files and directories currently installed.)
Preparing to unpack .../deb-get_0.3.3-1_all.deb ...
Unpacking deb-get (0.3.3-1) ...
Setting up deb-get (0.3.3-1) ...
phil@qvm-neon:~$ cat /etc/os-release 
NAME="KDE neon"
VERSION="5.25"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - 5.25"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

but

```
phil@qvm-neon:~$ which deb-get
/usr/bin/deb-get
phil@qvm-neon:~$ deb-get version
  [!] ERROR! KDE Neon Focal is not supported because it is not derived from a supported Debian or Ubuntu release.
phil@qvm-neon:~$ apt search deb-get
Sorting... Done
Full Text Search... Done
deb-get/now 0.3.3-1 all [installed,local]
  Script to "manage" .deb installs from 3rd party vendors/projects
```
because the self-install used main (working on KDE) to install the latest release deb (not working on KDE)

Until there is a new release (or some other solution) it is necessary to curl/clone and use the script from main and 
NOT `deb-get (re)-install deb-get`  and/or ensure the working deb-get script is earliest in the path ( I use /usr/local/bin for that ) 
and/or rename it to avoid accidentally clobbering it.

I don't think you need to test further @guso , but it you could confirm your KDE Neon version if not as tested above.

**Comment by natanjunges** [comment]
That is what I was thinking that could be happening.

**Comment by guso** [comment]
I just did the same steps you did there and got the exact same output, same os-release and same error

**Comment by philclifford** [comment]
Thanks for the confirmation. It is already fixed in main and will be in the next release.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/deb-get/commit/fe4cb91c60535c438af685894a4093e58eb241d4
