### ISSUE TITLE
Add VirtualBox

### ISSUE THREAD

**Issue by zocker-160** [wimpysworld/deb-get#385]
## Requesting a new app ✨

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: `VirtualBox`
 - Download URL: https://www.virtualbox.org/wiki/Linux_Downloads
 - Website URL: https://www.virtualbox.org/
 - App Summary: `VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product for enterprise as well as home use.`

EDIT: they are offering different .deb files for different versions of Ubuntu, I don't know if this is a problem though.

**Comment by philclifford** [comment]
downloads by os codename for Ubuntu and Debian is pretty ideal in fact
