### ISSUE TITLE
KDE Neon 20.04 is not supported because it is not derived from a supported Debian or Ubuntu release

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [wimpysworld/deb-get#397]
### Expected behavior

deb-get should output all available commands or execute any command.

### Actual behavior

Error:
`[!] ERROR! KDE Neon Focal is not supported because it is not derived from a supported Debian or Ubuntu release.`

### Steps to reproduce

1. install deb-get:
```
sudo apt install curl
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
```
2. try to run deb-get with any command:
```
deb-get update
```

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
NAME="KDE neon"
VERSION="5.25"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - 5.25"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

#### /etc/lsb-release

```bash
DISTRIB_ID=neon
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="KDE neon User - Plasma 5.25"
```

#### deb-get version

```bash
deb-get 0.3.3
```

### Suggested fix:
```bash
    # Fallback to ID_LIKE if ID was not 'ubuntu' or 'debian'
    # ID "ubuntu debian is a exclusive ID from KDE Neon 20.04."
    if [ "${UPSTREAM_ID}" != "ubuntu debian" ] &&[ "${UPSTREAM_ID}" != "debian" ] && [ "${UPSTREAM_ID}" != "ubuntu" ]; then
        UPSTREAM_ID_LIKE="$(grep "^ID_LIKE=" /etc/os-release | cut -d'=' -f2 | sed s/\"//g | cut -d' ' -f1)"
        UPSTREAM_ID="${UPSTREAM_ID_LIKE}"
    fi
```

**Comment by M4rQu1Nh0S** [comment]
The version at `main` branch is different from version .deb at `releases` page.
For some reason, the apt gets the .deb version instead the "deb-get" file at `main` branch.

Version .deb 0.3.4 will fix the issue. closing.

**Comment by natanjunges** [comment]
This is the intended behavior. Please wait until the next release.
