### ISSUE TITLE
Add AltServer-GUI

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#40]
AltServer is a popular sideloading app for iOS.
They have a deb available from their website.
https://github.com/powenn/AltServer-LinuxGUI/releases/download/0.1.8/AltServer.deb

**Comment by flexiondotorg** [comment]
Requires AltServer which is not available as a `.deb`. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)

**Comment by dtantono** [comment]
@flexiondotorg Altserver is just dependency and this GUI wrapper is available in .deb

**Comment by dtantono** [comment]
@flexiondotorg Altserver is just dependency and this GUI wrapper is available in .deb
