### ISSUE TITLE
Add Freetube

### ISSUE THREAD

**Issue by enigma9o7** [wimpysworld/deb-get#403]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [ ] I have checked that this app does not already have a pending request and has not previously been declined.
It was declined [previously](https://github.com/FreeTubeApp/FreeTube/releases/download/v0.16.0-beta/freetube_0.16.0_amd64.deb) apperantly because the developer calls the release a beta.   This isnt the nightly version/etc (which they also offer), this is the release version as there is no non- beta release, its been called beta forever.  Lots of software is perpetually beta.  deb-get hasnt reached 1.0 either for that matter.

 - App Name: FreeTube
 - Download URL: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.16.0-beta/freetube_0.16.0_amd64.deb
 Of course that changes with each version....
 - Website URL: https://freetubeapp.io/
 - App Summary: Private Youtube Client

**Comment by Xmetalfanx** [comment]
was going to take a fast look to add this one, but i'd want to ask if each version being marked as a pre-release and some (at least that i can see) being labeled as beta be a problem?  ... I see betas are not going to be accepted, even if say for example i have used it before and not had any issue .... i could see this addition being rejected just on those grounds (and logically i see why betas should be excluded)

**Comment by flexiondotorg** [comment]
Duplicate #108
