### ISSUE TITLE
Error for mullvad package

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#406]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date: Yes it is

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior
It should install the package

### Actual behavior
I got this error message
  [!] ERROR! Failed to download https://github.com/mullvad/mullvadvpn-app/releases/download/2022.2/MullvadVPN-2022.2_amd64.deb
https://github.com/mullvad/mullvadvpn-app/releases/download/2022.2/MullvadVPN-2022.2_amd64.deb.asc. Deleting /var/cache/deb-get/MullvadVPN-2022.2_amd64.deb.asc...
E: Unsupported file /var/cache/deb-get/MullvadVPN-2022.2_amd64.deb.asc given on commandline

### Steps to reproduce

I type sudo deb-get install mullvad
The messages are: 
 [+] Updating /var/cache/deb-get/mullvad.json
  [!] ERROR! Failed to download https://github.com/mullvad/mullvadvpn-app/releases/download/2022.2/MullvadVPN-2022.2_amd64.deb
https://github.com/mullvad/mullvadvpn-app/releases/download/2022.2/MullvadVPN-2022.2_amd64.deb.asc. Deleting /var/cache/deb-get/MullvadVPN-2022.2_amd64.deb.asc...
E: Unsupported file /var/cache/deb-get/MullvadVPN-2022.2_amd64.deb.asc given on commandline

### System information

Run the following a paste the output below:

#### /etc/os-release
NAME="KDE neon"
VERSION="5.25"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - 5.25"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```bash
cat /etc/os-release
```

  GNU nano 4.8                                               /etc/lsb-release                                                         
DISTRIB_ID=neon
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="KDE neon User - Plasma 5.25"

```bash
cat /etc/lsb-release
```

#### deb-get version

```bash
deb-get version
```
0.3.4

### deb-get update

```bash
deb-get update
```

**Comment by natanjunges** [comment]
Could replicate in Ubuntu 22.04, so it is not just for KDE Neon.

**Comment by natanjunges** [comment]
The `grep` performed on the JSON file is matching both the `*.deb` and the `*.deb.asc` files. I'm working on a fix.
