### ISSUE TITLE
Add Peek Gif recorder

### ISSUE THREAD

**Issue by FXBOY4EVA** [wimpysworld/deb-get#411]
## Requesting a new app ✨

 - [✓ ] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Peek
 - Download URL: https://code.launchpad.net/~peek-developers/+archive/ubuntu/stable
   (It is available in Debian repositories, as well as via AppImage, Flatpak and other distributions' repositories).
 - Website URL: https://github.com/phw/peek
 - App Summary: Peek - Simple animated GIF screen recorder with an easy to use interface

Peek has been one of my go-to tools for a while.
I figured since it has a PPA run by the developers it should be available via deb-get. Also figured Martin might enjoy this one.

**Comment by flexiondotorg** [comment]
Thanks for working on this. However, the versions of peek published in the Ubuntu archive since 20.04 are newer than the versions of peek published in the PPA, so I will not be adding this change.
