### ISSUE TITLE
Add Retro-Arch

### ISSUE THREAD

**Issue by GHMusicalCoder** [wimpysworld/deb-get#422]
## Requesting a new app ✨

 - [x ] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name:  Retro Arch
 - Download URL: ppa:libretro/stable
 - Website URL: www.retroarch.com
 - App Summary: RetroArch is a frontend for emulators, game engines and media players.

**Comment by natanjunges** [comment]
Being implemented at #416.

**Comment by flexiondotorg** [comment]
Closed via https://github.com/wimpysworld/deb-get/pull/416
