### ISSUE TITLE
portmaster versions mismatch at deb-get update.

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [wimpysworld/deb-get#425]
### Expected behavior

deb-get update should search and install the latest version of portmaster
Should search for version 0.8.12 and install this version but...

### Actual behavior

deb-get search for last version of portmaster **v0.8.12** but install the version **0.7.0~1**

In deb-get script....
```bash
function deb_portmaster() {
    if [ "${ACTION}" != "prettylist" ]; then
        VERSION_PUBLISHED="$(curl -s https://api.github.com/repos/safing/portmaster/releases/latest | grep -E '"name":' | tr -d "\"," | cut -d: -f2 | tr -d " v")"
    fi
    URL="https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb"
    PRETTY_NAME="Portmaster"
    WEBSITE="https://safing.io/portmaster/"
    SUMMARY="Portmaster is a free and open-source application that puts you back in charge over all your computer's network connections."
}
```
In function VERSION_PUBLISHED the deb-get will fetch the latest version, but will download the .deb file at `URL` line.
But the version of this .deb is the version **0.7.0~1**.

Exist a mismatch of versions here...

### Steps to reproduce

1. run `deb-get install portmaster`
2. run `deb-get update`
3. the following message will appear: 
```bash
  [+] portmaster (0.7.0~1) has an update pending. 0.8.12 is available.
```

### System information

This issue happens in:
**Ubuntu 22.04 & Ubuntu 20.04**
Other distros have not tested.

**Comment by natanjunges** [comment]
@flexiondotorg this package should not even be supported by `deb-get`, as it is in alpha stage.

**Comment by M4rQu1Nh0S** [comment]
> @flexiondotorg this package should not even be supported by `deb-get`, as it is in alpha stage.

That's not the real problem here, because the version 0.7.0 is the stable version, only version after are in Alpha stage.
Happens to deb-get are getting versions of github releases instead search for stable version directly from website. Not?

I supposed that the problem are in VERSION_PUBLISHED line only, please, correct me if i'm wrong.

**Comment by M4rQu1Nh0S** [comment]
Correction:
0.7.0 is the version of the installer of .deb file

The true version of portmaster, today, is 0.8.13 but from stable builds.

So, the problem is: the deb-get is looking for the latest releases on the  project's github page and comparing it to the .deb installer, which are different.

**Comment by natanjunges** [comment]
From [their website](https://safing.io/portmaster/):

> Portmaster is Alpha Software - expect hiccups here and there

From [their GitHub repo](https://github.com/safing/portmaster/blob/0a46f541dbdfc28202839cf21507ac51cb628a79/README.md?plain=1#L8-L10):
```markdown
**⚠️ Disclaimer**


> Portmaster is Alpha Software, treat as such; expect bugs here and there. Early Adopters welcome.
```

**Comment by M4rQu1Nh0S** [comment]
So, this issue will be closed since deb-get don't support this software since him is treated as alpha stage and out of deb-get approve scope...
