### ISSUE TITLE
Add WineHQ's Wine Build

### ISSUE THREAD

**Issue by bayazidbh** [wimpysworld/deb-get#427]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Wine
 - Download URL: https://wiki.winehq.org/Ubuntu
 - Website URL: https://www.winehq.org/
 - App Summary: Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, macOS, & BSD.

Hi, I'm not entirely sure if this fully fits with the acceptable, but I thought it'd be better to have a definitive rejection if it's not the case.

The reason why I am submitting this is because many guides for gaming on Linux recommends installing Wine build from WineHQ, especially Wine-Staging, and I recall a few guides mentioning pairing Lutris with Wine-Staging as well.

I'd just thought that given both Lutris and CrossOver is here, it might be worth it to add WineHQ's build given how commonly recommended it is, especially as I recall Ubuntu's build is generally outdated, especially for gaming.

If it falls outside of the bound of what's accepted or an exception cannot be made, feel free to close the issue, and thank you for your time regardless.

**Comment by Fuseteam** [comment]
i have no idea how i missed this, can i assume it's within scope?

**Comment by philclifford** [comment]
Closed by #632
