### ISSUE TITLE
Requesting a Dockbarx

### ISSUE THREAD

**Issue by Flashwalker** [wimpysworld/deb-get#440]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Dockbarx (dockbarx, dockbarx-themes-extra, xfce4-dockbarx-plugin)
 - Download URL: ppa:xuzhen666/dockbarx, https://ppa.launchpadcontent.net/xuzhen666/dockbarx/ubuntu/pool/main/d/, https://ppa.launchpadcontent.net/xuzhen666/dockbarx/ubuntu/pool/main/x/
 - Website URL: https://github.com/M7S/dockbarx
 - App Summary: DockBarX is a lightweight taskbar / panel replacement for Linux which works as a stand-alone dock (called DockX), as an an Avant Window Navigator applet, as a Xfce4 panel applet1, as a matepanel applet2 or as a legacy gnome2 panel applet. DockbarX is a fork of dockbar made by Aleksey Shaferov. DockbarX branch is developed by Matias Särs

**Comment by flexiondotorg** [comment]
DockBarX is not actively maintained, please see https://github.com/wimpysworld/deb-get/blob/main/CONTRIBUTING.md for details.

**Comment by Flashwalker** [comment]
ok, but still works fine on 22.04

**Comment by Flashwalker** [comment]
I actually ran into some bugs in DockBarX a few days ago, I wrote to the developer and he fixed them in a couple of days.  
So even though this program is not being actively developed, but bugs are being fixed promptly.
