### ISSUE TITLE
Add Skype-preview

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#45]
Skype-Insider is a popular messaging app by Microsoft
They have a deb available from their website.
https://repo.skype.com/latest/skypeforlinux-64-insider.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any daily/nightly, beta or pre-release software. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
