### ISSUE TITLE
Add libreoffice 

### ISSUE THREAD

**Issue by FallCheetah7373** [wimpysworld/deb-get#453]
- App Name: Libreoffice
 - Download URL: https://www.libreoffice.org/donate/dl/deb-x86_64/7.4.0/en-GB/LibreOffice_7.4.0_Linux_x86-64_deb.tar.gz
 - Website URL: https://www.libreoffice.org/download/download/?type=deb-x86_64&version=7.4.0&lang=en-GB
 - App Summary: LibreOffice is a free and powerful office suite, and a successor to OpenOffice.org (commonly known as OpenOffice).
Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.

**Comment by Xmetalfanx** [comment]
honestly not sure about deb-get and installing debs inside of tarball files.   It seems this version IS ahead of some of the Ubuntu repo's versions ... https://launchpad.net/~libreoffice/+archive/ubuntu/ppa is another option perhaps though It seems the "tarball deb" maybe newer than the PPA version and "is the PPA version really that much newer than what Ubuntu packages?" may come up as a question

**Comment by FallCheetah7373** [comment]
>  "is the PPA version really that much newer than what Ubuntu packages?" may come up as a question

I am not sure if ubuntu updates libreoffice frequently just like browsers but if they don't it might get outdated over time I am also not sure about the average update cycle of libreoffice either to answer that question.

**Comment by Xmetalfanx** [comment]
this maybe worth adding (if the devs approve) since it's hard to judge now since the 22.04 LTS is so new but it can go "out of date" over time i suppose I see focal is still (Ubuntu repo version) is still on the 6.x series when LO has been on the 7.x series for awhile

**Comment by flexiondotorg** [comment]
Sorry, the way this package is distributed doesn't fit with `deb-get`
