### ISSUE TITLE
Softmaker-office-2021 installation is freezing

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#460]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

I should install the app properly

### Actual behavior
it is freezing
### Steps to reproduce
I type sudo deb-get install softmaker-office-2021 and then it freezes

### System information

Run the following a paste the output below:

#### /etc/os-release
NAME="KDE neon"
VERSION="5.25"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - 5.25"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```bash
cat /etc/os-release
```

  GNU nano 4.8                                               /etc/lsb-release                                                         
DISTRIB_ID=neon
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="KDE neon User - Plasma 5.25"

```bash
cat /etc/lsb-release
```

#### deb-get version

```bash
deb-get version
```
0.3.5

### deb-get update

```bash
deb-get update
```

**Comment by philclifford** [comment]
Installs fine here on your platform with the current release.  
![image](https://user-images.githubusercontent.com/8797027/185769397-a10cd7bc-b48e-490a-a5b3-437cd8719c0a.png)

It looks to me like you may have issues ( not related to `deb-get` ) causing your "hang". 
Can you successfully install the deb from their site directly ?

**Comment by philclifford** [comment]
BTW you should not `sudo deb-get` : `deb-get` will seek elevated privileges as and when required

**Comment by dtantono** [comment]
yes I use curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get to get the deb directly. But, usually I use sudo deb-get to get the other packages. But, only this one is freezing. That is strange (FYI, I use deb-get install softmaker-office-2021 and it works)
