### ISSUE TITLE
deb-get does not recognize Linux Mint Debian Edition (LMDE) as a supported release

### ISSUE THREAD

**Issue by jruschme** [wimpysworld/deb-get#462]
### Expected behavior

deb-get should recognize LMDE 5 (Elsie) as Debian bullseye

### Actual behavior

deb-get reports "Linux Mint Elsie is not supported because it is not derived from a supported Debian or Ubuntu release."

### Steps to reproduce

Install deb-get on LMDE 5. 
Run 'deb-get' from root prompt.

### System information

Run the following a paste the output below:

#### /etc/os-release

PRETTY_NAME="LMDE 5 (elsie)"
NAME="LMDE"
VERSION_ID="5"
VERSION="5 (elsie)"
ID=linuxmint
ID_LIKE=debian
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=elsie
DEBIAN_CODENAME=bullseye

#### /etc/lsb-release

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=5
DISTRIB_CODENAME=elsie
DISTRIB_DESCRIPTION="LMDE 5 Elsie"

#### deb-get version
0.3.5

### deb-get update
n/a

**Comment by jruschme** [comment]
From a quick look at the code, it appears that the root cause is that a Debian-derived distro is expected to have a Debian codename as the VERSION_CODENAME in /etc/os-release. LMDE, however, is more like their Ubuntu-based counterpart in that they put the debian version in a DEBIAN_CODENAME variable in /etc/os-release.

**Comment by CuriousApe2020** [comment]
I have the same issue running Debian Bookworm.
