### ISSUE TITLE
Add FreeOffice

### ISSUE THREAD

**Issue by FallCheetah7373** [wimpysworld/deb-get#464]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: FreeOffice 
 - Download URL:  https://www.freeoffice.com/download.php?filename=https://www.softmaker.net/down/softmaker-freeoffice-2021_1050-01_amd64.deb
 - Website URL: https://www.freeoffice.com/en/
 - App Summary: FreeOffice 2021 is a proprietary yet complete Office suite with a word processor, a spreadsheet application and a presentation program – all seamlessly compatible with their counterparts in Microsoft Office.

**Comment by flexiondotorg** [comment]
SoftMaker Office is already available via `deb-get`, it this needed?

**Comment by FallCheetah7373** [comment]
> SoftMaker Office is already available via `deb-get`, is this needed?

I don't think its necessary since onlyoffice works pretty well...from my very recent testing few hours ago.

**Comment by flexiondotorg** [comment]
FreeOffice seems to be extremely limited. I'll close this as I don't see the value of including it given the other Office Suites that `deb-get` already supports.
