### ISSUE TITLE
Add electron-mail

### ISSUE THREAD

**Issue by ghost** [wimpysworld/deb-get#471]
## Requesting a new app ✨
 - [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: electron-mail
 - Download URL: https://github.com/vladimiry/ElectronMail/releases/download/v5.1.0/electron-mail-5.1.0-linux-amd64.deb
 - Website URL: https://github.com/vladimiry/ElectronMail
 - App Summary: ElectronMail is an Electron-based unofficial desktop client for ProtonMail.

**Comment by sbstn87** [comment]
Hi, are there any chances this can be revived and added to deb-get? Developer still publishes .deb packages:

https://github.com/vladimiry/ElectronMail/releases
