### ISSUE TITLE
Add makedeb

### ISSUE THREAD

**Issue by pirate486743186** [wimpysworld/deb-get#472]
## Requesting a new app ✨
 - [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: makedeb
 - Download URL: https://docs.makedeb.org/installing/apt-repository/
 - Website URL: https://www.makedeb.org/
 - App Summary: A simple to use deb packaging tool and the mpr repository, a AUR-like sister project for debian and derivatives.

**Comment by philclifford** [comment]
Thanks @pirate486743186. Hopefully I managed to credit you in the fixed / updated PR.
