### ISSUE TITLE
user controlled autoremove and -y

### ISSUE THREAD

**Issue by pirate486743186** [wimpysworld/deb-get#476]
## Requesting a new feature 🧑‍💻

autoremove and -y by default are annoying.

you may have stuff marked auto-installed on purpose. Maybe you are leaving some old kernels, maybe you are trying to compile something, maybe testing something....

-y is for scripts, where you already know it's correct. Interactively, you don't want -y, maybe you forgot something, maybe you did a typo, maybe it will try to uninstall your desktop or X or it want to download 1GB of updates ....

there's a reason why apt follows certain conventions. deb-get should follow them more closely. Also people expect that get-deb will work like apt.

I would propose to remove -y and autoremove. Maybe just add an option to send custom options to the apt command. They are plenty more apt options, cloning them all one by one would not make sense.

**Comment by flexiondotorg** [comment]
There is a lot of *maybe's* in your justification which I am not currently convinced are real issues for users.

I am going to close this for now, but perhaps we can revisit this in the future should the need arise.
