### ISSUE TITLE
Don't update default repository packages with upgrade

### ISSUE THREAD

**Issue by Forage** [wimpysworld/deb-get#477]
### Expected behavior
When running `deb-get upgrade`, deb-get should only update supported packages without touching those present in the default OS repositories.

### Actual behavior
Now when performing an upgrade, deb-get is running an `apt upgrade` first, causing all packages being updated, not just those supported by deb-get.
This is unexpected behaviour.

**Comment by flexiondotorg** [comment]
This is the intended behaviour.
