### ISSUE TITLE
Add Quarto

### ISSUE THREAD

**Issue by pep-sanwer** [wimpysworld/deb-get#478]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Quarto
 - Download URL: https://quarto.org/docs/download/
 - Website URL: https://quarto.org/
 - App Summary: Quarto - an open-source scientific and technical publishing system built on Pandoc

**Comment by Marwe** [comment]
Releases via github:
https://github.com/quarto-dev/quarto-cli/releases/

**Comment by Marwe** [comment]
I overlooked that it is in the source already, thank you!
I tested it successfully on Ubuntu 20.04 focal

This got the install job done without issues:
```
./deb-get update
./deb-get install quarto
```

**Comment by philclifford** [comment]
@pep-sanwer the related PR was merged but not linked properly to this issue.  Please close this issue.  Many thanks for the contribution.
