### ISSUE TITLE
Add Rare

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#48]
Rare is a open source Epic Games client
They have a deb available from their website.
https://github.com/Dummerle/Rare/releases/download/1.8.9/Rare-1.8.9.deb

**Comment by flexiondotorg** [comment]
The packaging of Rare is not complete and results in a broken install.

**Comment by peutch** [comment]
Just a remark on this: the rare package is also provided by the makedeb Package Repository (https://mpr.makedeb.org/) that also contains some others.
