### ISSUE TITLE
deb-get doesn't upgrade Virtualbox 6.1 to 6.1.38

### ISSUE THREAD

**Issue by thegreatyellow67** [wimpysworld/deb-get#483]
Hi, deb-get version 0.3.5 don't upgrade Virtualbox 6.1 to newer version 6.1.38.

### Expected behavior
A Virtualbox upgrade from older version (mine was 6.1.34) to 6.1.38.

### Actual behavior

Actually, deb-get seems that doesn't recognize the newer version of Virtualbox.

### Steps to reproduce

With an older version of Virtualbox (mine was 6.1.34), try to upgrade. 

### System information

Linux Mint 20.3 Cinnamon
cinnamon 5.2.7
kernel 5.4.0-125-generic

**Comment by natanjunges** [comment]
As you can see in the output of `deb-get show virtualbox-6.1` (ran in Ubuntu 22.04):
```
VirtualBox 6.1
  Package:	virtualbox-6.1
  Updater:	apt
  Installed:	6.1.38-153438~Ubuntu~jammy
  Architecture:	amd64
  Repository:	deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian jammy contrib
  Website:	https://www.virtualbox.org/
  Summary:	VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use.
```
The updater is `apt`, not `deb-get`, which means that `deb-get` is not responsible for this behaviour, or at least it should not be. With that said, the following questions could clarify what is going on:
- Was the package originally installed by `deb-get`?
- When running `deb-get search virtualbox-6.1`, does it show as installed?
- What is the output of `sudo deb-get update`?
- What is the output of `sudo deb-get upgrade`?

**Comment by thegreatyellow67** [comment]
Thanks natanjunges for your explanation. I've understood, I'm quite new with deb-get, so I'll try to know better it.
Indeed, Virtualbox was installed from the .deb package downloaded from the Virtualbox site, I simply believed that deb-get, finding it, updated it to a newer version!
