### ISSUE TITLE
deb-get not working on debian bookworm

### ISSUE THREAD

**Issue by joanarling** [wimpysworld/deb-get#487]
# deb-get issue template

## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

Using deb-get v0.3.5 on debian bookworm
/etc/os-release:
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
/etc/debian_version:
bookworm/sid

deb-get is not working on my system (amd64), because UPSTREAM_CODENAME gets no value (Line 2595). This fixes it for me:

+ diff -u /usr/bin/deb-get.org /usr/bin/deb-get
--- /usr/bin/deb-get.org	2022-08-20 01:51:22.000000000 +0200
+++ /usr/bin/deb-get	2022-09-03 15:17:19.728406939 +0200
@@ -2592,13 +2592,15 @@
 
     case "${UPSTREAM_ID}" in
         ubuntu) UPSTREAM_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2);;
-        debian) UPSTREAM_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2);;
+        debian)
+		#UPSTREAM_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2);;
+		UPSTREAM_CODENAME=$(grep ^PRETTY /etc/os-release|cut -d\  -f3|cut -d/ -f1);;
         *) UPSTREAM_CODENAME="";;
     esac
 else
     fancy_message fatal "/etc/os-release not found. Quitting"
 fi
-
+#echo "${UPSTREAM_CODENAME}"
 case "${UPSTREAM_CODENAME}" in
     buster)   UPSTREAM_RELEASE="10";;
     bullseye) UPSTREAM_RELEASE="11";;

HTH,
joan

**Comment by natanjunges** [comment]
Can you provide the output of `cat /etc/lsb-release`?

**Comment by joanarling** [comment]
I'm afraid no, because there is no /etc/lsb-release. I might point out that I installed the system from a bookworm iso (IIRC directly from Debian), then changed the setting in /etc/apt/sources.list to "testing". Perhaps that's why. Ihave /etc/apparmor.d/lsb_release, but that does not look helpful (I'll append it (anyway).

HTH, Joan

/etc/apparmor.d/lsb_release
--8<--
# Note: This profile does not specify an attachment path because it is
# intended to be used only via "Px -> lsb_release" exec transitions from
# other profiles. We want to confine the lsb_release(1) utility when it
# is invoked from other confined applications, but not when it is used
# in regular (unconfined) shell scripts or run directly by the user.

abi <abi/3.0>,

include <tunables/global>

# Do not attach to /usr/bin/lsb_release by default
profile lsb_release {
  include <abstractions/base>
  include <abstractions/python>

  owner @{PROC}/@{pid}/fd/ r,

  /dev/tty rw,

  /usr/bin/lsb_release r,
  /usr/bin/python3.{1,}[0-9] mr,

  /etc/debian_version r,
  /etc/default/apport r,
  /etc/dpkg/origins/** r,
  /etc/lsb-release r,
  /etc/lsb-release.d/ r,

  /{usr/,}bin/bash ixr,
  /{usr/,}bin/dash ixr,
  /usr/bin/basename ixr,
  /usr/bin/dpkg-query ixr,
  /usr/bin/getopt ixr,
  /usr/bin/sed ixr,
  /usr/bin/tr ixr,

  # TODO - many more permissions needed for this to work
  deny /usr/bin/apt-cache x,

  /usr/bin/ r,
  /usr/include/python*/pyconfig.h r,
  /usr/share/distro-info/** r,
  /usr/share/dpkg/** r,
  /usr/share/terminfo/** r,
  /var/lib/dpkg/** r,

  # file_inherit
  deny /tmp/gtalkplugin.log w,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/lsb_release>
}
-->8--

-- 
The soul would have no rainbows, if the eyes had no tears.

----- Original message -----

**Comment by flexiondotorg** [comment]
Please paste the output from `cat /etc/os-release`

**Comment by CuriousApe2020** [comment]
Same issue here my output from cat /etc/os-release:

```
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

**Comment by joanarling** [comment]
Oops... I just rebooted my raspi (which I rarely do, hence my late "insight")

Raspian version of /etc/os-release:
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Debian version:
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

That invalidates the diff I submitted in my OP. The "cut" would have to be modified according the ID variable (or the substring of PRETTY_NAME). Hardly an elegant solution. Better idea, anyone?
Oh yes, Raspian doesn't have /etc/lsb*, either.

Joan

**Comment by chiak597** [comment]
Debian has dropped VERSION_ID, VERSION and *CODENAME variables from /etc/os-release in base-files 12, so grepping UPSTREAM_CODENAME returns empty value on both bookworm and sid.

https://tracker.debian.org/news/1249897/accepted-base-files-12-source-into-unstable/

**Comment by joanarling** [comment]
----- Original message -----
> From: chiak597 ***@***.***>

> Debian has dropped VERSION_ID, VERSION and *CODENAME variables from /etc/os-release in base-files 12, so
> grepping UPSTREAM_CODENAME returns empty value on both bookworm and sid.

It might be a good idea, then, not to rely on lsb_release too much. Both Raspbian (Bullseye) and Debian (Bookworm)
complain about missing LSB Modules, and deb-get only escapes an error because it reads from STDIN and not STDERR.

I've reworked my patch (see OP) to work on both Raspian and Debian, but I have not tested for long-term issues (i.e. packages clashing). Admittedly, elegance looks different, but that's all I could come up with.

Here we go:

--- /usr/bin/deb-get.org	2022-08-20 01:51:22.000000000 +0200
+++ /usr/bin/deb-get	2022-09-07 23:25:49.324962152 +0200
@@ -2572,6 +2572,7 @@
 OS_ID=$(lsb_release --id --short)
 case "${OS_ID}" in
   Debian) OS_ID_PRETTY="Debian";;
+   Raspbian) OS_ID_PRETTY="Debian";;
   Linuxmint) OS_ID_PRETTY="Linux Mint";;
   Neon) OS_ID_PRETTY="KDE Neon";;
   Pop) OS_ID_PRETTY="Pop!_OS";;
@@ -2592,13 +2593,17 @@
 
     case "${UPSTREAM_ID}" in
         ubuntu) UPSTREAM_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2);;
-        debian) UPSTREAM_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2);;
+        debian)
+		#UPSTREAM_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2);;
+		UPSTREAM_CODENAME=$(grep ^PRETTY /etc/os-release|cut -d\  -f3-4|sed 's/\/.*//g'|tr -d " 0-9()\"")
+	;;
         *) UPSTREAM_CODENAME="";;
     esac
 else
     fancy_message fatal "/etc/os-release not found. Quitting"
 fi
-
case "${UPSTREAM_CODENAME}" in
     buster)   UPSTREAM_RELEASE="10";;
     bullseye) UPSTREAM_RELEASE="11";;

**Comment by easbarba** [comment]
same here, debian/sid

**Comment by chriswayg** [comment]
Similar issue here after installing:
 _Debian GNU/Linux testing Bookworm - Unofficial amd64 DVD Binary-1 with firmware 20220829-03:47_

$ cat  /etc/os-release
```
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

$ cat /etc/lsb-release
`cat: /etc/lsb-release: No such file or directory`

As a temporary workaround, I changed the [line](https://github.com/wimpysworld/deb-get/blob/fb2ca3f6904b20ac6c1b14a32955233f8f89c519/deb-get#L2643) to 'warn' so it will work, as the standard error is 'fatal' and aborts:
> [!] ERROR! Debian Bookworm is not supported because it is not derived from a supported Debian or Ubuntu release.

**Comment by natanjunges** [comment]
I'm working on a solution.
