### ISSUE TITLE
Deadbeef does not download & install

### ISSUE THREAD

**Issue by coffseducation** [wimpysworld/deb-get#495]
## Reporting a bug 🐛

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

deb-get install deadbeef
  -Deadbeef downloads and installs.

### Actual behavior

deb-get install deadbeef
  [!] ERROR! Download URL for deadbeef is empty. Skipping.

### Steps to reproduce
step 1. deb-get install deadbeef

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
cat /etc/os-release
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
#### /etc/lsb-release

```bash
cat /etc/lsb-release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
#### deb-get version

```bash
deb-get version
```
0.3.5
### deb-get update

```bash
deb-get update
```
Hit:1 https://brave-browser-apt-release.s3.brave.com stable InRelease
Hit:2 https://updates.signal.org/desktop/apt xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:5 http://ppa.launchpad.net/bit-team/stable/ubuntu jammy InRelease
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Ign:7 https://kx.studio/repo stable InRelease
Hit:8 https://ppa.launchpadcontent.net/kubuntu-ppa/backports-extra/ubuntu jammy InRelease
Hit:9 http://ppa.launchpad.net/kdenlive/kdenlive-stable/ubuntu jammy InRelease
Ign:10 https://kx.studio/repo gcc5 InRelease
Hit:11 http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu jammy InRelease
Hit:12 https://kx.studio/repo stable Release
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Hit:14 https://kx.studio/repo gcc5 Release
Hit:17 http://ppa.launchpad.net/pbek/qownnotes/ubuntu jammy InRelease
Fetched 324 kB in 3s (115 kB/s)
Reading package lists...
  [+] Updating /var/cache/deb-get/deb-get.json
  [+] Updating /var/cache/deb-get/hugo.json
  [+] Updating /var/cache/deb-get/ksnip.json
  [+] Updating /var/cache/deb-get/mullvad-vpn.json

**Comment by natanjunges** [comment]
Working on a fix.
