### ISSUE TITLE
Add support for the Google Cloud SDK

### ISSUE THREAD

**Issue by OhMyMndy** [wimpysworld/deb-get#499]

**Comment by sachinsejwal** [comment]
Hi @OhMyMndy ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by AditSaxena** [comment]
@flexiondotorg 
If the issue is open, I would like to work on it.

**Comment by natanjunges** [comment]
#500 already implements this.
