### ISSUE TITLE
add FrostWire

### ISSUE THREAD

**Issue by peutch** [wimpysworld/deb-get#531]
- App Name: FrostWire
 - Download URL: https://www.frostwire.com/download/?os=ubuntu
 - Website URL: https://www.frostwire.com/
 - App Summary: Cloud Downloader, BitTorrent Client and Media Player. Search, download, play.

Hi, it is strange that I did not already report this one but searching issues confirm me that it is missing.

**Comment by flexiondotorg** [comment]
Downloads are here: https://github.com/frostwire/frostwire/releases/

**Comment by natanjunges** [comment]
Closed by #619.
