### ISSUE TITLE
Add Wraith-Master

### ISSUE THREAD

**Issue by kz6fittycent** [wimpysworld/deb-get#542]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined. 
 - App Name: wraith-master
 - Download URL: https://github.com/serebit/wraith-master/releases
 - Website URL: https://github.com/serebit/wraith-master/
 - App Summary: Wraith Master is a feature-complete graphical and command-line application for controlling the RGB LEDs on AMD's Wraith stock coolers.

Please see: https://github.com/wimpysworld/deb-get/pull/541

**Comment by natanjunges** [comment]
Closed by #541.
