### ISSUE TITLE
Add Steam

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#56]
This is popular gaming application and I know we can install it via apt for now. But, it is just a precaution if Steam will be replaced by snap version in the future. 
They have a deb available from their website.
https://cdn.akamai.steamstatic.com/client/installer/steam.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any packages from the official Debian or Ubuntu archives. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
