### ISSUE TITLE
Add Prospect Mail

### ISSUE THREAD

**Issue by dnet890** [wimpysworld/deb-get#569]
I have checked that this app does not already have a pending request and has not previously been declined.
App Name: ProspectMail
Download URL: https://github.com/julian-alarcon/prospect-mail/releases/download/v0.4.0/prospect-mail_0.4.0_amd64.deb
Website URL: https://github.com/julian-alarcon/prospect-mail
App Summary: The Outlook desktop client for the new Outlook Interface from Microsoft 365.

**Comment by gusdemayo** [comment]
Seconded
