### ISSUE TITLE
Add viber

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#57]
Viber is a messaging application
They have a deb available from their website.
https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that provides a reliable way to dynamically determine the current published version. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
