### ISSUE TITLE
Mullvad 2022.5 error

### ISSUE THREAD

**Issue by PolGZ** [wimpysworld/deb-get#587]
### Expected behavior

Install new version of MullvadVPN when `deb-get upgrade`

### Actual behavior

```
dpkg: warning: version '2022.5
2022.5' has bad syntax: invalid character in version number
  [!] ERROR! Failed to download https://github.com/mullvad/mullvadvpn-app/releases/download/2022.5/MullvadVPN-2022.5_amd64.deb
https://github.com/mullvad/mullvadvpn-app/releases/download/2022.5/MullvadVPN-2022.5_arm64.deb. Deleting /var/cache/deb-get/MullvadVPN-2022.5_arm64.deb...
E: Unsupported file /var/cache/deb-get/MullvadVPN-2022.5_arm64.deb given on commandline
```

### Steps to reproduce

deb-get update
deb-get upgrade

#### /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

#### deb-get version

0.3.6

---

Manually checking the indicated URL seems to work: https://github.com/mullvad/mullvadvpn-app/releases/download/2022.5/MullvadVPN-2022.5_amd64.deb

**Comment by philclifford** [comment]
Thanks for the report.  They added arm support and found a hole in our logic. Sorted by :point_up:
