### ISSUE TITLE
Onlyoffice cannot be installed

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#595]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

I typed sudo deb-get install onlyoffice-desktopeditors and it does not worked

### Actual behavior

I got output sudo deb-get install onlyoffice-desktopeditors
  [+] Updating /var/cache/deb-get/onlyoffice-desktopeditors.json
/var/cache/deb-get/onlyoffice-des 100%[==========================================================>] 190.71M  2.32MB/s    in 41s     
E: Unable to correct problems, you have held broken packages.

### Steps to reproduce

type sudo deb-get install onlyoffice-desktopeditors and it does not worked

### System information

Run the following a paste the output below:

#### /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

```bash
cat /etc/os-release
```
                                                    
  GNU nano 6.2                                               /etc/lsb-release                                                        
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

```bash
cat /etc/lsb-release
```

#### deb-get version

```bash
deb-get version
```
0.3.4

### deb-get update

```bash
deb-get update
```

**Comment by natanjunges** [comment]
I already spotted that, and a fix has already been done.
