### ISSUE TITLE
Add gSubs

### ISSUE THREAD

**Issue by peutch** [wimpysworld/deb-get#599]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: gSubs
 - Download URL: https://github.com/sanjevirau/gsubs/releases
 - Website URL: https://cholaware.com/gsubs/
 - App Summary: Finds you the perfect subtitle match

**Comment by flexiondotorg** [comment]
Has not seen any development for over 2 years. Closing as unmaintained.
