### ISSUE TITLE
Add i3wm

### ISSUE THREAD

**Issue by budRich** [wimpysworld/deb-get#609]
## Requesting a new app ✨

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: i3
 - Download URL: https://i3wm.org/docs/repositories.html
 - Website URL: https://i3wm.org/
 - App Summary: tiling window manager

i3 officially provides repositories for debian and ubuntu (https://i3wm.org/docs/repositories.html) .
There are two *flavors*:  
- stable which is a build of the latest release
- development, auto builds on every commit to the master branch of the git repo

As I understand the packages supported by deb-get needs to have the same name as the package to be installed, for both **stable** and **development** version (as well as normal ubuntu debian) the package name is **i3**. Which i guess means both can't be included in deb-get?

I tried making my own entry with the development version and got it working with, [natanjunges:extrepo](https://github.com/natanjunges/deb-get/tree/extrepo)

`/etc/deb-get/01-main.d/i3`:  
```
DEFVER=1
CODENAMES_SUPPORTED="kinetic"
ASC_KEY_URL="https://baltocdn.com/i3-window-manager/signing.asc"
APT_REPO_URL="https://baltocdn.com/i3-window-manager/i3/i3-autobuild-ubuntu/ all main"
APT_REPO_OPTIONS="arch=amd64"
PRETTY_NAME="i3"
WEBSITE="https://i3wm.org/"
SUMMARY="i3 window manager - Development release (automatically built a few minutes after every commit)"
```

I added **CODENAMES_SUPPORTED**, since according to the documentation:  
>Development versions are only available for the latest version of Ubuntu, which is bionic at the moment.

**Comment by philclifford** [comment]
A possible solution, now that the extrepo work has been merged, would be to submit the stable version as a contribution into `01-main` and provide the nightly development version in an external repo ( e.g. on a branch - my fork has an `extras` branch with a couple of examples, one of which may be familiar :smiling_imp: ) .  From a `deb-get` point of view the development version, if added, would take precedence.  It might be sensible to document how to pin/prefer the development repo in the definition as well.

**Comment by philclifford** [comment]
The above PR adds the stable version.  It can be overridden using the development definition above via `/etc/deb-get/99-local.d/` or an external repo. (and if an external repo included the dev version the stable can be forced by copying it into `99-local`)
