### ISSUE TITLE
Add Microsoft-Edge-Beta

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#62]
Microsoft Edge have their own beta version
They have a deb available from their website.
https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_101.0.1210.31-1_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any daily/nightly, beta or pre-release software. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
