### ISSUE TITLE
Add IPFS Desktop

### ISSUE THREAD

**Issue by mikabak** [wimpysworld/deb-get#623]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: IPFS Desktop
 - Download URL: https://github.com/ipfs/ipfs-desktop/releases
 - Website URL: https://ipfs.tech/
 - App Summary: A peer-to-peer hypermedia protocol
designed to preserve and grow humanity's knowledge
by making the web upgradeable, resilient, and more open.

**Comment by natanjunges** [comment]
Closed by #624.
