### ISSUE TITLE
Hugo still not working in latest release

### ISSUE THREAD

**Issue by kd2flz** [wimpysworld/deb-get#630]
## Reporting a bug 🐛

This sounds like this has been fixed already in [this](https://github.com/wimpysworld/deb-get/pull/564) PR. This was fixed 20 days ago, but it's still not working in the current release. I'm hoping that there can be a new release of deb-get soon, since I'm submitting a PR to hugo with deb-get installation instructions. 

Please make sure the version of `deb-get` you are using is up to date:

### Expected behavior

```bash
deb-get install hugo 
``` 
should install hugo

### Actual behavior

This is the output I get:
```bash
[+] Updating /var/cache/deb-get/hugo.json
  [!] ERROR! Download URL for hugo is empty. Skipping.
```

### Steps to reproduce

1. Install deb-get per the instructions on GitHub
2. deb-get install hugo

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

#### /etc/lsb-release

```bash
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
```

#### deb-get version

```bash
0.3.6
```

**Comment by philclifford** [comment]
Was indeed fixed in #563 .  Will thus be working in next release unless there are more breaking upstream changes,  As of now it installs fine on kinetic using HEAD of main so :crossed_fingers:
