### ISSUE TITLE
Add XnConvert

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#64]
XnConvert is good image converter
They have a deb available from their website.
https://download.xnview.com/XnConvert-linux-x64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that provides a reliable way to dynamically determine the current published version. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)

**Comment by falko** [comment]
@flexiondotorg XnConvert's own update check uses this machine-readable file: https://www.xnview.com/update.txt
That should get us going, right? Can you please re-open the issue?

**Comment by philclifford** [comment]
something like 

```
VERSION_PUBLISHED=$(wget https://www.xnview.com/update.txt -q -O- |grep -A1 'XnView]'| grep version | cut -d= -f2)
#  2.52.2
VERSION_PUBLISHED=$(wget https://www.xnview.com/update.txt -q -O- |grep -A1 'XnConvert]'| grep version | cut -d= -f2)
# 1.10


```
