### ISSUE TITLE
Add Clockify client

### ISSUE THREAD

**Issue by Giako** [wimpysworld/deb-get#651]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Clockify
 - Download URL: https://clockify.me/downloads/Clockify_Setup.deb
 - Website URL: https://clockify.me/
 - App Summary: Clockify is a time tracker and timesheet app that lets you track work hours across projects

EDIT: first PR closed as there is no way to retrieve the .deb version automatically, see https://github.com/wimpysworld/deb-get/pull/652#issuecomment-1306022386

**Comment by flexiondotorg** [comment]
There is no way to determine what the upstream published version is, therefore this can not be added to `deb-get`.
