### ISSUE TITLE
Personal Access Token question

### ISSUE THREAD

**Issue by SegaGameBoyStation** [wimpysworld/deb-get#660]
I am not sure what I am doing with this. I created a PAT and exported it as described on the main page of this repo.

Two qustions. How do I check if the token is applied?
How am I to set up the token for it to be useful for updating programmes from github?

**Comment by philclifford** [comment]
No worries - hopefully this helps.

Second question first:

You just need to have DEBGET_TOKEN in your environment set to the PAT.  The simplest way (for most linux users) is to add a line to `~/.profile` with

```
export DEBGET_TOKEN=WhateverYourTokenIs
```
This will ensure that from your next login it is available to all your shells and also in the environment of, for example, `Deborah`
For immediate use you can just type `export DEBGET_TOKEN=WhateverYourTokenIs` into your shell then use it as below or any `deb-get` operations until you `unset DEBGET_TOKEN`


Now your first question:

You can use their api to see  what your rate-limit is and how much you have used (without counting against the rate-limit), so for example either side of a `deb-get update` you should see the used number change (unless of course you've used the cache that `deb-get` maintains to reduce this problem for users without a PAT ) . 

The full details are here : https://docs.github.com/en/rest/rate-limit
but if you do this:

```shell
curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${DEBGET_TOKEN}" \
  https://api.github.com/rate_limit
```

you should get an informative response. If you don't have DEBGET_TOKEN set correctly you'll get
```json
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```
and if you omit the Authorization header you'll see the unauthenticated picture 

``shell
curl \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/rate_limit
```

Comparing the core resources, unauthenticated will be limited to 60 whereas authenticated will be 5000
