### ISSUE TITLE
Add Hakuneko-Nightly

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#68]
Hakuneko is a open source comic reader
They have a deb available from their website.
https://github.com/manga-download/hakuneko/releases/download/nightly-20200705.1/hakuneko-desktop_8.3.4_linux_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any daily/nightly, beta or pre-release software. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
