### ISSUE TITLE
Add Hakuneko-Stable

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#69]
Hakuneko is a open source comic reader
They have a deb available from their website.
https://github.com/manga-download/hakuneko/releases/download/v6.1.7/hakuneko-desktop_6.1.7_linux_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained/released. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)

**Comment by dtantono** [comment]
@flexiondotorg this one actively release https://github.com/wimpysworld/deb-get/issues/68
