### ISSUE TITLE
Add TLP UI

### ISSUE THREAD

**Issue by Anderhar** [wimpysworld/deb-get#690]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: TLP UI
 - Download URL: ppa:linuxuprising/apps (a third-party repo according to developer's own [instruction](https://github.com/d4nj1/TLPUI/wiki/Install-instructions#ubuntudebian-family))
 - Website URL: https://github.com/d4nj1/TLPUI
 - App Summary: A GTK user interface for [TLP](https://github.com/linrunner/TLP) written in Python

**Comment by flexiondotorg** [comment]
The project does not publish .deb packages
