### ISSUE TITLE
Add HopToDesk

### ISSUE THREAD

**Issue by sbstn87** [wimpysworld/deb-get#693]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: HopToDesk
 - Download URL: https://www.hoptodesk.com/
 - Website URL: https://www.hoptodesk.com/
 - App Summary: Free remote desktop software featuring true end-to-end encrypted traffic, file transfer, and live chat. HopToDesk is a free remote desktop tool allowing users to share their screen and allow remote control access to their computers and devices. Unlike other similar tools such as TeamViewer or AnyDesk, HopToDesk is free for both personal and business use, provides true end-to-end encryption for all peer communications, and open source.

**Comment by flexiondotorg** [comment]
There is no means to determine what the currently published upstream version is.
