### ISSUE TITLE
Add Double Commander

### ISSUE THREAD

**Issue by sbstn87** [wimpysworld/deb-get#699]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Double Commander
 - Download URL: https://sourceforge.net/p/doublecmd/wiki/Download/
 - Direct download URL: https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-qt
 - Website URL: https://doublecmd.sourceforge.io/
 - App Summary: Double Commander is a [free](https://www.gnu.org/philosophy/free-sw.html) cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.

**Comment by flexiondotorg** [comment]
The project does not publish .deb packages

**Comment by sbstn87** [comment]
They publish .deb packages for QT and GTK builds:

https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-qt

https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-gtk

**Comment by sbstn87** [comment]
Can this be reopened, because the .deb packages are available?
