### ISSUE TITLE
Please add Cisco WebEx client

### ISSUE THREAD

**Issue by charles-hood** [wimpysworld/deb-get#7]
uri="https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb" alt="Linux deb"

**Comment by flexiondotorg** [comment]
I don't think adding Webex is viable :disappointed: 

The `.deb` is only available via direct download, and the version number of the package is not available anywhere. Something `get-deb` requires so it knows when an update is available, by comparing the installed `.deb` with some vendor published version number on their website.

The other option is if Webex has an apt repository, but it does not. I've unpacked the `.deb` and it doesn't include any postinst scripts or cron jobs to setup an apt repository.

**Comment by charles-hood** [comment]
we know the version from examining the deb, It is currently 42.4.0.21893
![Screenshot from 2022-04-21 19-49-16](https://user-images.githubusercontent.com/16855550/164568934-6e2780a2-248f-4b5c-909e-fef4998f37b4.png)
If we update deb-get when the next version comes out, users will still know to update as the number will be higher

**Comment by charles-hood** [comment]
Would it be too much processing to read the version from the .deb file itself?

`ar p Webex.deb control.tar.gz | tar xzOf - ./control | grep Version`

![Screenshot from 2022-04-21 20-00-06](https://user-images.githubusercontent.com/16855550/164569710-eb5cde1f-1444-4bcf-aae1-f652eb2f3bec.png)

**Comment by charles-hood** [comment]
I think we could pattern it after the existing deb_gitkraken() function, except get the version from inside the .deb instead of the name

`function deb_gitkraken() {
    VERSION_PUBLISHED="$(curl -s "https://www.gitkraken.com/download/linux-deb" | grep "name: '" | cut -d"'" -f2)"
    URL="https://release.gitkraken.com/linux/gitkraken-amd64.deb"
    PRETTY_NAME="GitKraken"
    WEBSITE="https://www.gitkraken.com/invite/ieih1QR3"
}`

**Comment by charles-hood** [comment]
PR #8 submitted

**Comment by flexiondotorg** [comment]
Fixed via #8
