### ISSUE TITLE
Add Musikcube

### ISSUE THREAD

**Issue by dnet890** [wimpysworld/deb-get#70]
Musikcube is a open source CLI music player
They have a deb available from their website.
https://github.com/clangen/musikcube/releases/download/0.97.0/musikcube_standalone_0.97.0_x86_64.deb

**Comment by Xmetalfanx** [comment]
^ (noted on Github) another untested commit that addresses the issue but dont want to do a PR request unless the code seems ok to the team.

**Comment by natanjunges** [comment]
To test it, go in the terminal to the folder where you cloned the repository and run:
```bash
./deb-get install musikcube
```

**Comment by Xmetalfanx** [comment]
> To test it, go in the terminal to the folder where you cloned the repository and run:
> 
> ```shell
> ./deb-get install musikcube
> ```

thank you for the info
