### ISSUE TITLE
Exclude packages from installing

### ISSUE THREAD

**Issue by Marwe** [wimpysworld/deb-get#701]
## Exclude packages from installing/upgrading

Can certain packages be excluded from installing?
Any installed package seems to get upgrades, even if installed via package manager (example: pandoc).
I found that apt pinning does not work for direct binary package installs, holding does work, though, but keeps packages at certain versions (no upgrades at all).

```bash
apt-mark hold package
apt-mark showhold
```
Solutions would be:

* interaction, if package is installed and source is a standard repo (check for apt-cache policy origin?)
    * default keep
* whitelists, blacklists
* config options,
* cli parameters

Thank you very much for your efforts for this very efficient tool!

**Comment by flexiondotorg** [comment]
Sorry, this is not in the scope for the project.
