### ISSUE TITLE
Add Veracrypt

### ISSUE THREAD

**Issue by dombean** [wimpysworld/deb-get#703]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Veracrypt
 - Download URL: ppa:unit193/encryption
 - Website URL: https://www.veracrypt.fr/en/Downloads.html
 - App Summary: VeraCrypt is a free and open-source utility for on-the-fly encryption (OTFE).

**Comment by sbstn87** [comment]
Can you please add a .deb file fro the official website?

https://www.veracrypt.fr/en/Downloads.html

This will make it available for all Debian-based distros, not only Ubuntu.

**Comment by dombean** [comment]
Thanks @sbstn87 : As requested, I've changed the website from https://www.veracrypt.fr/en/Home.html to https://www.veracrypt.fr/en/Downloads.html -- in the Pull Request and Issue Description.

**Comment by philclifford** [comment]
Hi @dombean,  I think your change is not quite what @sbstn87 was asking for.  You're still using a PPA, which will only work for Ubuntu.  If you can change your PR to use the website page and parse the .deb download links out to get the correct URL based on distro, release and architecture and also get the version from the URL then it becomes available for the Debians as well as Ubuntus.  There's guidance in https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md#website-download and plenty of examples in 01-main from which to borrow.
