### ISSUE TITLE
Add PDFSam

### ISSUE THREAD

**Issue by Fuseteam** [wimpysworld/deb-get#710]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: pdfsam
 - Download URL: https://github.com/torakiki/pdfsam/releases/download/v4.3.4/pdfsam_4.3.4-1_amd64.deb
 - Website URL: https://pdfsam.org
 - App Summary: Split, merge, rotate, mix and extract pages from PDF files with PDFsam Basic, free and open source, at home or at work. Your PDF documents stay private on your computer, no need to upload them to a third party service.

**Comment by marosg42** [comment]
This package is already in Ubuntu repositories, is it still eligible?

**Comment by philclifford** [comment]
4.2.12 in the LTS vs 5.0.3 direct from upstream. I'd think that complies with https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md#what-is-acceptable .
