### ISSUE TITLE
New release - when? 

### ISSUE THREAD

**Issue by abacao** [wimpysworld/deb-get#723]
Hello @flexiondotorg 

When can a new version of deb-get be released?

There were some improvements between the v0.3.6 and the current time-and-date.

Suggestion: create a github action that do a build every couple of weeks.

**Comment by abacao** [comment]
I'm trying on my fork. I will contribute if I reach some success.
Meanwhile, can we get a new release?
Please?

**Comment by Fuseteam** [comment]
i would love that as well!

**Comment by flexiondotorg** [comment]
When it is ready :smiley:

**Comment by Fuseteam** [comment]
for posterity [according to the stream](https://www.youtube.com/watch?v=y2RZQpIy1sg) there is a massive release blocker: the caching is too aggressive atm
