### ISSUE TITLE
Spotify-client package signing key has changed

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#730]
https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg has replaced https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg

If the key is not updated we get apt errors:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7A3A762FAFD4A51F
W: Failed to fetch http://repository.spotify.com/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7A3A762FAFD4A51F
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

To overcome the catch-22 users with `deb-get`-installed `spotify-client` could to this:

```
 curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/spotify-client-archive-keyring.gpg
```

**Comment by philclifford** [comment]
Hi @stankovictab ,  this error says you have two entries that have different signing key info for the one repo.  You can find them like this :
```bash
grep spotify /etc/apt/sources.list.d/*.list
/etc/apt/sources.list.d/spotify-client.list:deb [signed-by=/usr/share/keyrings/spotify-client-archive-keyring.gpg] http://repository.spotify.com stable non-free
```
But you should see two lines with another pointing to a different key location.  You need to move or delete that extra file.  Then `sudo apt update` should complete without errors.

**Comment by stankovictab** [comment]
Yup, that did the trick, for some reason I had both `spotify` and `spotify-client` in there, 
just removed the `spotify` one and the problem is gone. 
Thanks a lot!
