### ISSUE TITLE
Neurontube

### ISSUE THREAD

**Issue by rauldipeas** [wimpysworld/deb-get#732]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Neurontube
 - Download URL: https://audiosingularity.com/product/neurontube-debut
 - Website URL: https://audiosingularity.com/product/neurontube-debut
 - App Summary: Guitar effects VST plugin.

**Comment by philclifford** [comment]
Looks interesting, but as the download is behind a registration login it is not possible to support this software in `deb-get` .
