### ISSUE TITLE
Add apt repo definition option to fetch keyID directly

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#738]
Where a key is not otherwise readily available but the signing ID is we could maybe support direct 
```
${ELEVATE} gpg --no-default-keyring --keyring /usr/share/keyrings/${APP}-archive-keyring.gpg --keyserver keyserver.ubuntu.com --recv ${APT_KEY_ID}
```

_Originally posted by @philclifford in https://github.com/wimpysworld/deb-get/issues/731#issuecomment-1418247588_

**Comment by KlfJoat** [comment]
I cobbled together my own `deb-get`-like system over the last 4 years in my ignorance of this project. And this functionality is the main piece that `deb-get` is missing compared to mine.

If this gets implemented, I'll switch to `deb-get` and add my software that's not already included.

**Comment by philclifford** [comment]
@KlfJoat keep an eye on the status of PR 741 :-)
