### ISSUE TITLE
Add Sunshine!

### ISSUE THREAD

**Issue by Constancies** [wimpysworld/deb-get#739]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [CHECK!] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Sunshine
 - Download URL: https://github.com/LizardByte/Sunshine/releases/download/v0.18.1/sunshine-ubuntu-22.04-amd64.deb
 - Website URL: https://github.com/LizardByte/Sunshine
 - App Summary: Sunshine is a self-hosted game stream host for Moonlight offering low latency cloud gaming server capabilities with support for AMD, Intel, and Nvidia GPUs for hardware encoding.

I would like to note that the `.deb` options for this app are Ubuntu 20.04 and 22.04 specific packages, plus ARM variants (I linked the 22.04 amd64 edition). How should something like this be handled? Just ship 22.04?

**Comment by philclifford** [comment]
Already supported since https://github.com/wimpysworld/deb-get/commit/f55b8c93441f5c660798388c9198ae04e4436c88
