### ISSUE TITLE
Add VirtScreen

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#75]
Virtscreen is a open source application that Make your iPad/tablet/computer as a secondary monitor on Linux.
They have a deb available from their website.
https://github.com/kbumsik/VirtScreen/releases/download/0.3.1/virtscreen.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained/released. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
