### ISSUE TITLE
Missing required information on Raspberry Pi

### ISSUE THREAD

**Issue by OMEGARAZER** [wimpysworld/deb-get#752]
### Expected behavior

No errors, not seeing download info for 01-main.repo update
(The download part is also seen on my ubuntu 22.04.01 machine but does not get the error related to agena)

### Actual behavior

```
  [!] ERROR! Missing required information of website package agena:
URL=
VERSION_PUBLISHED=
```

### Steps to reproduce

update to 0.3.7 on Raspberry Pi running Debian 11 (5.15.84-v8+ aarch64)

#### /etc/os-release

```bash
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### /etc/lsb-release

```bash
cat: /etc/lsb-release: No such file or directory
```

#### deb-get version

```bash
0.3.7
```

### deb-get update

```bash
  [+] Updating /etc/deb-get/01-main
/etc/deb-get/01-main.repo                            100%[===================================================================================================================>]   2.70K  --.-KB/s    in 0s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  102k    0  102k    0     0   211k      0 --:--:-- --:--:-- --:--:-- 1148k
/var/cache/deb-get
  [+] Updating cache of supported apps in the background
  [!] ERROR! Missing required information of website package agena:
URL=
VERSION_PUBLISHED=
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://download.docker.com/linux/debian bullseye InRelease
Hit:5 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:6 https://deb.nodesource.com/node_19.x bullseye InRelease
Fetched 4,775 B in 2s (2,471 B/s)
Reading package lists...
```

**Comment by OMEGARAZER** [comment]
Some additional info if it helps. When attempting to see if it was something on my end causing the issue I tried a `deb-get clean`  which caused the following `deb-get update` attempts to complain about empty cache files. I wasn't able to resolve that till removing the agena.html file from the /var/cache/deb-get directory and running `deb-get fix-installed`.

Since then the updates are working correctly except for the reported error.

**Comment by philclifford** [comment]
We need to enable Pi users to get to the right file. Their naming looks a little unhelpful : 

```shell
grep '.*\.deb\"' /var/cache/deb-get/agena.html 
      <td style="text-align: center; vertical-align: middle;"><a href="http://downloads.sourceforge.net/agena/agena-2.36.2-linux.i386.deb"><img style="border: 0px solid ; width: 24px; height: 24px;" alt="Download x86 Linux Debian 32-bit installer" src="bitmaps/downloadbinary.png"></a></td>
      <td style="text-align: center; vertical-align: middle;"><a href="http://downloads.sourceforge.net/agena/agena-2.36.2-linux.amd64.deb"><img style="border: 0px solid ; width: 24px; height: 24px;" alt="Download x64 Linux Debian 64-bit installer" src="bitmaps/downloadbinary.png"></a></td>
      <td style="text-align: center; vertical-align: middle;"><a href="http://downloads.sourceforge.net/agena/agena-2.34.5-raspi.stretch.armv6-32.deb"><img style="border: 0px solid ; width: 24px; height: 24px;" alt="Download Raspberry Pi ARM 32-bit installer" src="bitmaps/downloadbinary.png"></a></td>
      <td style="text-align: center; vertical-align: middle;"><a href="http://downloads.sourceforge.net/agena/agena-2.34.5-raspi.stretch.armv8-64.deb"><img style="border: 0px solid ; width: 24px; height: 24px;" alt="Download Raspberry Pi ARM 64-bit installer" src="bitmaps/downloadbinary.png"></a></td>
```

I guess you'll be wanting ` http://downloads.sourceforge.net/agena/agena-2.34.5-raspi.stretch.armv8-64.deb` , but as you're running `Debian` that may be wrong .. 

If you copy /etc/deb-get/01-main.d/agena into  /etc/deb-get/99-local.d/  you can possibly get to a solution that works for everyone. 
Can you provide the output of : 
 * `uname -m`
 *  `dpkg --print-architecture`
 *  `lsb-release --id --short`

Then we'll need to map your data into the correct/best URL ....

**Comment by OMEGARAZER** [comment]
```
uname -m
aarch64
```
```
dpkg --print-architecture
arm64
```
lsb-release command isn't found.

I imagine the bottom two would be for anyone looking to install this app depending on if they're running 32 or 64-bit.

**Comment by cobalt2727** [comment]
> lsb-release command isn't found.

`sudo apt install lsb-release && lsb-release --id --short`

**Comment by OMEGARAZER** [comment]
```
lsb_release --id --short
Debian
```

**Comment by philclifford** [comment]
OK this might work:
put the following into `/etc/deb-get/99-local.d/agena`
(you might need to create the directory )

```shell
"DEFVER=1
ARCHS_SUPPORTED="amd64 i386 arm64 arm32"
local TARGET_ARCH="xxx"

# Handle raspi jankily
case ${HOST_ARCH} in
    arm64|armv8-64|armv8)
        TARGET_ARCH=armv8-64;;
    arm32|armv6-32|armv6)
        TARGET_ARCH=armv8-64;;
    *)
        TARGET_ARCH=${HOST_ARCH};;
esac

WEBSITE="https://agena.sourceforge.net/"
get_website "${WEBSITE}/download.html"
if [ "${ACTION}" != "prettylist" ]; then
    local REDIR_URL="$(grep -o "[^\"]*/${APP}/.*${TARGET_ARCH}\.deb" "${CACHE_FILE}")"
    URL=$(unroll_url "${REDIR_URL}")
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'-' -f2)"
fi
PRETTY_NAME="Agena"
SUMMARY="Agena is an easy-to-learn procedural programming language designed to be used in science, scripting, and many other applications"
```

**Comment by philclifford** [comment]
If you then do `deb-get show agena` you should see : 

```deb-get show agena
  [*] WARNING! Conflict detected, duplicate declaration of package agena, using declaration from 99-local
  [!] Duplicate entr(ies) already merged upstream (if no longer needed), must be manually removed from your /etc/deb-get/99-local.d folder.
  [+] Including local package agena
  [ ... ]
  [!] Please consider contributing back new entries, an issue (or raise a PR) directly at https://github.com/wimpysworld/deb-get/pulls
Agena
  Package:	agena
  Repository:	99-local
  Updater:	deb-get
  Installed:	No
  Published:	2.34.5
  Architecture:	amd64 i386 arm64 arm32
  Download:	http://master.dl.sourceforge.net/project/agena/Binaries/Legacy/agena-2.34.5-raspi.stretch.armv8-64.deb?viasf=1
  Website:	https://agena.sourceforge.net/
  Summary:	Agena is an easy-to-learn procedural programming language designed to be used in science, scripting, and many other applications
```

**Comment by OMEGARAZER** [comment]
> put the following into `/etc/deb-get/99-local.d/agena`

So, I did that to test to see if the error is gone and now it's just been replaced by android-messages-desktop

```
  [!] ERROR! Missing required information of github package android-messages-desktop:
URL=
VERSION_PUBLISHED=
```

Seems it may be a deeper issue than just agena.

I'll have to roll my pi back to .6 and keep an eye on this.

**Comment by philclifford** [comment]
There is no arm release for `android-messages-desktop`.  That seems to point to the root cause being a failure to respect the supported architecture (which should default to `amd64` )

**Comment by OMEGARAZER** [comment]
So, figured I'd try to dig into this to see what I could find.

What seems to be happening is in the validate_deb call from [here](https://github.com/wimpysworld/deb-get/blob/main/deb-get#L538) the process is killed at [this check](https://github.com/wimpysworld/deb-get/blob/main/deb-get#L472-L474) because the archs_supported isn't checked till after validate_deb is completed and it just sees that the information is missing and bails. Adding the check there lets the process complete and go back to what seems to be normal.

After that update the supported_apps.list on the pi contains
<details><summary>supported_apps.list</summary>
appimagelauncher

bat
chronograf
codium
cosign
deb-get
docker-ce
influxdb
influxdb2
influxdb2-cli
jellyfin
kapacitor
lsd
lutris
mergerfs
min
minigalaxy
minikube
mullvad-vpn
nala-legacy
nordvpn
obs-cli
onedriver
pandoc
plexmediaserver
plow
rclone
standard-notes
syft
system-monitoring-center
teams-for-linux
telegraf
trivy
vivaldi-stable
vuescan
zettlr
</details>

I haven't confirmed if that list is correct or not (I only use 5 and they're all there though).
I'm going to test the change on my Ubuntu install to make sure it doesn't break anything there and if not I can toss a PR up with the change.
