### ISSUE TITLE
Add Evernote 

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#76]
Evernote is popular note taking application
They have a deb available from their website.
https://cdn1.evernote.com/boron/linux/builds/Evernote-Beta-10.35.3-linux-ddl-beta-3355-f684e12257.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that provides a reliable way to dynamically determine the current published version. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
