### ISSUE TITLE
Make an exception/rules which app needed for update

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#761]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior
I have one app called Sunshine that is broke on recent update. So, I need to downgrade it and it will be better if I can make parameters which app needed to be updated to recent version 

### Actual behavior
recent release on Sunshine broke the application

### Steps to reproduce

sudo deb-get upgrade and when upgrade all apps to the recent release.  specific app does not worked

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


```

#### /etc/lsb-release

```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

```

#### deb-get version

```bash
deb-get version
```

### deb-get update

```bash
deb-get update
```

**Comment by philclifford** [comment]
Hi @dtantono , thanks for letting us know. I suspect a broken upstream release is not the root of the problem.  The definition for sunshine needs tightening up.  If you put the following into `/etc/deb-get/99-local.d/sunshine` it will override the definition and can confirm if my guess is correct:

```bash
DEFVER=1
ARCHS_SUPPORTED="amd64 arm64"
CODENAMES_SUPPORTED="bullseye focal jammy"
SUNSHINE_RELEASE="${UPSTREAM_RELEASE}"
if [ "${UPSTREAM_ID}" == debian ]; then
    SUNSHINE_RELEASE=$UPSTREAM_CODENAME
fi
get_github_releases "LizardByte/Sunshine" # "latest"
if [ "${ACTION}" != "prettylist" ]; then
    URL=$(grep "browser_download_url.*-${UPSTREAM_ID}-${UPSTREAM_RELEASE}-${HOST_ARCH}\.deb\"" "${CACHE_FILE}" |grep -v -e 'nightly-dev' |head -1 |cut -d'"' -f4)
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f8 | sed 's|^v||')"
fi
PRETTY_NAME="Sunshine"
WEBSITE="https://docs.lizardbyte.dev/projects/sunshine/"
SUMMARY="Sunshine is a Gamestream host for Moonlight."
```

You may have been getting the arm or debian .deb ....

If you really need to skip a version you could then edit the above and add the version you **don't** want to the list of `grep -v ` expressions - so something like  ` ... | grep -v -e 'nightly-dev' -e '0.18.1' | ...`

Hope that helps.  Please let me know if it works for you as I'll be putting the above in a PR shortly.

**Comment by philclifford** [comment]
@dtantono it would be useful to see a  `deb-get show sunshine` before and after putting the local override in place.

**Comment by dtantono** [comment]
noted for that. that exception workaround is just skipping certain version and then if newer version comes up, then it will download newer version right? Just for future reference,  Is it possible to exclude an app from the future updates on deb-get update list?

**Comment by philclifford** [comment]
The raison d'etre of `deb-get` is to follow new upstream releases and keep up-to-date.  If you put an exception workaround in place as above then the next newer release will be picked up.  If you need to downgrade you might need to re-install to get there. If you find a release is broken you can let upstream know and get them to fix it or withdraw it, or make a local interim override as above (and ideally let us know so we can assess if we need to put an exclusion in place).

It is not possible to exclude an app that way (you could add a feature request for that by all means but ..).  I cannot think of a simple way of achieving that off the top of my head, except to say for apps using apt repos or PPAs the standard pinning mechanisms of apt should still work.   A local "exclude these apps from update" list would be a possible but non-trivial enhancement.

**Comment by philclifford** [comment]
Apt pinning : https://help.ubuntu.com/community/PinningHowto
`sudo apt-mark hold <package_name>`

**Comment by dtantono** [comment]
thank you it works
