### ISSUE TITLE
deb-get missing information of github package deborah

### ISSUE THREAD

**Issue by p4p4j0hn** [wimpysworld/deb-get#763]
### Expected behavior
`deb-get update` succeeds in updating the entire catalog.

### Actual behavior

`deb-get update` fails to update the cache for anything past "deb-get" except for lutris and neovim which I had already installed manually from other sources. 

Error Message:
```bash
[!] ERROR! Missing required information of github package deborah:
URL=
VERSION_PUBLISHED=
```
#### Output of `ls -l /var/cache/deb-get`
```bash
total 10248
-rw-r--r-- 1 root root   13395 Feb 14 19:14 agena.html
-rw-r--r-- 1 root root   33240 Feb 14 19:14 android-messages-desktop.json
-rw-r--r-- 1 root root  249694 Feb 14 19:15 antimicrox.json
-rw-r--r-- 1 root root  635637 Feb 14 19:15 appimagelauncher.json
-rw-r--r-- 1 root root    3947 Feb 14 19:15 azuredatastudio.json
-rw-r--r-- 1 root root  871900 Feb 14 19:15 balena-etcher-electron.json
-rw-r--r-- 1 root root   33687 Feb 14 19:15 bat.json
-rw-r--r-- 1 root root    6323 Feb 14 19:15 battery-monitor.json
-rw-r--r-- 1 root root   48866 Feb 14 19:15 beersmith3.html
-rw-r--r-- 1 root root  621056 Feb 14 19:14 bitwarden.json
-rw-r--r-- 1 root root   22173 Feb 14 19:15 bitwig-studio.html
-rw-r--r-- 1 root root   31616 Feb 14 19:15 blockbench.json
-rw-r--r-- 1 root root   93311 Feb 14 19:15 bluejeans-v2.html
-rw-r--r-- 1 root root   49658 Feb 14 19:15 bottom.json
-rw-r--r-- 1 root root   29404 Feb 14 19:15 brisqi.json
-rw-r--r-- 1 root root  702497 Feb 14 19:15 caprine.json
-rw-r--r-- 1 root root 6146359 Feb 14 19:15 codium.json
-rw-r--r-- 1 root root  203702 Feb 14 19:15 com.github.tkashkin.gamehub.json
-rw-r--r-- 1 root root  235821 Feb 14 19:15 cosign.json
-rw-r--r-- 1 root root   45151 Feb 14 19:15 croc.json
-rw-r--r-- 1 root root   25360 Feb 14 19:15 cronopete.html
-rw-r--r-- 1 root root    4852 Feb 14 19:14 crossover.html
-rw-r--r-- 1 root root   15550 Feb 14 19:15 dbeaver-ce.html
-rw-r--r-- 1 root root    8012 Feb 14 19:15 deadbeef-static.html
-rw-r--r-- 1 root root  129242 Feb 14 19:15 deb-get.json
-rw-r--r-- 1 root root   91702 Feb 14 19:15 deborah.json
-rw-r--r-- 1 root root   37346 Feb 14 19:15 gh.json
-rw-r--r-- 1 root root    4182 Feb 14 19:15 lutris.json
-rw-r--r-- 1 root root   29714 Feb 14 19:15 neovim.json
-rw-r--r-- 1 root root     345 Feb 14 19:40 supported_apps.list
-rw-r--r-- 1 root root     496 Feb 14 19:40 supported.list
```

### Steps to reproduce

Performed a `deb-get update` then a `deb-get upgrade` 

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### /etc/lsb-release

```bash
cat: /etc/lsb-release: No such file or directory
```

#### deb-get version

```bash
0.3.7
```

### deb-get update

```bash
  [+] Updating /etc/deb-get/01-main
/etc/deb-get/01-main.repo               100%[=============================================================================>]   2.70K  --.-KB/s    in 0s      
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  102k  100  102k    0     0   111k      0 --:--:-- --:--:-- --:--:--  111k
/etc/apt/sources.list.d
  [+] Updating cache of supported apps in the background
Hit:1 http://mirror.it.ubc.ca/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://mirror.it.ubc.ca/debian bullseye-updates InRelease
Hit:4 http://mirror.it.ubc.ca/debian bullseye-backports InRelease
Hit:5 https://repo.steampowered.com/steam stable InRelease
Hit:6 https://dl.winehq.org/wine-builds/debian bullseye InRelease
Hit:7 https://packages.microsoft.com/repos/vscode stable InRelease
Get:8 https://pkgs.tailscale.com/stable/debian bullseye InRelease
Ign:9 https://proget.makedeb.org makedeb InRelease
Hit:10 https://brinkervii.gitlab.io/grapejuice/repositories/debian universal InRelease
Hit:11 https://apt.benthetechguy.net/debian bullseye InRelease
Hit:12 https://apt.calenhad.com/debian bullseye InRelease
Hit:13 https://deb.librewolf.net bullseye InRelease
Ign:14 https://proget.makedeb.org prebuilt-mpr InRelease
Get:15 https://proget.makedeb.org makedeb Release [7,608 B]
Get:16 https://proget.makedeb.org prebuilt-mpr Release [3,494 B]
Fetched 17.1 kB in 2s (9,277 B/s)
Reading package lists...  [!] ERROR! Missing required information of github package deborah:
URL=
VERSION_PUBLISHED=

  [+] neovim (0.4.4-1) has an update pending. 0.8.3 is available.
```

**Comment by philclifford** [comment]
This is related to (and may be fixed by ) #756 if my codename checking suggestion is included there or separately.
Of course the other fix is for @ymauray to make debian releases as well as ubuntu ones, but that's not a general solution to the general problem.

**Comment by p4p4j0hn** [comment]
Thank you @philclifford that's a great fix! I'll try it out.

**Comment by philclifford** [comment]
Strange:  I just did an update ( using 0.3.7 on ubuntu) and had a package "fail" but the `update` completed in spite of the error and the `upgrade` was successful.  I'll see if I can replicate on debian 11.
(Sadly the package "fail" was transient while upstream was releasing so I'll also need to manufacture a "fail" but that's already in the armoury so ... )

**Comment by philclifford** [comment]
BTW: ( for anyone playing along )

-  you can `export DEBGET_CACHE_RTN=1` to reduce the cache live time to a minute or put it up above the default 60 .(e.g. `export DEBGET_CACHE_RTN=240` for when you don't want to update the cache but are banging away at a 99-local.d override until  `show` and `update` look good enough)  
- `deb-get cache` will list the cache directory
- `deb-get clean` will clear out the cache (sometimes helpful but shouldn't be needed normally and removes useful diagnostics when troubleshooting so at least save the output of  `deb-get cache` and maybe save a copy of relevant cache files and `deb-get show <app> [<app>] `  before a `clean`

**Comment by philclifford** [comment]
OK, I think after a bit of playing around on debian and I may have a fix for this (and related unsupported arch behaviour) :point_up: 
@p4p4j0hn the only other thing I needed for this to be working for me was to clear out any PPA repos that I'd managed to get into `/etc/apt/sources.list.d/*list` (I had a firefox-esr entry in there which caused me problems).  Hopefully this will work better for you too.

**Comment by p4p4j0hn** [comment]
@philclifford It updates the cache beautifully on Debian 11 with this PR. Great work! :100: Hope this makes it in soon.

**Comment by Xdavius** [comment]
> BTW: ( for anyone playing along )
> 
> * you can `export DEBGET_CACHE_RTN=1` to reduce the cache live time to a minute or put it up above the default 60 .(e.g. `export DEBGET_CACHE_RTN=240` for when you don't want to update the cache but are banging away at a 99-local.d override until  `show` and `update` look good enough)
> * `deb-get cache` will list the cache directory
> * `deb-get clean` will clear out the cache (sometimes helpful but shouldn't be needed normally and removes useful diagnostics when troubleshooting so at least save the output of  `deb-get cache` and maybe save a copy of relevant cache files and `deb-get show <app> [<app>] `  before a `clean`

Hi,

This trick works for me. This must be integrated in the normal release of deb-get. I don't understand why deborah is downloaded in cache and, the file broken too.

Here using Debian 12.
