### ISSUE TITLE
Add tachidesk-JUI

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#764]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name:Tachidesk-JUI
 - Download URL:https://github.com/Suwayomi/Tachidesk-JUI/releases/download/v1.3.2/tachidesk-jui_1.3.2-1_amd64.deb
 - Website URL:https://github.com/Suwayomi/Tachidesk-JUI
 - App Summary:Application to download comics

**Comment by philclifford** [comment]
From the project README : " Keep in mind that Tachidesk-JUI and Tachidesk-Server are alpha software"
Therefore this does not accord with the [Acceptable Contribution Criteria](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md#adding-software) so this will be closed until there is a stable production release.
