### ISSUE TITLE
Add Tusk

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#77]
Tusk is a open source unofficial evernote client
They have a deb available from their website.
https://github.com/klaussinani/tusk/releases/download/v0.23.0/tusk_0.23.0_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained/released. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
