### ISSUE TITLE
deb-get 0.3.7-1 cannot list installed apps and install new application

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#776]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

it should install new application and list installed application 

### Actual behavior

![image](https://user-images.githubusercontent.com/29157187/220819906-2fc3d9a2-45f7-4dc8-bf16-c83ddd8f4a6c.png)

![image](https://user-images.githubusercontent.com/29157187/220819955-ed5d3e65-5cc1-4623-b667-5c7317f1d43a.png)

### Steps to reproduce

type:
sudo deb-get install google-chrome-stable
deb-get install google-chrome-stable
and it does not worked

### System information

Run the following a paste the output below:

#### /etc/os-release

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

#### /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

#### deb-get version

```bash
deb-get version
```

### deb-get update

```bash
deb-get update
```
BTW, my current workaround is I downgrade it to 0.3.6-1 and it could do these commands properly.

**Comment by RichAyotte** [comment]
Issue confirmed.

`sudo deb-get list` outputs a truncated list. Here's what I'm seeing.

```bash
❯ sudo deb-get list
1password                       [ installed ]
agena
android-messages-desktop
antimicrox
anydesk
appimagelauncher
atom
azure-cli
azuredatastudio
balena-etcher-electron
bat                             [ installed ]
bitwarden
bitwig-studio
blockbench
bluejeans-v2
bottom
brave-browser
brisqi
caprine
cawbird
chronograf
code
codium
com.github.tkashkin.gamehub
cosign
croc
crossover
dbeaver-ce
deadbeef-static
deb-get                         [ installed ]
```

**Comment by RichAyotte** [comment]
Oddly enough, `deb-get prettylist` does not truncate the list.

**Comment by RichAyotte** [comment]
Not sure if this is related but I can no longer install obs studio on my Debian system.

`sudo deb-get install obs-studio`

```bash
❯ sudo deb-get install obs-studio
  [!] ERROR! obs-studio cannot be installed as PPAs are not supported on distros that are not derived from Ubuntu.
```

This is something that I was able to do with a previous version.

**Comment by dtantono** [comment]
yeah But, it is not on stable release yet
