### ISSUE TITLE
Updates official packages to third party and adds third party repos

### ISSUE THREAD

**Issue by eight85** [wimpysworld/deb-get#777]
This program can't tell the difference between your official packages and the third party ones on github. This is not desirable as you could just install a couple of deb files from github and its default behavior tries to update your other official packages from PPAs.

 Example: You could add the official OBS ppa and install it as normal. Then you decide to install a couple of github deb packages like google chrome. When you attempt to update your exisiting packages. Deb-get will attempt to update OBS to different version and add a third party repo. In this case the following ppa was added https://launchpad.net/~flexiondotorg/+archive/ubuntu/obs-fully-loaded

This needs to be addressed as it starts making a security concern. I have no issues with people hosting third party packages and their respected repos. Only if the user chooses todo so and not forced on the user. This project gets alot of attention from social media influencers in the open source community. I urge you to remedy this situation

**Comment by philclifford** [comment]
You are mistaken.
