### ISSUE TITLE
Add multibootusb

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#78]
Multibootusb is multiple ISO creator for USB drives
They have a deb available from their website.
https://sourceforge.net/projects/multibootusb/

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained/released. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
