### ISSUE TITLE
Add Flemozi

### ISSUE THREAD

**Issue by sbstn87** [wimpysworld/deb-get#804]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Flemozi
 - Download URL: https://github.com/KRTirtho/flemozi/releases
 - Website URL: https://github.com/KRTirtho/flemozi
 - App Summary: A simple, fast and lightweight emoji picker for desktop operating systems. Not Electron based.

**Comment by philclifford** [comment]
Once there is a fix for https://github.com/KRTirtho/flemozi/issues/3 and the released deb can be installed ...
