### ISSUE TITLE
Add Lightworks

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#81]
Lightworks is professional video editing suite
They have a deb available from their website.
https://cdn.lwks.com/releases/2022.1.1/lightworks_2022.1.1_r132185.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that provides a reliable way to dynamically determine the current published version. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
