### ISSUE TITLE
Add code-insiders

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#812]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: code-insiders
 - Download URL: https://packages.microsoft.com/repos/vscode stable main
 - Website URL: https://code.visualstudio.com/
 - App Summary: Code editing. Redefined. Insider Edition

Discussing this in #810 it is occurred to me that we ought to support `code-insiders` as well because otherwise we risk a user installing it with `apt` and then `deb-get remove code` will currently remove the apt repo configs, leaving the insiders build orphaned and no longer updated.

**Comment by flexiondotorg** [comment]
Including pre-release software in deb-get is out of scope for the project.
