### ISSUE TITLE
Package request: TL Legacy 

### ISSUE THREAD

**Issue by Adithyan007hack** [wimpysworld/deb-get#815]
- [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: TL Legacy 
 - Download URL: https://tlaun.ch/ubuntu
 - Website URL: https://tlaun.ch/
 - App Summary: Minecraft launcher , Stable, fast and simple

**Comment by philclifford** [comment]
Sorry, they do not provide an easy way to determine available version, plus looking at the website this _may_  not be a legitimate application so for both those reasons it will not be supported.
