### ISSUE TITLE
Add Open3D

### ISSUE THREAD

**Issue by brccabral** [wimpysworld/deb-get#818]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Open3D
 - Download URL: https://github.com/isl-org/Open3D/releases
 - Website URL: http://www.open3d.org/
 - App Summary: 3D models visualization

**Comment by philclifford** [comment]
The only deb on the github releases is the viewer app, which depends on the python wheel so without that all being also being deb packaged with each release I think supporting this is not appropriate.

**Comment by brccabral** [comment]
That's a bummer, thanks for checking
