### ISSUE TITLE
Add Google-Keep

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#82]
This is unofficial Google Keep client
They have a deb available from their website.
https://github.com/andrepolischuk/keep/releases/download/v0.1.10/keep_0.1.10_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained/released. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
