### ISSUE TITLE
Please add support for 23.04 Lunar Lobster

### ISSUE THREAD

**Issue by lproven** [wimpysworld/deb-get#823]
New feature? `deb-get` is giving me errors on my Lunar boxes, saying it's not a derivative of Debian or Ubuntu.

**Comment by philclifford** [comment]
That would be a bug not a feature. Alas I cannot replicate here.


please supply some information about boxes where it is failing (per the bug issue template) (`lsb-release -a ; cat /etc/os-release; deb-get version`) , details of what is "failing" and relevant output ...


![image](https://user-images.githubusercontent.com/8797027/235350086-41c93613-985d-49c4-9fe0-c0cde03728f7.png)

**Comment by lproven** [comment]
Sure.

> `root@Latitude-5420:/home/lproven# deb-get upgrade`
> `[!] ERROR! Ubuntu Lunar is not supported because it is not derived from a supported Debian or Ubuntu release.`

**Comment by lproven** [comment]
````
root@Latitude-5420:/home/lproven# apt upgrade deb-get
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
deb-get is already the newest version (0.3.6-1).
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

````

**Comment by philclifford** [comment]
Thanks @lproven : could you try `deb-get update; deb-get install deb-get` ?
Failing that the self-install line from the Readme should work (it put deb-get on a clean lunar VM for me so ...)

```
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
```

or if you are a good person who doesn't pipe the internet to `sudo` then download and `sudo apt install ./deb-get_0.3.8-1_all.deb` 

Your 0.3.6 is clearly not the newest, but then apt wouldn't know as it was not installed from an apt repo ...

**Comment by lproven** [comment]
> Failing that the self-install line from the Readme should work

That did it and it's now working. Thank you very much!

Now, about the Waterfox browser... ;-) (bug #799)

**Comment by lproven** [comment]
Fixed, closing
