### ISSUE TITLE
deb-get update and deb-get list does not show installed package (0.3.8)

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#826]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior
it should show list of the installed packages and update it properly

### Actual behavior
it shows nothing

### Steps to reproduce

sudo deb-get update and update does not work as intended

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


```

#### /etc/lsb-release

```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

```

#### deb-get version

```bash
deb-get version
```

### deb-get update

```bash
deb-get update
```
![image](https://user-images.githubusercontent.com/29157187/236428121-6e2bca2c-e6d2-422a-b152-8c9308c057f5.png)

**Comment by philclifford** [comment]
don't `sudo deb-get` (we need to catch that - it breaks things! )

Presumably `/etc/deb-get/installed` has only `deb-get 1 github` in now...
Any hint as to how/when that happened, or does it list other apps?

**Comment by dtantono** [comment]
Thanks for your reply and here are my answers
1. I just type sudo apt install curl lsb-release wget
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get to upgrade my previous deb-get and then yeah. suddenly, the problems happened
2. I checked on /etc/deb-get/installed and then this problem happens
What do you think?
![2023-05-05_22-36](https://user-images.githubusercontent.com/29157187/236472929-7d36dfad-7e87-4fc7-8584-08bd54ea8c48.png)

**Comment by philclifford** [comment]
What you did should not have overwritten `/etc/deb-get/installed`  so I'll take a look at that to make sure it is behaving reasonably or fix it.  I presume your `/etc/deb-get/aptrepos`  is also empty.

Upgrading `deb-get` if you have it installed should just happen normally with `deb-get update ;deb-get upgrade` .  If the old version is failing to `update`  and a newer release is available then `deb-get install deb-get`   should get the newer version. You should not run the self-install script from the README.md again (although I'm pretty sure that should not wipe out the installed list and also that I have done it myself installing the latest `deb-get` on 22.04 and 22.10 without such problems - I'll check again later ...)

Meanwhile to recover the position of the files in `/etc/deb-get` here's how you could proceed.

If you only had a few apps installed with `deb-get`  and can remember them just doing `deb-get install` should re-add them to `/etc/deb-get/installed` etc. and get you back on track.  If you had more and/or cannot remember then for the most part you can use `apt`, `dpkg`  and `deb-get` to get an idea of what should be installed with something like this: 

```bash

# These apps are supported by deb-get 

for app in $(deb-get csvlist |grep -v -e apt -e ppa | cut -d\" -f2 ) ; do  apt-cache policy ${app} |grep -e ${app} -e 'Installed' |tee -a /tmp/deb-installed-check;done
# ones that have been installed directly from debs (e.g. from github of direct download from upstream) will have an installed version rather than "(none)"


# Next we look for configured app repo lists matching apps ..

for app in $(deb-get csvlist |grep -e apt -e ppa | cut -d\" -f2 ) ; do if [ -f /etc/apt/sources.list.d/${app}.list ] ; then echo ${app} |tee -a /tmp/app-aptlist-present; fi;done

```

You can then `deb-get show ... `  ( or `deb-get install ...` )  from the  `/tmp/app-aptlist-present` with something like  `deb-get show $(cat /tmp/app-aptlist-present)` and get a list from the list directly installed from debs

```
sed  '/\(none\)/d' /tmp/deb-installed-check |grep -B1 Installed|grep '^[a-z,0-9]' |tr -d ':'
```



You might still need to check for shared repositories with ( e.g. `glow`,  the `winehq-{stable,devel,staging}`  variants  etc.)

You also need to take care with the above as they may offer to have  `deb-get` adopt apps you installed from the main distro repositories, which is useful if you want to do that, but could be annoying if you don't.

**Comment by dtantono** [comment]
Hi
Thanks for your reply and here are my answers:
1. I checked on /etc/deb-get/aptrepos and the lists are still intact
![2023-05-08_08-24](https://user-images.githubusercontent.com/29157187/236707813-08c653f1-a914-4be7-95ab-114bce1d3203.png)
![2023-05-08_08-20](https://user-images.githubusercontent.com/29157187/236707834-babd900b-2ada-477d-ae4f-5263199e94dd.png)

3. You mentioned that the workaround is just reinstall it back. But, it does not work  and it just show me it is not supported. What do you think?
![image](https://user-images.githubusercontent.com/29157187/236707848-47cf5c94-3b90-4c58-8ee6-5f56cbd330b9.png)

**Comment by philclifford** [comment]
Hmmm - that looks like you don't have `/etc/deb-get/01-main.repo` available 
```
head -1 /etc/deb-get/01-main.repo 
https://raw.githubusercontent.com/wimpysworld/deb-get/main/01-main
```
If it has gone just creating the file with the one line above and doing an update should rebuild it .

**Comment by dtantono** [comment]
do you mean just copy that command line to the terminal? because it is 404
![image](https://user-images.githubusercontent.com/29157187/236957978-60a6cc59-4b1e-42a5-9e8e-16021b99817a.png)

**Comment by philclifford** [comment]
no : create the file `/etc/deb-get/01-main.repo` with that as the content:

```bash
echo "https://raw.githubusercontent.com/wimpysworld/deb-get/main/01-main" | sudo tee /etc/deb-get/01-main.repo
```
then `deb-get update`

**Comment by dtantono** [comment]
That is weird I typed deb-get list and it shows nothing. But on /etc/deb-get/01-main.repo. it seems populated. Is this okay?
![2023-05-09_17-51](https://user-images.githubusercontent.com/29157187/237046349-5bdd71fb-c931-4451-8596-5628c9ccbdaa.png)
![2023-05-09_17-52](https://user-images.githubusercontent.com/29157187/237046370-ac6c7b16-c6b4-4a5a-99e4-5f3f7e610443.png)
![2023-05-09_17-52_1](https://user-images.githubusercontent.com/29157187/237046378-53d99b13-e48e-4f41-a5c5-e6b7f4cdc827.png)

**Comment by philclifford** [comment]
Utterly weird: I cannot reproduce your problem, but it clearly broken for you somehow.
All I can think at the moment is to `sudo rm /var/cache/deb-get/*` then do a `deb-get update` and wait for the background refresh to complete (when there is a cache for zotero and no lock file ) . Beyond that I think we're looking at purging the current install and re-installing...

**Comment by dtantono** [comment]
understood, it's getting better. But, I need to reconnect everything from scratch. So, for deb-get everything begin with sudo is ill-advised. is that so?

**Comment by philclifford** [comment]
Yes. It elevates when needed. You should always just use it without sudo.

**Comment by dtantono** [comment]
thank you

**Comment by dtantono** [comment]
Hi, Sorry, I reopened this case again. it looks like my repo list is gone from deb-get list again
So, when I try to sudo rm /var/cache/deb-get/* then do a deb-get update and wait for the background refresh to complete. I got this error.
What do you think?
![image](https://github.com/wimpysworld/deb-get/assets/29157187/34823beb-e252-44cb-9e36-ea7c28868d95)
![image](https://github.com/wimpysworld/deb-get/assets/29157187/10380146-ee64-40b4-b518-182a5c6902c6)

**Comment by philclifford** [comment]
Still cannot replicate this here.  :shrug: :confused:

**Comment by SteveLauC** [comment]
> don't `sudo deb-get` (we need to catch that - it breaks things! but not usually like this )


Hi @philclifford, I am the maintainer of Topgrade, and I come from [this issue](https://github.com/topgrade-rs/topgrade/issues/1019#issuecomment-2606204811). I want to know do `deb-get update` and `deb-get upgrade` currently require sudo?

**Comment by philclifford** [comment]
> > don't `sudo deb-get` (we need to catch 
> I want to know do `deb-get update` and `deb-get upgrade` currently require sudo?

Hi @SteveLauC sorry for the late reply! No neither option should be run with sudo: elevated privileges are obtained where necessary and indeed running as root or sudo is problematic.

**Comment by SteveLauC** [comment]
Thanks for the reply! @philclifford :)
