### ISSUE TITLE
list and search are hanging

### ISSUE THREAD

**Issue by brccabral** [wimpysworld/deb-get#828]
## Reporting a bug 🐛

Please make sure the version of `deb-get` you are using is up to date:

```bash
deb-get update
deb-get reinstall deb-get
```

### Expected behavior

`list` should print all available packages, but it hangs after `ferdium`.
`search` should show packages that matches the input and finish the process, but it hangs after `ferdium`.

### Actual behavior

`list` command hangs, as well as `search`.
`list` starts printing the packages but after `ferdium` it stops.
`search` it is possible to search any package alphabetically before `ferdium`, after that I can't get any response. But even when it finds something, it hangs and never completes.

### Steps to reproduce

Just run `deb-get list` - it will hang after `ferdium`
Just run `deb-get search dropbox` - it will print `dropbox` but never completes the process.

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
cat /etc/os-release
```
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### /etc/lsb-release

```bash
cat /etc/lsb-release
```
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```

#### deb-get version

```bash
deb-get version
```
```
0.3.8
```

### deb-get update

```bash
deb-get update
```
```
  [+] Updating /etc/deb-get/01-main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  108k    0  108k    0     0  84749      0 --:--:--  0:00:01 --:--:-- 84749
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 https://www.synaptics.com/sites/default/files/Ubuntu stable InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 https://esm.ubuntu.com/apps/ubuntu jammy-apps-security InRelease
Hit:7 https://esm.ubuntu.com/apps/ubuntu jammy-apps-updates InRelease
Hit:8 https://esm.ubuntu.com/infra/ubuntu jammy-infra-security InRelease
Hit:9 https://esm.ubuntu.com/infra/ubuntu jammy-infra-updates InRelease
Hit:10 https://ppa.launchpadcontent.net/papirus/papirus/ubuntu jammy InRelease
Reading package lists...
```

**Comment by brccabral** [comment]
Today it is back to normal

**Comment by philclifford** [comment]
Thanks. Sometimes this happens when upstreams are doing a release or there's some other "upstream" problem/change breaks us.  Some of these result in a package needing a definition update or even deprecating if they stop making debs or such.  Some of them self-heal when the upstream maintainer (or CI/CD in most cases!) gets around to providing the deb for all supported variants.

If it happens again you could try adding `--include-unsupported` to the list or search options.

**Comment by brccabral** [comment]
Is it possible to add some timeout and warn the user? The timeout could be an option or something...
