### ISSUE TITLE
I can to upgrade packages installed via deb-get.

### ISSUE THREAD

**Issue by musicfunfan** [wimpysworld/deb-get#834]
### Expected behavior
When i run the command ``deb-get upgrade`` i expect to update the packages that is installed via deb-get. 

### Actual behavior
When i run the command i get this output  ``E: Unable to correct problems, you have held broken packages.``

### Steps to reproduce
Just run ``deb-get upgrade``
### System information
```bash
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```
#### /etc/lsb-release

```bash
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"
```

#### deb-get version

```bash
deb-get version is 0.3.8
```

### deb-get update

```bash
 deb-get update
  [+] Updating /etc/deb-get/01-main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  108k  100  108k    0     0  75614      0  0:00:01  0:00:01 --:--:--  380k
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://packages.linuxmint.com vera InRelease
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Hit:5 http://packages.linuxmint.com vera Release
Hit:7 https://packages.element.io/debian default InRelease
Hit:8 https://ppa.launchpadcontent.net/flexiondotorg/obs-fully-loaded/ubuntu jammy InRelease
Hit:9 http://security.ubuntu.com/ubuntu jammy-security InRelease
Fetched 108 kB in 15s (7007 B/s)
Reading package lists...
  [+] openrgb () has an update pending. 0.7 is available.
```
This may be a problem with apt... But i do not know how to fix it. 
I try ``sudo apt install -f`` to fix broken dependencies but this is not the problem... Coz i see no broken dependencies. I do not how to troubleshoot this... 
Thenx in advance ;)

**Comment by flexiondotorg** [comment]
This is not a bug in `deb-get`, your system has a broken package state.

**Comment by musicfunfan** [comment]
Hmmm ok... But when i update with apt for the rest of the system work fine... I know this is out of the scope but can you help fix it?

**Comment by rasa** [comment]
I just ran
```
deb-get install zoom
```
and got
`E: Unable to correct problems, you have held broken packages.`

When I removed `-q=2` from the `apt-get` call [here](https://github.com/wimpysworld/deb-get/blob/4303aa855b516079eab9fca467f4eb69a30ac03c/deb-get#L278), the problem was made visible:

```
The following packages have unmet dependencies:
 zoom : Depends: libgl1-mesa-glx but it is not installable
        Depends: libegl1-mesa but it is not installable
E: Unable to correct problems, you have held broken packages.
```
If you want, I can submit a PR that reruns the command that fails without the `-q=2`, so users can see the underlying issue.
