### ISSUE TITLE
Add AWS session-manager-plugin for SSM

### ISSUE THREAD

**Issue by arthurzenika** [wimpysworld/deb-get#837]
## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: session-manager-plugin 
 - Download URL:  "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
 - Website URL: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html & https://github.com/aws/session-manager-plugin
 - App Summary:  This plugin helps you to use the AWS Command Line Interface (AWS CLI) to start and end sessions to your managed instances

**Comment by philclifford** [comment]
Having reviewed that discussion and the critique there of the state of the packaging I feel we cannot support this at this time.
If the issues with the quality of packaging and naming are addressed (and critically it is possible to determine the available released version) then this can be re-opened.
