### ISSUE TITLE
Replace MS-Office-Electron with MS-365-Electron

### ISSUE THREAD

**Issue by miloumeeloo** [wimpysworld/deb-get#844]
MS-Office-Electron is not available anymore.
Could you replace with MS-365-Electron ?
https://github.com/agam778/MS-365-Electron

**Comment by diegobersanetti** [comment]
I tested a simple fork of the ms-office-electron, named ms-365-electron and put in the /etc/deb-get/99-local.d folder, and the installation went fine.

The content of the definition file follows:

`DEFVER=1
get_github_releases "agam778/MS-365-Electron" "latest"
if [ "${ACTION}" != "prettylist" ]; then
    URL=$(grep "browser_download_url.*${HOST_ARCH}\.deb\"" "${CACHE_FILE}" | head -n1 | cut -d'"' -f4)
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f8 | tr -d v)"
fi
PRETTY_NAME="Microsoft 365"
WEBSITE="https://agam778.github.io/MS-365-Electron/"
SUMMARY="A Microsoft Office Online Desktop Client made with Electron."`
