### ISSUE TITLE
Add AppimageLauncher

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#85]
AppimageLauncher is a open source application Integrate AppImages to your application launcher with one click
They have a deb available from their website.
https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained/released. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
