### ISSUE TITLE
Option to accept defaults for installs with EULA, installation options, etc.

### ISSUE THREAD

**Issue by dchurch315** [wimpysworld/deb-get#868]
## Requesting a new feature 🧑‍💻

To make this usable for automation scripts, we need some way of answering prompts for installers. For example, the google-chrome-stable download puts up a EULA question before it will install -  you have to answer 1 to agree before it continues.

**Comment by nazrhyn** [comment]
Looking at the source, it looks like you can set `DEBIAN_FRONTEND=noninteractive` to skip the prompt. Just confirmed this locally like this:
```shell
DEBIAN_FRONTEND=noninteractive deb-get install atuin
```

Here's the source location:
https://github.com/wimpysworld/deb-get/blob/35d22107f5c7fad9d74ba87d2953b3f3c734cb10/deb-get#L222-L233

**Comment by dchurch315** [comment]
Awesome - should make my workstation reinstalls script much more automated.
