### ISSUE TITLE
Add Stacer

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#87]
Stacer is a open source system monitor
They have a deb available from their website.
https://github.com/oguzhaninan/Stacer/releases/download/v1.1.0/stacer_1.1.0_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
