### ISSUE TITLE
Proposal: descriptive env var name for GitHub PAT

### ISSUE THREAD

**Issue by roadkell** [wimpysworld/deb-get#879]
## Proposing a new feature 👩‍💻 ##
How about a more descriptive environment variable for the GitHub access token, for example, `DEBGET_GITHUB_API_TOKEN`, similarly to the [Homebrew](https://docs.brew.sh/Manpage) one?
Alternatively, an env var like `GITHUB_AUTH_TOKEN` or `GITHUB_API_TOKEN`, [commonly used by other tools](https://github.com/search?q=%2F%5C%24.%3FGITHUB_%28API%7CAUTH%29_TOKEN.%3F%2F+language%3AShell&type=code) and possibly present in the environment already, would minimize the number of required tokens and env vars (they might have different scopes though).

## Reasoning ##
If Gitlab, Codeberg, etc. PAT support is to be added in the future, it would require new env vars. Having them uniformly named is nice to have.

## Caveats ##
Simply changing behavior to a new one would introduce breaking change for existing users. Checking both new and old env vars for existence can prevent that.

**Comment by philclifford** [comment]
Having a distinct name allows users to chose not to put all their keys in one basket should they wish to have nuanced permissions for example.
They are at liberty to
```shell
export GH_TOKEN=$DEBGET_TOKEN 
export GITHUB_AUTH_TOKEN=$GH_TOKEN
```
if they wish.  Everyone using the same ENV is a two-edged sword and where it impacts keys and permissions the default behaviour should be towards supporting and encouraging granularity and specificity.
