### ISSUE TITLE
App Request: OpenTofu

### ISSUE THREAD

**Issue by felicianotech** [wimpysworld/deb-get#880]
## Requesting a new app ✨

 - [ x ] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: OpenTofu
 - Download URL: TBD
 - Website URL: https://opentf.org/
 - App Summary: A fork of Terraform

I am requesting to add OpenTF to `deb-get`. This is a placeholder issue as the tool doesn't have its first release yet but it will in the near future. This was, once it comes out, we, possibly me, can quickly make the PR and get this added.

Part of my justification for getting this added is that Terraform itself is already listed in `deb-get`. It might normally be unusual to add a fork here and especially one without it's first release but I would say that OpenTF is different. This will be a **huge** community fork that will likely go mainstream before the end of this year. https://opentf.org/fork

**Comment by philclifford** [comment]
https://opentofu.org/blog/opentofu-is-going-ga/ Released Jan 10

https://opentofu.org/docs/intro/install/deb/ has details required to add their repo so a PR should be straightforward.
