### ISSUE TITLE
Manpage: Links to URL's

### ISSUE THREAD

**Issue by TriMoon** [wimpysworld/deb-get#898]
## Reporting a bug 🐛

I just installed this tool, and went into the manpage to see how to use it etc.
I noticed when i used <kbd>CTRL</kbd>+<kbd>MouseClick</kbd> on a link and ending up on a 404-page in the browser that links are not protected vs word-breaks.

### Expected behavior

Able to <kbd>CTRL</kbd>+<kbd>MouseClick</kbd> on all the links to automatically open the link in the browser.

### Actual behavior

The link to `EXTREPO.md` was split across lines, which made the shell hyperlinking broken for that URL.
https://github.com/wimpysworld/deb-get/blame/main/docs/deb-get.1#L270
![image](https://github.com/wimpysworld/deb-get/assets/1723378/0b7d3056-50ac-4dff-8691-44b1adf08cba)

### Steps to reproduce

See above

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
```

#### /etc/lsb-release

```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar
DISTRIB_DESCRIPTION="Ubuntu 23.04"
```

#### deb-get version

```bash
0.3.9
```

### deb-get update

```bash
  [+] Updating /etc/deb-get/01-main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  110k  100  110k    0     0   117k      0 --:--:-- --:--:-- --:--:--  413k
Hit:1 https://repo.steampowered.com/steam stable InRelease
Hit:2 http://archive.ubuntu.com/ubuntu lunar InRelease
Hit:3 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
Get:4 http://download.opensuse.org/repositories/hardware:/razer/xUbuntu_23.04  InRelease [1.521 B]
Hit:5 http://security.ubuntu.com/ubuntu lunar-security InRelease
Hit:6 https://ppa.launchpadcontent.net/openrazer/stable/ubuntu lunar InRelease
Hit:7 https://ppa.launchpadcontent.net/polychromatic/stable/ubuntu lunar InRelease
Hit:8 https://repo.waydro.id lunar InRelease
Hit:9 tor+https://deb.torproject.org/torproject.org lunar InRelease
Fetched 1.521 B in 2s (860 B/s)
Reading package lists...
```

**Comment by philclifford** [comment]
This cannot be fixed: even forcing line-breaks to put links on the start of lines with ugly markdown can lead to split and hyphenated links in `man` presentation, and no additional dancing with `man -nh` and the like results in the behaviour you'd like for all terminals, current line sizes, pagers, ...  
`man -H` fails for me so even that is not an option I can recommend.
If you unmaximise and resize the terminal it may be possible to get the link into an unsplit state, but it would be quicker to just go to https://raw.githubusercontent.com/wimpysworld/deb-get/main/docs/deb-get.1.md at the start.

**Comment by TriMoon** [comment]
Sorry to say but a broken link in a documentation is worse as no link at all...
Maybe put links at the bottom on a line by themself, in a references section or similar like on wiki pages...
Anyhow, the current state is breathing amateurism, sorry to say that in such a hard way...
