### ISSUE TITLE
deb-get fails when user's `.curlrc` contains `remote-header-name` option

### ISSUE THREAD

**Issue by rasa** [wimpysworld/deb-get#900]
### Expected behavior

`deb-get update` works

### Actual behavior

`deb-get update` failed. After I removed the `2>/dev/null` that was swallowing the error [here](https://github.com/wimpysworld/deb-get/blob/4303aa855b516079eab9fca467f4eb69a30ac03c/deb-get#L424), curl reports the error
`curl: showing headers and --remote-header-name cannot be combined` 

### Steps to reproduce

```
echo remote-header-name >>~/.curlrc
deb-get update
```

So, I am planning on submitting a PR that adds the `-q` (aka `--disable`) option to all curl calls, so curl doesn't read the user's `.curlrc` file. But I see that the `-q` option has already been added on [line 689](https://github.com/wimpysworld/deb-get/blob/4303aa855b516079eab9fca467f4eb69a30ac03c/deb-get#L689).

So, I'm curious as to why `-q` is added on [line 689](https://github.com/wimpysworld/deb-get/blob/4303aa855b516079eab9fca467f4eb69a30ac03c/deb-get#L689), but not on [line 693](https://github.com/wimpysworld/deb-get/blob/4303aa855b516079eab9fca467f4eb69a30ac03c/deb-get#L693), or any other curl calls.

**Comment by philclifford** [comment]
line 693 should indeed also have `-q` . Thanks in advance for the PR to fix it.
