### ISSUE TITLE
Add Audacity

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#91]
Audacity is open source audio editor
They have a deb available from their website.
http://ftp.debian.org/debian/pool/main/a/audacity/audacity_2.4.2~dfsg0-5_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any packages from the official Debian or Ubuntu archives. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
