### ISSUE TITLE
Add Forticlient-VPN

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#92]
Forticlient is a robust VPN
They have a deb available from their website.
https://filestore.fortinet.com/forticlient/downloads/forticlient_vpn_7.0.0.0018_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that provides a reliable way to dynamically determine the current published version. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
