### ISSUE TITLE
Add GoogleChrome-Beta

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#93]
Google Chrome Beta is famous browser from Google
They have a deb available from their website.
https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any daily/nightly, beta or pre-release software. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
