### ISSUE TITLE
do MIT-licensed packages need EULA=(non-empty) ?

### ISSUE THREAD

**Issue by mralusw** [wimpysworld/deb-get#931]
For example I see that https://github.com/wimpysworld/deb-get/blob/main/01-main/packages/mdview has an EULA (thus prompting for confirmation). But it's MIT-licensed, just like `deb-get` itself. I somehow doubt that among all the other packages (none of which has a non-empty `EULA=`, except for chrome), there are no other MIT's.

**Comment by philclifford** [comment]
IANAL, but no in general you're right - it is solely there to meet requirements of the likes of `chrome`.
If, however, the author of an app adds a link to their own license in their own PR then so-be-it. It may be MIT now but could change.  One might discuss with them whether there is value in provoking an action by the end-user that purports to "accept" an MIT license. @mapitman might decide to remove that line if he felt there was no value in forcing users to answer an EULA prompt for `mdview`
It might also be an area where the CONTRIBUTING.md could be improved.

**Comment by mapitman** [comment]
This is the second thing I kind of messed up on when submitting the pull request for my application. I'll submit a PR later to remove this.
