### ISSUE TITLE
Requesting a new app: Nekoray

### ISSUE THREAD

**Issue by itsMohammadHeidari** [wimpysworld/deb-get#939]
## Requesting a new app ✨
 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Nekoray
 - Download URL: [https://github.com/MatsuriDayo/nekoray/releases/download/3.24/nekoray-3.24-2023-10-28-debian-x64.deb](https://github.com/MatsuriDayo/nekoray/releases/download/3.24/nekoray-3.24-2023-10-28-debian-x64.deb)
 - Website URL: [https://matsuridayo.github.io/](https://matsuridayo.github.io/)
 - App Summary: Qt based cross-platform GUI proxy configuration manager (backend: v2ray / sing-box).

**Comment by philclifford** [comment]
It's hard to review with confidence without better Chinese, but the definition in the PR can easily be copied and dropped into `/etc/deb-get/99-local.d/` or added to and external repo if the PR doesn't get accepted and merged.
