### ISSUE TITLE
Proposal: use extrepo as the source of metadata

### ISSUE THREAD

**Issue by andrewshadura** [wimpysworld/deb-get#94]
There’s a project similar in scope, called [extrepo](https://grep.be/blog/en/computer/debian/Announcing_extrepo/).

To avoid duplication of effort, I think it should probably make sense for deb-get to adopt its format and start using its data:

https://salsa.debian.org/extrepo-team/extrepo-data/-/tree/master

**Comment by hsbasu** [comment]
There is another package with similar functionalities that I found recently: [pacstall](https://github.com/pacstall/pacstall). It might be worth reviewing.

**Comment by flexiondotorg** [comment]
As we work towards #313 it is clear we will have our own package metadata.
