### ISSUE TITLE
Add Clementine

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#97]
an open source music player based in QT
They have a deb available from their website.
https://github.com/clementine-player/Clementine/releases/tag/1.3.1

**Comment by flexiondotorg** [comment]
Sorry, we are only accepting software that is actively maintained. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)

**Comment by dtantono** [comment]
it is actively maintained and updated https://github.com/clementine-player/Clementine/releases

**Comment by flexiondotorg** [comment]
There has not been a stable release for 6 years.
