### ISSUE TITLE
Add nala support/Make a version of nala for deb-get

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [wimpysworld/deb-get#973]
## Requesting a new feature 🧑‍💻

If you are proposing a new feature for `deb-get` please describe the proposed
feature with as much detail as possible here:
I use nala as my apt frontend of choice, and i was wondering if it would be possible to get deb-get installed apps to act like apt apps eg. updated with `apt upgrade`, or in this case, `nala upgrade`.
EDIT: 29/01/2024
To specify, was meaning if it was possible to get deb-get install apps detected by nala so that `nala upgrade` upgraded them.

**Comment by philclifford** [comment]
It would be possible to detect that `nala` is available and use it. Taking the presence of  `nala` as a mandate to use it without explicit request (e.g. a `--use_nala` option or the like) would imo not be good. I use Nala, but not by default.

If I wanted to use Nala for all apt operations I expect I could achieve that locally (aliases, shell functions, symlinks, PATH, ...) without impacting other local accounts or requiring wider changes.

**Comment by philclifford** [comment]
`nala upgrade` will upgrade all `deb-get`-installed apps that are installed via `apt` or `ppa` methods.  `nala` obviously cannot currently upgrade those that are using web, direct or git sources.

**Comment by philclifford** [comment]
Not possible beyond what is described above, where `nala update/upgrade` will already do the desired work. The app must be installed from and apt repo or ppa for nala to deal with it.
