### ISSUE TITLE
Add Discord-Beta

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#98]
Discord client Beta Channel
They have a deb available from their website.
https://dl.discordapp.net/apps/linux/0.0.17/discord-0.0.17.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any daily/nightly, beta or pre-release software. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
