### ISSUE TITLE
[Question] List Unsupported App

### ISSUE THREAD

**Issue by zero77** [wimpysworld/deb-get#988]
## Requesting a new feature 🧑‍💻 - Reporting a bug 🐛
Is there a way to list all apps even if they're not supported as I believe I have some installed that don't show Debian support.
Using your comments from https://github.com/wimpysworld/deb-get/issues/826, I want to find all installed apps and open a PR to add the correct Debian code names.

**Comment by philclifford** [comment]
There's already a parameter to include unsupported apps. `--include-unsupported`
If submitting a PR to extend Debian support for an app please ensure the added release is actually well tested for the app to install and run without issues or formally supported by the upstream with a specific release.
