### ISSUE TITLE
Add Opera-Beta

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#99]
Opera browser Beta Channel
They have a deb available from their website.
https://download3.operacdn.com/pub/opera-beta/87.0.4390.8/linux/opera-beta_87.0.4390.8_amd64.deb

**Comment by flexiondotorg** [comment]
Sorry, we won't be accepting any daily/nightly, beta or pre-release software. Please see:

* [Add guidelines for what packages are acceptable for inclusion](https://github.com/wimpysworld/deb-get/commit/99551cbc516c1853a959498d11ed254562dfeb73)
