### ISSUE TITLE
Requesting a new app : Jitsi

### ISSUE THREAD

**Issue by M-Rick** [wimpysworld/deb-get#993]
## Requesting a new app ✨

 - [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Jitsi
 - Download URL: https://github.com/jitsi/jitsi-meet-electron/releases/download/v2024.1.0/jitsi-meet-amd64.deb
 - Website URL: https://jitsi.org/jitsi-meet/
 - App Summary: Jitsi Meet is an open source video conferencing application. In addition to audio and video, screen sharing is available, and new members can be invited via a generated link. Jitsi implemented end-to-end encryption (E2EE) with dynamic key management . Jitsi offers the ability to record meetings by streaming them to youtube. Self-installed Jitsi Meet deployments need to install and set up Jibri to support this capability. The client also has the capability to save a local recording.

**Comment by philclifford** [comment]
#972
