### ISSUE TITLE
"Missing required information of github package croc"

### ISSUE THREAD

**Issue by KlfJoat** [wimpysworld/deb-get#997]
Please make sure the version of `deb-get` you are using is up to date:

(excerpt)
```bash
...
Preparing to unpack .../deb-get_0.4.0-1_all.deb ...
Unpacking deb-get (0.4.0-1) over (0.4.0-1) ...
Setting up deb-get (0.4.0-1) ...
...
```
Done.

### Expected behavior

`deb-get update` is resilient against missing information in GitHub packages when the source website changes and the commands return no data or garbage data.

### Actual behavior

`deb-get update` throws an error because yet another package returns no data. This one is `croc`, whatever that is.

```text
[!] ERROR! Missing required information of github package croc:
URL=
VERSION_PUBLISHED=
```

This is a recurring problem (#962  #822) because `deb-get` doesn't gracefully handle the entirely foreseeable and obvious case where the fragile commands used to fill those variables returns nothing or returns garbage. It downloads data from external websites, not versioned APIs. Why is it not resilient against this? Why can't it WARN me and continue processing the rest of the package data? Updates still work, but installs don't. So now there are only 32 packages that users can install from scratch using `deb-get`.

```text
$ deb-get list                                                                      
1password                                      
activitywatch                                                                                       
agena                                                                                               
alduin                                                                                              
android-messages-desktop                                                                            
antimicrox                                                                                          
anydesk                                                                                             
appimagelauncher                                                                                    
atom                                                                                                
atomic                                                                                              
audio-recorder                                                                                      
authme                                                                                              
azuredatastudio                                                                                     
balena-etcher                                             
bat                                                                                                 
bitwarden                                                                                           
bitwig-studio                                                                                       
blanket                                           
blockbench                                                                                          
bluejeans-v2                                                                                        
bottom                                                                                              
brave-browser                                                                                       
brisqi                                                                                              
caddy                                                                                               
caprine
cawbird                                           
chronograf                                        
code                                                                                                
codium
com.github.tkashkin.gamehub                                                                         
copyq                                                                                               
cosign                                            
$
```

### Steps to reproduce

Run `deb-get update`. Look at error on screen.

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
```

#### /etc/lsb-release

```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.10
DISTRIB_CODENAME=mantic
DISTRIB_DESCRIPTION="Ubuntu 23.10"
```

#### deb-get version

```bash
0.4.0
```

### deb-get update

```bash
$ deb-get update
[sudo] password for klfjoat:
  [+] Updating /etc/deb-get/01-main
 #=#=-#    #
  [+] Updating cache of supported apps in the background
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.html
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.html
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
  [+] Updating /var/cache/deb-get/you-dont-need-to-know-the-software-i-install.json
Hit:1 https://you.dont.need/to/know the InRelease
Hit:2 https://software.i.install/you/dont/need to InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu mantic InRelease 
Hit:4 https://know.the.software/i install InRelease
Hit:5 https://you.dont.need/to know InRelease
Hit:6 http://security.ubuntu.com/ubuntu mantic-security InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu mantic-updates InRelease 
Ign:8 https://the.software.i.install you InRelease                                          
Hit:9 http://us.archive.ubuntu.com/ubuntu mantic-backports InRelease                                
Hit:10 https://dont.need.to/know the InRelease
Err:11 https://software.i.install.you dont Release
  404  Not Found [IP: 192.0.2.1 443]
Hit:12 https://ppa.launchpadcontent.net/need/to-know/ubuntu mantic InRelease
Hit:13 https://ppa.launchpadcontent.net/the/software/ubuntu kinetic InRelease
Hit:14 https://ppa.launchpadcontent.net/i/install/ubuntu mantic InRelease
Hit:15 https://ppa.launchpadcontent.net/you/dont-need/ubuntu mantic InRelease
Reading package lists...
E: The repository 'https://to.know.the.software i Release' does not have a Release file.
W: https://install.you.dont/need/to/know/InRelease: Key is stored in legacy trusted.gpg key ring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
$   [!] ERROR! Missing required information of github package croc:
URL=
VERSION_PUBLISHED=
```

**Comment by fedz1** [comment]
It is OK to fix package `croc`, but it would be very convenient if deb-get could gracefully issue a warning but continue processing the following packages. Tank you

**Comment by KlfJoat** [comment]
@philclifford  @flexiondotorg 

It took over 2 months for #962 to be fixed by #963.

It's been over a month since it was opened, and #998 has not been approved to fix this problem.

It's been 3 weeks since #1027 was merged, and a new release has not been created to fix these very foreseeable problems for users.

It feels like, though work is happening, it's not improving the user experience or it takes a long time to fix what's broken.

**Comment by Mark3xtrm** [comment]
So, no update on this? Deb-get is a great project, but it needs to be mantained to be more reliable

**Comment by KlfJoat** [comment]
@Mark3xtrm 
> So, no update on this? Deb-get is a great project, but it needs to be mantained to be more reliable

I will give it to them. Finally, after nearly a year of complaints, they have fixed the very foreseeable underlying bug that caused this to be a problem. They made an update some time earlier this year, and now deb-get will throw errors in the background about bad 'package' definitions, but it **WILL** complete an update for all 'packages' that have valid definitions rather than getting stopped by 1 bad one.

**Comment by Mark3xtrm** [comment]
> [@Mark3xtrm](https://github.com/Mark3xtrm)
> 
> > So, no update on this? Deb-get is a great project, but it needs to be mantained to be more reliable
> 
> I will give it to them. Finally, after nearly a year of complaints, they have fixed the very foreseeable underlying bug that caused this to be a problem.
> 
> It wasn't the [#998](https://github.com/wimpysworld/deb-get/pull/998) PR that fixed it, like they claimed in this Issue. But they DID make an update some time earlier this year, and now deb-get will throw errors in the background about bad 'package' definitions, but it **WILL** complete an update for all 'packages' that have valid definitions rather than getting stopped by 1 bad one.

Good, and glad they worked well. But unfortunately the fact remains that when a message like `[!] ERROR! Missing required information of github package jellyfin-media-player` (i.e.) appears, that package keeps getting out of date.

Also you could hide those error messages, maybe behind a generic message like `There are errors on some packages that do not have valid definitions, type deb-get --show-package-errors to see them`, instead of showing them in the terminal perpetually.

At least this is what happens to me, after I do the `deb-get uprgade`, until I close the terminal and reopen it, errors like these keep appearing
```
 ❯ [!] ERROR! Missing required information of website package tonelib-bassdrive:
URL=
VERSION_PUBLISHED=2.1-0
 [!] ERROR! Missing required information of website package tonelib-gfx:
URL=
VERSION_PUBLISHED=4.8-7
 [!] ERROR! Missing required information of website package tonelib-jam:
URL=
VERSION_PUBLISHED=4.8-7
 [!] ERROR! Missing required information of website package tonelib-metal:
URL=
VERSION_PUBLISHED=1.4-0
 [!] ERROR! Missing required information of website package tonelib-noisereducer:
URL=
VERSION_PUBLISHED=2.0-2
 [!] ERROR! Missing required information of website package tonelib-tubewarmth:
URL=
VERSION_PUBLISHED=2.2-1 2.0.1
```

Note that I don't know why it says those libraries are missing, I don't even know if they are required (mistakenly?) by `deb-get`, that not finding them complains, or for what other reason.
I'm referring to the latest ones, `jellyfin-media-player` is actually a package I have installed, but apparently it can no longer be updated by `deb-get` because it has precisely obsolete definitions.
